import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Segment } from '@lectheo/domain'
import type { ConceptFx, ExtraOccurrenceFx, ItemFx, LectureFx } from '@lectheo/db/seed'
import type { BankResult, Candidate } from './bank'
import type { RevisionResult } from './revise'
import { EXTRA_EDGES, fixConcept, fixTranscript } from './reviewed'
import { REPO_ROOT } from './cache'
import type { LecturePlan } from './curriculum'
import { SLOT_KIND } from './drafts'
import type { Extraction, SeedEdge } from './extract'

/*
 * Writes the generated library bank as typed TS fixtures under packages/db/src/seed/fixtures/, so
 * seeding stays deterministic and AI-free (ADR-010). Answers, rubrics and hints only ever land in
 * the item's secret fields (ADR-009: they become item_secrets rows).
 */

export const FIXTURES_DIR = join(REPO_ROOT, 'packages/db/src/seed/fixtures')

export interface LectureOutput {
  plan: LecturePlan
  segments: Segment[]
  extraction: Extraction
  bank: BankResult
  /** Bank selection after reviewer revisions, and what is still missing. */
  selected: Candidate[]
  shortfall: BankResult['shortfall']
  revisions: RevisionResult[]
}

const NAME: Readonly<Record<LecturePlan['key'], string>> = {
  l3: 'lecture3',
  l4: 'lecture4',
  l5: 'lecture5',
}

export function lectureFx(out: LectureOutput): LectureFx {
  const { plan, segments, extraction } = out
  const byKey = new Map(extraction.concepts.map((c) => [c.canonicalKey, c]))
  const concepts: ConceptFx[] = plan.concepts.map(({ key, name }) => {
    const c = byKey.get(key)
    if (!c) throw new Error(`${plan.key}: extraction has no ${key}`)
    return {
      key,
      name,
      ...fixConcept(
        key,
        c.summary,
        c.keyPoints.map((k) => ({ id: k.id, text: k.text, segs: [...k.segmentIdxs] })),
      ),
      segs: [...c.segmentIdxs],
      salience: c.salience,
    }
  })
  return {
    key: plan.key,
    seq: plan.seq,
    title: plan.title,
    youtubeId: plan.youtubeId,
    start: plan.start,
    end: plan.end,
    duration: plan.duration,
    fallbackAudioUrl: plan.fallbackAudioUrl,
    segments: segments.map(({ idx, startMs, endMs, text }) => ({
      idx,
      startMs,
      endMs,
      text: fixTranscript(plan.key, idx, text),
    })),
    concepts,
  }
}

/** Concepts an earlier lecture introduced that this one revisits. */
export function extraOccurrences(out: LectureOutput): ExtraOccurrenceFx[] {
  const introduced = new Set(out.plan.concepts.map((c) => c.key))
  return out.extraction.concepts
    .filter((c) => !introduced.has(c.canonicalKey))
    .map((c) => ({
      concept: c.canonicalKey,
      lecture: out.plan.key,
      segs: [...c.segmentIdxs],
      salience: c.salience,
    }))
}

/** Selected candidates → fixture items; variants count from 1 per (concept, kind). */
export function itemsFx(selected: readonly Candidate[]): ItemFx[] {
  const used = new Map<string, number>()
  return selected.map((c) => {
    const r = c.record
    const slot = `${r.conceptKey}:${r.kind}`
    const variant = (used.get(slot) ?? 0) + 1
    used.set(slot, variant)
    // ponytail: the record's kind/payload pairing is guaranteed by draft-items' mappers.
    return {
      concept: r.conceptKey,
      kind: r.kind,
      variant,
      segs: [...r.segmentIdxs],
      publicPayload: r.publicPayload,
      answerKey: r.answerKey,
      distractorMeta: r.distractorMeta,
      rubric: r.rubric,
      hints: r.hints,
      leakKeywords: [...r.leakKeywords],
      verification: c.verification,
      model: c.model,
      promptVersion: c.promptVersion,
    } as ItemFx
  })
}

/** Generated edges plus the reviewed EXTRA_EDGES (deduped by from/relation/to). */
function withExtraEdges(edges: readonly SeedEdge[]): SeedEdge[] {
  const key = (e: SeedEdge) => `${e.from}:${e.relation}:${e.to}`
  const seen = new Set(edges.map(key))
  return [...edges, ...EXTRA_EDGES.filter((e) => !seen.has(key(e)))]
}

const banner = (lines: readonly string[]): string =>
  ['/**', ...lines.map((l) => ` * ${l}`.trimEnd()), ' */'].join('\n')

const GENERATED = [
  'GENERATED by scripts/seed-library.ts (Opus 5.5 extraction/drafting, GPT-6.1 Sol blind',
  'verification). Do not edit by hand: change the script and re-run it.',
]

function write(file: string, header: string, body: string): string {
  const path = join(FIXTURES_DIR, file)
  writeFileSync(path, `${header}\n${body}\n`)
  return path
}

export function emitFixtures(outputs: readonly LectureOutput[], edges: readonly SeedEdge[]): void {
  const paths: string[] = []
  for (const out of outputs) {
    const name = NAME[out.plan.key]
    const header = banner([
      `CS50x 2026 ${out.plan.title}, core window ${out.plan.start}–${out.plan.end} (video time).`,
      out.plan.windowNote,
      `Segments are the official subtitles (${out.plan.srtUrl}), segmented by @lectheo/domain;`,
      'CC BY-NC-SA 4.0, CS50x 2026 by Harvard University, adapted by Lectheo.',
      'Subtitles lightly corrected for ASR errors (scripts/lib/reviewed.ts); timestamps unchanged.',
      ...GENERATED,
    ])
    const itemsHeader = banner([
      `Verified practice bank for ${out.plan.title} (F7.3).`,
      ...GENERATED,
    ])
    paths.push(
      write(
        `${out.plan.key}-lecture.ts`,
        `import type { LectureFx } from './types'\n\n${header}`,
        `export const ${name}: LectureFx = ${JSON.stringify(lectureFx(out), null, 2)}`,
      ),
      write(
        `${out.plan.key}-items.ts`,
        `import type { ItemFx } from './types'\n\n${itemsHeader}`,
        `export const ${name}Items: ItemFx[] = ${JSON.stringify(itemsFx(out.selected), null, 2)}`,
      ),
    )
  }
  const edgesHeader = banner([
    'Concept edges (F7.2) and cross-lecture occurrences. `from depends_on to` = "to is a',
    'prerequisite of from"; depends_on is a DAG. Segment idxs refer to `lecture`.',
    ...GENERATED,
  ])
  paths.push(
    write(
      'edges.ts',
      `import type { EdgeFx, ExtraOccurrenceFx } from './types'\n\n${edgesHeader}`,
      [
        `export const EDGES: EdgeFx[] = ${JSON.stringify(withExtraEdges(edges), null, 2)}`,
        `export const EXTRA_OCCURRENCES: ExtraOccurrenceFx[] = ${JSON.stringify(outputs.flatMap(extraOccurrences), null, 2)}`,
      ].join('\n\n'),
    ),
  )
  paths.push(writeReport(outputs))
  const quoted = paths.map((p) => `"${p}"`).join(' ')
  execSync(`pnpm exec prettier --write ${quoted}`, { cwd: REPO_ROOT, stdio: 'inherit' })
}

/** Shortfall and rejection stats, so tests and the README read the bank's real numbers. */
function writeReport(outputs: readonly LectureOutput[]): string {
  const shortfall = outputs.flatMap((o) =>
    o.shortfall.map((s) => ({
      concept: s.conceptKey,
      kind: SLOT_KIND[s.slot],
      missing: s.missing,
    })),
  )
  const stats = outputs.map((o) => ({
    lecture: o.plan.key,
    drafted: o.bank.candidates.length,
    rejected: o.bank.candidates.filter((c) => c.verification.verdict === 'fail').length,
    selected: o.bank.selected.length,
    revised: o.revisions.filter((r) => r.verdict === 'pass').length,
    final: o.selected.length,
  }))
  const revisions = outputs.flatMap((o) => o.revisions)
  const header = banner([
    'Library bank shortfall and verification stats (Architecture §5.3: at most one redraft round;',
    'slots still failing verification are left empty and labeled here).',
    ...GENERATED,
  ])
  return write(
    'bank-report.ts',
    `import type { ItemKind } from '@lectheo/contracts'\n\n${header}`,
    [
      `export const BANK_SHORTFALL: { concept: string; kind: ItemKind; missing: number }[] = ${JSON.stringify(shortfall, null, 2)}`,
      `export const BANK_STATS = ${JSON.stringify(stats, null, 2)} as const`,
      `/** Reviewer-requested redrafts (scripts/lib/reviewed.ts REVISIONS) and their verdicts. */
export const BANK_REVISIONS = ${JSON.stringify(revisions, null, 2)} as const`,
    ].join('\n\n'),
  )
}
