/**
 * F9.15: "Explain in depth" for the CS50x library concepts, generated once on the dev key and
 * written to packages/db/src/seed/fixtures/depth.ts. It only adds data: segments, concepts, items
 * and stable ids don't change. Never touches a database; `pnpm db:seed` loads the fixture.
 *
 *   AI_FAKE=0 AI_GATEWAY_KEY_NAME=dev pnpm --filter @lectheo/scripts library-depth [-- --force]
 *
 * The pipeline's explainConcepts call, one per lecture, checked by the same `toDepths`. Idempotent:
 * lectures whose concepts all have depth are skipped (--force regenerates them), and each model
 * output is cached under .cache/seed-library/, so a rerun never pays twice.
 */
import { execSync } from 'node:child_process'
import { rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parseArgs } from 'node:util'
import { explainConceptsTask, runTask, toDepths, type ExplainConceptsOutput } from '@lectheo/ai'
import type { ConceptDepth } from '@lectheo/contracts'
import { LECTURES, LIBRARY_DEPTH, lectureId, type LectureFx } from '@lectheo/db/seed'
import {
  assertDevGateway,
  cachePath,
  cached,
  ledgerCost,
  readLedger,
  REPO_ROOT,
  scriptContext,
} from './lib/cache'

const RUN = 'library-depth'
const BUDGET_USD = 3
const FIXTURE = join(REPO_ROOT, 'packages/db/src/seed/fixtures/depth.ts')

const out = (line: string): void => {
  process.stdout.write(`${line}\n`)
}

/** The lecture's concepts and only the segments they cite, as the pipeline step builds them. */
function inputFor(lecture: LectureFx) {
  const cited = new Set(
    lecture.concepts.flatMap((c) => [...c.segs, ...c.keyPoints.flatMap((k) => k.segs)]),
  )
  return {
    segments: lecture.segments
      .filter((s) => cited.has(s.idx))
      .map(({ idx, text }) => ({ idx, text })),
    concepts: lecture.concepts.map((c) => ({
      key: c.key,
      name: c.name,
      summary: c.summary,
      keyPoints: c.keyPoints.map((k) => k.text),
      segmentIdxs: c.segs,
    })),
  }
}

async function depthFor(lecture: LectureFx, force: boolean): Promise<Map<string, ConceptDepth>> {
  const cacheName = `depth-${lecture.key}.json`
  if (force) rmSync(cachePath(cacheName), { force: true })
  const output = await cached<ExplainConceptsOutput>(cacheName, async () => {
    const { output } = await runTask(
      explainConceptsTask,
      inputFor(lecture),
      scriptContext(RUN, BUDGET_USD, lectureId(lecture.key)),
    )
    return output
  })
  return toDepths(
    output,
    new Set(lecture.concepts.map((c) => c.key)),
    new Set(lecture.segments.map((s) => s.idx)),
  )
}

function writeFixture(depth: Partial<Record<string, ConceptDepth>>): void {
  const header = [
    "import type { ConceptDepth } from '@lectheo/contracts'",
    '',
    '/**',
    ' * "Explain in depth" for the CS50x library concepts (Product Spec F9.15), keyed by concept key.',
    ' * GENERATED by scripts/library-depth.ts on the dev key. It only adds data: stable ids, segments,',
    " * concepts and items don't change. Re-run the script with --force to regenerate.",
    ' */',
  ].join('\n')
  const body = `export const LIBRARY_DEPTH: Partial<Record<string, ConceptDepth>> = ${JSON.stringify(depth, null, 2)}`
  writeFileSync(FIXTURE, `${header}\n${body}\n`)
  execSync(`pnpm exec prettier --write "${FIXTURE}"`, { cwd: REPO_ROOT, stdio: 'inherit' })
}

async function main(): Promise<void> {
  const { values } = parseArgs({ options: { force: { type: 'boolean', default: false } } })
  assertDevGateway()
  const depth: Partial<Record<string, ConceptDepth>> = { ...LIBRARY_DEPTH }
  for (const lecture of LECTURES) {
    const keys = lecture.concepts.map((c) => c.key)
    if (!values.force && keys.every((k) => depth[k])) {
      out(`${lecture.key}: all ${keys.length} concepts have depth, skipped`)
      continue
    }
    const made = await depthFor(lecture, values.force)
    for (const k of keys) depth[k] = made.get(k)
    const dropped = keys.filter((k) => !made.has(k))
    const note = dropped.length > 0 ? ` (dropped: ${dropped.join(', ')})` : ''
    out(`${lecture.key}: ${made.size}/${keys.length} concepts${note}`)
  }
  writeFixture(depth)
  const ledger = readLedger().filter((e) => e.run === RUN)
  out(`Cost (dev key, ${ledger.length} calls): $${ledgerCost(ledger).toFixed(2)}`)
}

main().catch((error: unknown) => {
  process.stderr.write(
    `library-depth failed: ${error instanceof Error ? error.message : String(error)}\n`,
  )
  process.exitCode = 1
})
