/**
 * F11.6: chapters for the CS50x library lectures, generated once on the dev key and written to
 * packages/db/src/seed/fixtures/chapters.ts. It only adds data: segments, concepts, items and
 * stable ids don't change. Never touches a database; `pnpm db:seed` loads the fixture.
 *
 *   AI_FAKE=0 AI_GATEWAY_KEY_NAME=dev pnpm --filter @lectheo/scripts library-chapters [-- --force]
 *
 * Idempotent: lectures that already have chapters are skipped (--force regenerates them), and
 * each model output is cached under .cache/seed-library/, so a rerun never pays twice.
 */
import { execSync } from 'node:child_process'
import { rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parseArgs } from 'node:util'
import { extractConceptsTask, runTask, type ExtractConceptsOutput } from '@lectheo/ai'
import {
  clockToMs,
  LECTURES,
  LIBRARY_CHAPTERS,
  lectureId,
  type ChapterFx,
  type LectureFx,
  type LectureKey,
} from '@lectheo/db/seed'
import { chapterCountRange, chapterErrors } from '@lectheo/domain'
import {
  assertDevGateway,
  cachePath,
  cached,
  ledgerCost,
  readLedger,
  REPO_ROOT,
  scriptContext,
} from './lib/cache'

const RUN = 'library-chapters'
const BUDGET_USD = 5
const FIXTURE = join(REPO_ROOT, 'packages/db/src/seed/fixtures/chapters.ts')

const out = (line: string): void => {
  process.stdout.write(`${line}\n`)
}

const LIBRARY_KEYS = new Map(LECTURES.flatMap((l) => l.concepts.map((c) => [c.key, c.name])))

/** The pipeline's extraction call, asked for chapters only, with library concept keys. */
function chaptersTask(lecture: LectureFx, minutes: number) {
  const idxs = lecture.segments.map((s) => s.idx)
  return {
    ...extractConceptsTask,
    name: 'library-chapters',
    promptVersion: `${extractConceptsTask.promptVersion}+library-chapters.1`,
    buildPrompt: (input: Parameters<typeof extractConceptsTask.buildPrompt>[0]) => {
      const spec = extractConceptsTask.buildPrompt(input)
      const only = [
        'This run only needs chapters: return empty concepts and edges.',
        'In chapters, conceptKeys must be canonicalKeys from the existing course concepts list.',
      ].join('\n')
      return { ...spec, prompt: `${spec.prompt ?? ''}\n\n${only}` }
    },
    validate: (output: ExtractConceptsOutput) =>
      chapterErrors(
        output.chapters.map((c) => ({ ...c, concepts: c.conceptKeys })),
        idxs,
        minutes,
        (key: string) => LIBRARY_KEYS.has(key),
      ),
  }
}

async function chaptersFor(lecture: LectureFx, force: boolean): Promise<ChapterFx[]> {
  const minutes = (clockToMs(lecture.end) - clockToMs(lecture.start)) / 60_000
  const cacheName = `chapters-${lecture.key}.json`
  // --force regenerates: drop the cached model output too, or `cached` would return it.
  if (force) rmSync(cachePath(cacheName), { force: true })
  const output = await cached<ExtractConceptsOutput>(cacheName, async () => {
    const { output } = await runTask(
      chaptersTask(lecture, minutes),
      {
        lectureTitle: lecture.title,
        segments: lecture.segments.map(({ idx, text }) => ({ idx, text })),
        existingConcepts: [...LIBRARY_KEYS].map(([canonicalKey, name]) => ({ canonicalKey, name })),
        targetCount: lecture.concepts.length,
        chapterCount: chapterCountRange(minutes),
      },
      scriptContext(RUN, BUDGET_USD, lectureId(lecture.key)),
    )
    return output
  })
  return output.chapters.map((c) => ({
    title: c.title.trim(),
    summary: c.summary.trim(),
    start: c.startIdx,
    concepts: [...new Set(c.conceptKeys)],
  }))
}

function writeFixture(chapters: Partial<Record<LectureKey, ChapterFx[]>>): void {
  const header = [
    "import type { LectureKey } from '../ids'",
    "import type { ChapterFx } from './types'",
    '',
    '/**',
    ' * Chapters for the CS50x library lectures (Product Spec F11.6), keyed by lecture.',
    ' * GENERATED by scripts/library-chapters.ts on the dev key. It only adds data: stable ids, segments',
    " * and items don't change. Re-run the script with --force to regenerate a lecture.",
    ' */',
  ].join('\n')
  const body = `export const LIBRARY_CHAPTERS: Partial<Record<LectureKey, ChapterFx[]>> = ${JSON.stringify(chapters, null, 2)}`
  writeFileSync(FIXTURE, `${header}\n${body}\n`)
  execSync(`pnpm exec prettier --write "${FIXTURE}"`, { cwd: REPO_ROOT, stdio: 'inherit' })
}

async function main(): Promise<void> {
  const { values } = parseArgs({ options: { force: { type: 'boolean', default: false } } })
  assertDevGateway()
  const chapters: Partial<Record<LectureKey, ChapterFx[]>> = { ...LIBRARY_CHAPTERS }
  for (const lecture of LECTURES) {
    if (chapters[lecture.key]?.length && !values.force) {
      out(`${lecture.key}: has ${chapters[lecture.key]?.length} chapters, skipped`)
      continue
    }
    const made = await chaptersFor(lecture, values.force)
    chapters[lecture.key] = made
    out(`${lecture.key}: ${made.length} chapters`)
  }
  writeFixture(chapters)
  const ledger = readLedger().filter((e) => e.run === RUN)
  out(`Cost (dev key, ${ledger.length} calls): $${ledgerCost(ledger).toFixed(2)}`)
}

main().catch((error: unknown) => {
  process.stderr.write(
    `library-chapters failed: ${error instanceof Error ? error.message : String(error)}\n`,
  )
  process.exitCode = 1
})
