import type { LectureKey } from '../ids'
import type { ChapterFx } from './types'

/**
 * Chapters for the CS50x library lectures (Product Spec F11.6), keyed by lecture.
 * GENERATED by scripts/library-chapters.ts on the dev key. It only adds data: stable ids, segments
 * and items don't change. Re-run the script with --force to regenerate a lecture.
 */
export const LIBRARY_CHAPTERS: Partial<Record<LectureKey, ChapterFx[]>> = {
  l3: [
    {
      title: 'Selection Sort Pseudocode',
      summary:
        'Selection sort is written in pseudocode and mapped onto the volunteers in an array, with a note on memory use.',
      start: 0,
      concepts: ['selection_sort', 'arrays'],
    },
    {
      title: 'Analyzing Selection Sort',
      summary: 'Counting comparisons gives n² steps, so selection sort is O(n²), Ω(n²) and Θ(n²).',
      start: 6,
      concepts: ['selection_sort', 'asymptotic_notation'],
    },
    {
      title: 'Bubble Sort and Analysis',
      summary:
        'Bubble sort pseudocode, its loop bounds, and its O(n²) running time, with an early-exit optimization giving Ω(n).',
      start: 13,
      concepts: ['bubble_sort', 'asymptotic_notation'],
    },
    {
      title: 'Sorting Visualizations',
      summary: 'An animation compares selection sort and bubble sort and shows why n² is slow.',
      start: 24,
      concepts: ['selection_sort', 'bubble_sort'],
    },
    {
      title: 'Introducing Recursion',
      summary:
        'Recursion is defined, tied to binary search, and explained through base cases and recursive cases.',
      start: 28,
      concepts: ['recursion', 'binary_search'],
    },
    {
      title: 'Recursive Mario Pyramid',
      summary:
        'A Mario pyramid is defined recursively and coded both iteratively and recursively, including the missing base case.',
      start: 36,
      concepts: ['recursion'],
    },
    {
      title: 'Recursion Questions and Memory',
      summary:
        'Q&A on scope, and a stack overflow with large heights hints at the memory cost of recursion.',
      start: 54,
      concepts: ['recursion', 'stack_and_heap'],
    },
    {
      title: 'Merge Sort Idea and Merging',
      summary: 'The merge sort pseudocode, its base case, and merging two sorted lists in n steps.',
      start: 56,
      concepts: ['merge_sort', 'recursion'],
    },
    {
      title: 'Merge Sort Walkthrough',
      summary: 'Merge sort is traced step by step on eight numbers.',
      start: 62,
      concepts: ['merge_sort'],
    },
    {
      title: 'Merge Sort Running Time',
      summary:
        'Log n levels of n work give O(n log n), at the cost of extra space, confirmed by a visualization.',
      start: 69,
      concepts: ['merge_sort', 'asymptotic_notation'],
    },
  ],
  l4: [
    {
      title: 'Copying Strings with malloc',
      summary:
        "Copy a string manually into malloc'd memory, fixing the null terminator and strlen-in-loop issues, then use strcpy.",
      start: 0,
      concepts: ['malloc_and_null', 'strings_as_char_pointers'],
    },
    {
      title: 'NULL and Error Checks',
      summary:
        'Explains NULL versus NUL, checking get_string and malloc for NULL, and guarding the empty string.',
      start: 10,
      concepts: ['malloc_and_null'],
    },
    {
      title: 'Memory Leaks and free',
      summary:
        'Unfreed malloc memory causes leaks; the rule is that whatever you malloc you must free.',
      start: 15,
      concepts: ['memory_leaks'],
    },
    {
      title: 'Valgrind Debugging',
      summary:
        'Use Valgrind on memory.c to find invalid writes and leaks, then fix them and check malloc for NULL.',
      start: 19,
      concepts: ['memory_leaks', 'malloc_and_null', 'arrays'],
    },
    {
      title: 'Garbage Values and Bad Pointers',
      summary:
        'Shows garbage values in an uninitialized array and the danger of dereferencing uninitialized pointers.',
      start: 34,
      concepts: ['pointers'],
    },
    {
      title: 'Binky Pointer Claymation',
      summary:
        "Stanford's Binky video shows allocating pointees, dereferencing, and pointer assignment.",
      start: 41,
      concepts: ['pointers'],
    },
    {
      title: "C's Power and Risks",
      summary:
        "Discusses C's control and performance versus memory mistakes, compared to modern languages, and previews later topics.",
      start: 47,
      concepts: [],
    },
    {
      title: 'Swapping Glasses Demo',
      summary: 'A volunteer swaps two drinks using a temporary glass, motivating a swap function.',
      start: 51,
      concepts: ['pass_by_reference'],
    },
    {
      title: 'Broken Swap and Scope',
      summary:
        'The swap function fails because arguments are passed by value and have different scope.',
      start: 55,
      concepts: ['pass_by_reference'],
    },
    {
      title: 'Stack and Heap Layout',
      summary:
        'Describes memory layout: machine code, globals, heap, and stack frames for function calls.',
      start: 60,
      concepts: ['stack_and_heap'],
    },
    {
      title: 'Swap by Reference',
      summary: 'Fixes swap by passing addresses of ints and dereferencing with the star operator.',
      start: 69,
      concepts: ['pass_by_reference', 'pointers'],
    },
  ],
  l5: [
    {
      title: 'Linked List Tradeoffs',
      summary:
        'Linked lists are O(n) for insert, search and delete, and arrays resize slowly, which motivates combining the two.',
      start: 0,
      concepts: ['linked_lists', 'arrays', 'binary_search', 'asymptotic_notation'],
    },
    {
      title: 'Binary Search Trees',
      summary:
        'Trees mash arrays and linked lists together, giving logarithmic search at the cost of extra memory.',
      start: 9,
      concepts: ['binary_search_trees', 'binary_search', 'pointers'],
    },
    {
      title: 'Recursive Tree Search',
      summary:
        'A recursive search function in C with a base case and left and right subtree calls.',
      start: 22,
      concepts: ['binary_search_trees', 'recursion'],
    },
    {
      title: 'Unbalanced Trees',
      summary: 'Inserting in a bad order turns a tree into a linked list; rebalancing avoids this.',
      start: 30,
      concepts: ['binary_search_trees', 'linked_lists', 'asymptotic_notation'],
    },
    {
      title: 'Hashing and Hash Functions',
      summary:
        'Constant time as the goal, and hashing as a mapping from an infinite domain to buckets, with a C hash function.',
      start: 35,
      concepts: ['hash_functions', 'asymptotic_notation', 'pass_by_reference'],
    },
    {
      title: 'Hash Tables and Collisions',
      summary:
        'An array of linked lists handles collisions, but search is still O(n) asymptotically.',
      start: 48,
      concepts: ['hash_tables', 'linked_lists', 'arrays', 'hash_functions'],
    },
    {
      title: 'Tries',
      summary: 'A trie is a tree of arrays giving constant-time lookup at a large memory cost.',
      start: 62,
      concepts: ['tries'],
    },
    {
      title: 'Real-World Data Structures',
      summary:
        'Why hash tables are preferred over tries, and a lead-in to real-world stacks and queues.',
      start: 73,
      concepts: ['hash_tables', 'tries'],
    },
  ],
}
