import type { ConceptDepth } from '@lectheo/contracts'

/**
 * "Explain in depth" for the CS50x library concepts (Product Spec F9.15), keyed by concept key.
 * GENERATED by scripts/library-depth.ts on the dev key. It only adds data: stable ids, segments,
 * concepts and items don't change. Re-run the script with --force to regenerate.
 */
export const LIBRARY_DEPTH: Partial<Record<string, ConceptDepth>> = {
  binary_search: {
    howItWorks: [
      {
        text: 'The algorithm first checks whether any doors are left; if none, it returns false. Otherwise it looks at the middle door and returns true if the number is there.',
        cites: [30],
      },
      {
        text: "If the number is less than the middle door's value, it searches the left half; if greater, it searches the right half. The lecture asks how to search a half and answers that you just use the same algorithm again.",
        cites: [31],
      },
      {
        text: "Those 'search the left/right half' lines are recursive calls. They do not loop forever because each call is handed a smaller problem, so eventually it bottoms out by finding the number or running out of doors.",
        cites: [32, 33],
      },
      {
        text: "In week 0 the same idea was written procedurally with lines that said 'go back to line 3'. Condensing those line pairs into 'search the left half' and 'search the right half' gives a recursive version, where you restart the same algorithm on a problem half as large.",
        cites: [34, 35],
      },
    ],
    example: {
      text: 'Searching 8 doors: check the middle door. If the target is smaller, repeat on the left 4 doors, then perhaps the left 2, then 1. If no doors remain, return false. Each call has fewer doors, so it must stop.',
      beyondLecture: true,
    },
    mistakes: [
      {
        mistake:
          'Thinking the recursive calls could loop forever because the function calls itself.',
        why: 'Each recursive call gets a smaller set of doors, and the check for no doors left stops the process.',
      },
      {
        mistake:
          'Believing the recursive version is a different algorithm from the week 0 loop version.',
        why: "It is the same logic; the 'go back to line 3' lines are just replaced by calls on the left or right half.",
      },
      {
        mistake: 'Forgetting the check that handles no doors left.',
        why: 'That is a base case; without it the search would have no way to end when the number is absent.',
      },
    ],
  },
  asymptotic_notation: {
    howItWorks: [
      {
        text: 'Big O describes an upper bound on running time. You keep only the dominant term for large n and wave away lower-order terms, so n²/2 − n/2 is on the order of n².',
        cites: [8, 9],
      },
      {
        text: 'Omega describes the lower bound, such as how an algorithm behaves when the data is already sorted. Selection sort has no check for sorted input, so its lower bound is also n².',
        cites: [10, 11, 12],
      },
      {
        text: 'When Big O and Omega are the same, you can say Theta. Selection sort is Θ(n²), and merge sort is Θ(n log n) because both of its bounds match. Bubble sort with early exit is O(n²) and Ω(n), so no Theta applies.',
        cites: [12, 23, 73],
      },
      {
        text: 'Constant-time steps like a comparison or a swap do not matter. What matters is how the loops multiply, as in nested loops giving about n² steps.',
        cites: [18, 19, 20],
      },
    ],
    example: {
      text: 'Bubble sort does (n−1)(n−1) = n² − 2n + 1 steps. For n = 1000, n² is 1,000,000 while 2n is only 2,000, so n² dominates and the algorithm is O(n²).',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Keeping lower-order terms like −n/2 in the Big O answer.',
        why: 'For large n the dominant term overwhelms the others, so Big O keeps only n².',
      },
      {
        mistake: 'Saying Theta applies whenever you know Big O.',
        why: 'Theta requires the upper and lower bounds to be the same, as with selection sort but not bubble sort with early exit.',
      },
      {
        mistake: 'Thinking Big O is always the typical running time.',
        why: "Big O is an upper bound; the lower bound (Omega) can be far smaller, such as bubble sort's Ω(n) on sorted input.",
      },
    ],
  },
  selection_sort: {
    howItWorks: [
      {
        text: 'For i from 0 to n−1, find the smallest number between numbers[i] and numbers[n−1], then swap it with numbers[i]. The first pass puts the smallest value in place, and then i advances so the next pass starts one later.',
        cites: [1, 2],
      },
      {
        text: 'While scanning, it remembers only the smallest value so far in a single variable. An array is a fixed block of memory, so you swap values instead of claiming space elsewhere. Using little memory is a trade-off against time.',
        cites: [3, 4, 5, 6],
      },
      {
        text: 'The comparisons are (n−1)+(n−2)+…+1, which equals n(n−1)/2, or n²/2 − n/2. Dropping lower-order terms gives O(n²).',
        cites: [7, 8, 9],
      },
      {
        text: 'The code never checks whether the list is already sorted, so it does the same work even then. Its best case is Ω(n²) as well, which makes it Θ(n²).',
        cites: [10, 11, 12],
      },
    ],
    example: {
      text: 'Take [7,2,1,0]. Pass i=0: smallest is 0, swap with 7 giving [0,2,1,7]. Pass i=1: smallest of [2,1,7] is 1, swap with 2 giving [0,1,2,7]. Pass i=2: smallest of [2,7] is 2, already in place. Done.',
      beyondLecture: true,
    },
    mistakes: [
      {
        mistake: 'Assuming selection sort finishes quickly on an already sorted list.',
        why: 'It has no check for sortedness and still scans every time, so its best case is still n².',
      },
      {
        mistake: 'Thinking the smallest element is inserted by shifting everything over.',
        why: 'It is swapped with the element at location i.',
      },
      {
        mistake: 'Thinking the inner search looks at the whole array every pass.',
        why: 'It searches from i to n−1, so the range shrinks and the total is n(n−1)/2.',
      },
    ],
  },
  bubble_sort: {
    howItWorks: [
      {
        text: 'Repeat n−1 times: for i from 0 to n−2, if numbers[i] and numbers[i+1] are out of order, swap them. It is like a left hand and right hand moving along adjacent pairs.',
        cites: [13, 14, 17],
      },
      {
        text: 'The inner loop stops at n−2 because the code looks at i+1. If i were n−1, the right hand would point at n, which is past the end of the array.',
        cites: [15],
      },
      {
        text: 'The biggest element bubbles to the end first, then the next biggest, and so on. The outer loop runs n−1 times because the last element is free once the others are placed.',
        cites: [16, 17],
      },
      {
        text: 'Two nested loops of about n−1 steps each give n² − 2n + 1, so it is O(n²). Quitting after a pass with no swaps gives a best case of Ω(n), but the average and worst cases remain n².',
        cites: [18, 19, 20, 21, 22, 23],
      },
    ],
    example: {
      text: 'Take [3,1,2]. Pass 1: compare 3,1 and swap giving [1,3,2]; compare 3,2 and swap giving [1,2,3]. Pass 2: no swaps happen, so with the early exit it stops. Pass 2 is the single extra pass that makes the best case linear.',
      beyondLecture: true,
    },
    mistakes: [
      {
        mistake: 'Looping i up to n−1 in the inner loop.',
        why: 'Then i+1 equals n, which is outside the array.',
      },
      {
        mistake: 'Believing the early exit improves the worst case.',
        why: 'It helps only when the list is already or mostly sorted; average and worst cases stay O(n²).',
      },
      {
        mistake: 'Saying the lower bound of bubble sort is n² without the modification.',
        why: 'Without the early exit, it still does all the comparisons; Ω(n) only holds with the no-swap check.',
      },
    ],
  },
  recursion: {
    howItWorks: [
      {
        text: 'A recursive function is defined in terms of itself, meaning the function calls itself. This seems like a recipe for an infinite loop, so two things are required.',
        cites: [29, 30],
      },
      {
        text: 'Each recursive call must be given a smaller problem, and a base case must give an immediate answer without recursing. The base case ends the chain of calls.',
        cites: [32, 33, 34],
      },
      {
        text: 'A pyramid of height n is a pyramid of height n−1 plus one more row, and the smallest pyramid is the base case. In code, draw(n) calls draw(n−1) and then prints one row with a single loop.',
        cites: [36, 37, 38, 47, 48, 49],
      },
      {
        text: "Without a base case, clang reports that all paths call the function itself. Adding 'if n <= 0 return' fixes it, and the lecture used <= 0 to also handle negative input.",
        cites: [50, 51, 52],
      },
    ],
    example: {
      text: 'Recursive pyramid from the lecture: draw(n) returns if n <= 0, otherwise calls draw(n-1) and then prints n hashes and a newline. For n=3, draw(3) calls draw(2), which calls draw(1), which calls draw(0) and returns. Then rows of 1, 2 and 3 hashes print in that order.',
      code: 'void draw(int n)\n{\n    if (n <= 0)\n        return;\n    draw(n - 1);\n    for (int i = 0; i < n; i++)\n        printf("#");\n    printf("\\n");\n}',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Thinking a function that calls itself always loops forever.',
        why: 'With a base case and a smaller problem each time, the calls terminate.',
      },
      {
        mistake: 'Omitting the base case because the problem shrinks anyway.',
        why: 'Without it nothing tells the function to stop, and clang flags that all paths call itself.',
      },
      {
        mistake: 'Assuming recursion costs no more than a loop.',
        why: 'Each call uses extra memory, so very large inputs can crash.',
      },
    ],
  },
  merge_sort: {
    howItWorks: [
      {
        text: 'Merge sort is: sort the left half, sort the right half, merge the sorted halves. A base case says that a list of one element is already sorted.',
        cites: [57, 58],
      },
      {
        text: 'Merging uses two pointers, one per sorted half. At each step you take the smaller of the two pointed-at values and advance only that pointer, so the hands only move rightward. Every element is placed once, so merging n elements takes n steps.',
        cites: [59, 60, 61],
      },
      {
        text: 'Tracing 8 numbers, the left half is sorted recursively down to single elements and merged back up, then the right half, then the final merge. There are only about 3 levels, not n levels.',
        cites: [62, 63, 64, 65, 66, 67, 68],
      },
      {
        text: 'With n = 8 there are log₂8 = 3 levels, and each level does n steps of merging, so it is O(n log n). There is no early-exit shortcut, so it is also Ω(n log n) and therefore Θ(n log n). The cost is needing about twice as much space.',
        cites: [69, 70, 71, 72, 73],
      },
    ],
    example: {
      text: 'Merge the sorted halves [1,3,4,6] and [0,2,5,7]. Compare 1 and 0, take 0. Compare 1 and 2, take 1. Compare 3 and 2, take 2, then 3, then 4, then 5, then 6, and finally 7. The result is [0,1,2,3,4,5,6,7] after 8 placements.',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Thinking merging requires going back and forth over the lists repeatedly.',
        why: 'The two pointers only move right, and each element is placed once, so merging is n steps.',
      },
      {
        mistake: 'Believing merge sort is faster at no cost.',
        why: 'It needs about twice as much space, as when two shelves were needed to merge.',
      },
      {
        mistake: 'Thinking merge sort has a faster best case on sorted input.',
        why: 'It has no early-exit optimization, so it is Ω(n log n) and Θ(n log n).',
      },
    ],
  },
  strings_as_char_pointers: {
    howItWorks: [
      {
        text: 'To copy a string, you first need a new chunk of memory. The lecture asks malloc for strlen(s) + 1 bytes. The extra byte is for the null terminator, because the real-world length of "hi!" is 3 but 4 bytes are needed underneath.',
        cites: [0, 1],
      },
      {
        text: "Then you copy the characters yourself, one by one, from s into t. A loop that stops at i < strlen(s) forgets the null character. The fix is to go up to and through the length, using <=, so it runs 4 times for a length of 3. Hard-coding t[4] = '\\0' is called sloppy.",
        cites: [2, 4, 5],
      },
      {
        text: 'Calling strlen on every iteration is wasteful. The trick is to store the length once in a variable n, then compare i against n after the semicolon so the function is not called repeatedly.',
        cites: [5, 6],
      },
      {
        text: 'Because t gets its own chunk from malloc, capitalizing t leaves s unchanged. The lecture shows s still lowercase and t capitalized. strcpy(destination, source) can replace the whole loop, as long as enough memory was allocated. The destination comes first.',
        cites: [7, 8, 9],
      },
    ],
    example: {
      text: "Copy \"hi!\" (length 3). Allocate 3 + 1 = 4 bytes. The loop with i <= n copies 'h', 'i', '!' and then '\\0', so t is a complete string. Equivalent: strcpy(t, s).",
      code: 'char *t = malloc(strlen(s) + 1);\nint n = strlen(s);\nfor (int i = 0; i <= n; i++)\n{\n    t[i] = s[i];\n}',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Allocating only strlen(s) bytes for the copy.',
        why: "strlen does not count the null terminator, so you need one extra byte for '\\0'.",
      },
      {
        mistake: 'Looping with i < strlen(s) and assuming the copy is complete.',
        why: 'That skips the null character, so t is not properly terminated.',
      },
      {
        mistake: 'Writing strcpy(s, t) to copy s into t.',
        why: 'The destination comes first and the source second, so the arguments would be reversed.',
      },
    ],
  },
  malloc_and_null: {
    howItWorks: [
      {
        text: 'malloc takes a number of bytes, asks the operating system for that much memory, and returns the address of the first byte. It needs stdlib.h. To request space for 3 ints, use 3 * sizeof(int) rather than a hard-coded 12, which is less portable if an int is not 4 bytes.',
        cites: [0, 1, 20, 21],
      },
      {
        text: 'NULL is the special address 0x0, where nothing is supposed to live. It is different from NUL, the single byte of eight zero bits that ends a string. Functions use NULL as a sentinel for errors.',
        cites: [10, 11],
      },
      {
        text: 'get_string and malloc can return NULL, for example when memory runs out. The program should check for NULL and return 1 instead of continuing. Otherwise it might touch the null address.',
        cites: [12, 13, 32],
      },
      {
        text: "Bracket notation on malloc'd memory is syntactic sugar for pointer arithmetic, so x[1] is the same as *(x + 1). The lecture also checks that strlen(s) > 0 before capitalizing t[0], since an empty string has only the terminator at that position.",
        cites: [14, 30, 31],
      },
    ],
    example: {
      text: 'Allocate space for 3 ints and check the result before using it. If malloc fails, return 1. Otherwise fill indexes 0 to 2.',
      code: 'int *x = malloc(3 * sizeof(int));\nif (x == NULL)\n{\n    return 1;\n}\nx[0] = 72;\nx[1] = 73;\nx[2] = 33;',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Treating NULL and NUL as the same thing.',
        why: "NUL is the one-byte '\\0' terminator of a string, while NULL is the address 0x0.",
      },
      {
        mistake: 'Hard-coding 12 for three ints.',
        why: 'An int may not be 4 bytes on every system, so sizeof(int) is more portable.',
      },
      {
        mistake: 'Using the memory from malloc without checking for NULL.',
        why: 'If malloc failed, you would be touching address 0x0, so you should check and return 1.',
      },
    ],
  },
  memory_leaks: {
    howItWorks: [
      {
        text: 'Memory obtained with malloc must be given back with free. If it is not, the program has a memory leak. In a long-running program such as a server, this makes the computer slower and slower because it thinks all memory is in use.',
        cites: [15, 16, 17],
      },
      {
        text: "The rule of thumb is that if you malloc'd it, you must free it. CS50's get_string frees its own memory automatically, so you do not free s.",
        cites: [18, 19],
      },
      {
        text: 'Valgrind is a tool for finding memory errors. Running it on the example, it reports an invalid write of size 4 tied to line 11, because the index is off and touches memory that should not be touched.',
        cites: [19, 24, 25, 26],
      },
      {
        text: 'Its leak summary reports 12 bytes definitely lost, which is 3 ints of 4 bytes each. It also points to line 8 where the memory was allocated. After the fix, indexes become 0 to 2 and the program calls free(x). Valgrind then reports all heap blocks freed and zero errors.',
        cites: [27, 28, 29, 33],
      },
    ],
    example: {
      text: 'The corrected program from the lecture: use indexes 0 to 2 and free x at the end. Valgrind then shows no leaks and no invalid writes.',
      code: 'int *x = malloc(3 * sizeof(int));\nx[0] = 72;\nx[1] = 73;\nx[2] = 33;\nfree(x);',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Thinking a program with no visible crash has no memory bugs.',
        why: "The lecture's program ran fine but had a bad index and a leak, which are latent bugs that Valgrind finds.",
      },
      {
        mistake: 'Calling free on the string returned by get_string.',
        why: "CS50's get_string frees that memory automatically, and you free only what you malloc'd.",
      },
      {
        mistake: 'Believing a leak only matters if the program crashes.',
        why: 'A leak shows up as a program that gets slower over time.',
      },
    ],
  },
  pointers: {
    howItWorks: [
      {
        text: 'A pointer variable stores the address of a value. Declaring int *x, *y creates the pointers but does not create anything for them to point to. The things they point to are called pointees, and setting them up is a separate step.',
        cites: [38, 42],
      },
      {
        text: 'Dereferencing with * means go to that address. After x = malloc(sizeof(int)), *x = 42 stores 42 in the pointee. This is valid because x points to real memory.',
        cites: [39, 43],
      },
      {
        text: 'An uninitialized pointer holds a garbage value, just like uninitialized memory contains leftovers from earlier use, as the garbage-values program showed. Dereferencing y with *y = 13 goes to a bogus address and bad things happen.',
        cites: [35, 36, 37, 40, 44],
      },
      {
        text: 'The fix is pointer assignment, y = x, which makes both pointers share one pointee without copying data. Then *y = 13 changes the 42 to 13 for both. C gives fast, powerful control over memory but makes such mistakes easy.',
        cites: [45, 46, 47],
      },
    ],
    example: {
      text: "The lecture's Binky example: allocate x, store 42, point y at the same place, then store 13 through y. Both see 13.",
      code: 'int *x;\nint *y;\nx = malloc(sizeof(int));\n*x = 42;\ny = x;\n*y = 13;',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Thinking int *y creates an integer for y to point to.',
        why: 'It only creates the pointer, and the pointee must be set up separately.',
      },
      {
        mistake: 'Thinking y = x copies the value 42 into new memory.',
        why: 'It only makes y point to the same location, so both share one pointee.',
      },
      {
        mistake:
          'Assuming an uninitialized pointer is safe to dereference, for example because it is 0.',
        why: 'It holds a garbage value, so you do not know where it points and dereferencing it is dangerous.',
      },
    ],
  },
  pass_by_reference: {
    howItWorks: [
      {
        text: 'Swapping two values needs a temporary variable, like the empty glass in the demo. In code, swap puts a in temp, b in a, and temp in b. This works inside swap itself.',
        cites: [53, 54, 55, 57],
      },
      {
        text: 'But the program still prints x and y unswapped. C passes arguments by value, so a and b are copies of x and y. They live in different scope, in a different frame of memory, so swapping the copies does not change the originals.',
        cites: [58, 59, 60, 67, 68, 69],
      },
      {
        text: 'The fix is to pass by reference: declare swap(int *a, int *b) and pass the addresses of x and y. Then a and b act as a treasure map to the originals.',
        cites: [69, 70],
      },
      {
        text: 'Inside swap, int tmp = *a; *a = *b; *b = tmp; goes to those addresses and changes the original variables. The * symbol is overloaded in C: multiplication, declaring a pointer, and dereferencing.',
        cites: [71, 72, 73],
      },
    ],
    example: {
      text: 'Trace with x = 1, y = 2. Call swap(&x, &y), so a points to x and b points to y. tmp = *a gives 1. *a = *b puts 2 in x. *b = tmp puts 1 in y. Now x is 2 and y is 1.',
      code: 'void swap(int *a, int *b)\n{\n    int tmp = *a;\n    *a = *b;\n    *b = tmp;\n}\n// in main: swap(&x, &y);',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Thinking the by-value swap fails because the logic is wrong.',
        why: 'The logic is right but it swaps copies, and x and y are unchanged because of scope.',
      },
      {
        mistake: 'Believing the * always means the same thing.',
        why: 'It means multiplication, pointer declaration, or dereference depending on context.',
      },
      {
        mistake: 'Thinking a function can swap originals when handed only copies.',
        why: 'Without their addresses the function has no way to reach the original variables.',
      },
    ],
  },
  stack_and_heap: {
    howItWorks: [
      {
        text: "When a program runs, its machine code is copied from persistent storage into RAM at one edge of memory. Global variables, defined outside main, sit right below it by convention. Top and bottom are only an artist's picture.",
        cites: [61, 62],
      },
      {
        text: 'Below that is the heap, which malloc uses to hand out chunks back to back. The heap grows downward in the diagram.',
        cites: [63],
      },
      {
        text: 'The stack is used for local variables and function calls, and it grows upward like stacked cafeteria trays. main gets a frame first. When it calls swap, swap gets the next frame above it, holding its arguments and locals.',
        cites: [64, 65, 66],
      },
      {
        text: 'When a function returns, its frame is conceptually freed, though the zeros and ones remain. The memory can be reused later, which is why garbage values appear as remnants of earlier calls.',
        cites: [65, 66, 74],
      },
    ],
    example: {
      text: "In the swap program, main's frame holds x = 1 and y = 2. Calling swap adds a frame above it holding a, b and temp. When swap returns, that frame goes away, but main's frame stays with its values.",
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Thinking the heap and stack are two names for the same area.',
        why: 'malloc uses the heap, while local variables and function calls use the stack.',
      },
      {
        mistake: "Thinking a returned function's memory is erased.",
        why: 'The bytes remain but can be reused, which leaves garbage values.',
      },
      {
        mistake: 'Treating top and bottom as real physical positions.',
        why: "The lecture says the diagram is an artist's rendition and there is no real up or down.",
      },
    ],
  },
  arrays: {
    howItWorks: [
      {
        text: 'Arrays are stored back to back, contiguous in memory. Because of this, simple arithmetic finds the length, the middle, and the middle of the middle. That is what makes binary search, and so O(log n) lookup, possible.',
        cites: [2, 3],
      },
      {
        text: 'The downside is that you must decide in advance how big the array is. If you guess too small, you have to ask for more memory with malloc or realloc. That is solvable, but it costs time.',
        cites: [3],
      },
      {
        text: 'Growing means copying all the old values into the new memory, whether you use a for loop or realloc does it for you. With 3 or 4 values this is trivial, but with 3 million values it wastes a huge amount of time. This cost motivated linked lists.',
        cites: [4, 12],
      },
    ],
    example: {
      text: 'An array of 7 numbers is full, and you want to add 8. If the memory after it is free you might get lucky. Otherwise you allocate a bigger block, copy all 7 old values over, and then place the 8. With 3 million values the copy step dominates.',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Thinking arrays can simply grow in place whenever you need more room.',
        why: 'Memory after the array may be in use, so you may have to allocate a new block and copy everything, which is slow for large data.',
      },
      {
        mistake: 'Believing binary search works on an array because it is sorted alone.',
        why: 'It also relies on contiguous storage, which lets you jump straight to the middle with arithmetic.',
      },
    ],
  },
  linked_lists: {
    howItWorks: [
      {
        text: 'A linked list allocates one node per value and stitches the nodes together with pointers. It only allocates memory as needed, so it avoids over- or underestimating the size. It can also use fragmented memory, a few bytes here and there.',
        cites: [1, 4],
      },
      {
        text: 'Once allocated, nodes stay where they are and you just update pointers, so nothing is copied. The cost is that search, insert and delete in the sorted version were all O(n). You must walk from the start to find the right place.',
        cites: [0, 5],
      },
      {
        text: 'Binary search is lost. To find the middle you must traverse from the beginning to learn the length and then walk halfway, and you repeat this for every middle after that. Keeping pointers to many middles would devolve into an array.',
        cites: [6, 7],
      },
      {
        text: "A doubly linked list has arrows in both directions. This simplifies code, since you don't need to look ahead to free or insert, but it does not fundamentally change the speed.",
        cites: [8],
      },
    ],
    example: {
      text: 'A sorted list holds 1, 2, 3, 4 and you search for 4. Starting at the list pointer you follow four next pointers before finding it. Finding the middle first would also require walking the whole list, so there is no binary search shortcut.',
      beyondLecture: true,
    },
    mistakes: [
      {
        mistake: 'Thinking a sorted linked list can use binary search.',
        why: 'You cannot jump to the middle. Finding it takes O(n) traversal each time.',
      },
      {
        mistake: 'Thinking a doubly linked list makes operations faster than O(n).',
        why: 'The lecture says it only makes the code easier to write, not fundamentally faster.',
      },
      {
        mistake: 'Thinking linked lists beat arrays on every measure.',
        why: 'They gain dynamism but cost extra space and lose binary search speed.',
      },
    ],
  },
  binary_search_trees: {
    howItWorks: [
      {
        text: 'A binary search tree stores the same values as a sorted array, but in two dimensions. The middle value is the root, and the middles of the halves become its left and right children. Each node holds a number and two pointers, left and right.',
        cites: [11, 13, 14],
      },
      {
        text: 'The key property is that every node is greater than its left child and less than its right child. This property is recursive, since it holds at every node and is trivially not violated at the leaves. So searching for 5 at a root of 4 lets you snip off the left subtree and go right.',
        cites: [15, 16, 17, 18],
      },
      {
        text: "Search is recursive too. If the tree is null, return false. If the number is less than the node's, search the left child, and if greater, search the right child. Otherwise it equals the node, so return true. The height is about log2 n, so search, insert and delete are O(log n), and inserting only updates pointers.",
        cites: [19, 20, 24, 25, 26, 28],
      },
      {
        text: 'The costs are memory, roughly three times as much per value, and balance. If values arrive in sorted order, such as 1, 2, 3, 4, the tree becomes a long stringy linked list and operations are O(n) again. More advanced trees rebalance on insert or delete to keep the height logarithmic.',
        cites: [21, 23, 31, 32, 33, 34],
      },
    ],
    example: {
      text: 'Insert 2, then 1, then 3. The 2 is the root, 1 goes left and 3 goes right, so the tree is balanced. Now insert 1, 2, 3 in that order. Each new value goes to the right of the last, giving a chain and O(n) search.',
      code: 'bool search(int number, node *tree)\n{\n    if (tree == NULL)\n    {\n        return false;\n    }\n    else if (number < tree->number)\n    {\n        return search(number, tree->left);\n    }\n    else if (number > tree->number)\n    {\n        return search(number, tree->right);\n    }\n    else\n    {\n        return true;\n    }\n}',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Assuming a binary search tree always gives O(log n).',
        why: 'If inserts arrive in sorted order, the tree becomes a linked list with O(n) operations unless it is rebalanced.',
      },
      {
        mistake:
          "Thinking each node must be greater than all its descendants' left side only locally, ignoring the recursion.",
        why: 'The property applies at every node, which is why you can discard a whole subtree with one comparison.',
      },
      {
        mistake: 'Thinking a tree uses the same memory as an array.',
        why: 'Each node has an int plus two pointers, roughly three times as much.',
      },
    ],
  },
  hash_functions: {
    howItWorks: [
      {
        text: 'Hashing maps an infinite domain of inputs to a finite range of outputs. Domain is the input and range is the output. Sorting 52 playing cards into 4 suit buckets is an analogy, turning one big problem into smaller ones.',
        cites: [37, 38, 39],
      },
      {
        text: 'A hash function decides which bucket an input goes to. For names, a simple one uses the first letter, so A maps to bucket 0 and Z to 25. Mario maps to 12 and Luigi to 11, since buckets are indexed from 0.',
        cites: [40, 42, 43],
      },
      {
        text: "In C, the function uppercases the first letter with toupper and subtracts 'A'. It does no error checking, so non-English symbols would break it. Refinements include making the parameter const so the function cannot change the caller's string, and returning an unsigned int so the result is never negative.",
        cites: [44, 45, 46, 47],
      },
      {
        text: 'Mapping an infinite domain onto a finite range means collisions are inevitable. Hashing on more letters, such as the first three, reduces collisions but needs far more buckets and wastes memory. A good hash function balances these.',
        cites: [53, 58, 59, 60, 61],
      },
    ],
    example: {
      text: "For Mario, toupper('M') is 77 and subtracting 65 gives 12. For Luigi, 'L' is 76, giving 11. Both names starting with M, such as Mario and another M name, both give 12, which is a collision.",
      code: "unsigned int hash(const char *name)\n{\n    return toupper(name[0]) - 'A';\n}",
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake:
          'Thinking a hash function can avoid collisions entirely when the domain is larger than the range.',
        why: 'Mapping infinite or many inputs to finite buckets guarantees some collisions.',
      },
      {
        mistake: 'Thinking using more letters is free.',
        why: 'Hashing on three letters needs far more buckets, and many of them (like AAA) are never used, wasting memory.',
      },
      {
        mistake: 'Forgetting that the bucket index starts at 0.',
        why: 'M is the 13th letter, but its index is 12.',
      },
    ],
  },
  hash_tables: {
    howItWorks: [
      {
        text: 'A hash table associates keys with values and is often how dictionaries are implemented at a lower level. A phone book of names and numbers, or an English dictionary of words and definitions, are key-value collections.',
        cites: [48, 49],
      },
      {
        text: 'It is an array mashed together with linked lists. For example, an array of 26 node pointers, one per letter, where each node holds a name and a next pointer. To insert, you hash the name to find the array location and create a new node there.',
        cites: [49, 50, 51, 52],
      },
      {
        text: 'If two names hash to the same bucket, that is a collision. Overwriting or filling neighbouring slots makes a mess that devolves into something linear. Instead you chain the colliding names in a linked list at that bucket.',
        cites: [53, 54, 55],
      },
      {
        text: 'With k buckets and uniformly distributed names, each chain has about n/k entries. That is much faster, such as 26 times, than one linked list. But asymptotically n/k is still O(n), because k is a constant.',
        cites: [56, 57, 61, 62],
      },
    ],
    example: {
      text: 'With the first-letter hash, Mario hashes to 12 and gets a node at bucket 12. If another M name arrives, it is chained onto the same list. Searching for it means going to bucket 12 and walking that short chain instead of the whole data set.',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: "Saying a hash table with chaining is O(1) in this lecture's design.",
        why: 'With collisions, chains hold about n/k items, which is still O(n) asymptotically.',
      },
      {
        mistake: 'Handling a collision by overwriting the existing entry.',
        why: 'That would delete data. Chaining keeps both in a linked list.',
      },
      {
        mistake: 'Saying a hash table is no better than a linked list.',
        why: 'It is roughly k times faster in practice because the chains are shorter.',
      },
    ],
  },
  tries: {
    howItWorks: [
      {
        text: 'A trie, short for retrieval, is a tree made out of arrays. Each node is an array of 26 pointers indexed A to Z, and each pointer leads to another such node. It gives constant-time lookup at the cost of lots of space.',
        cites: [62, 63, 64],
      },
      {
        text: 'Names are stored implicitly as a path of non-null pointers, one per letter, rather than as a string. To insert toad you follow or create nodes for T, O, A, D. A boolean, drawn in green, marks that a name ends at that node.',
        cites: [64, 65, 66],
      },
      {
        text: 'Names that share prefixes reuse nodes, so toad, toadette and tom all share the T and O nodes. Instead of a boolean, the node can point to a person structure to store key-value pairs such as phone numbers.',
        cites: [66, 67, 71, 72],
      },
      {
        text: 'To look up toad you follow one pointer per letter, four steps, no matter whether the trie holds 3 or 3 million names. Names have some finite maximum length, so this is effectively constant time. The trade-off is memory, since most of the pointers in each array are null and wasted.',
        cites: [68, 69, 70, 73, 74, 75],
      },
    ],
    example: {
      text: 'Insert toad. Change the T pointer at the root from null to a new node, then the O pointer in that node, then the A pointer, then the D pointer, and mark the final node with a true boolean. To look up toad you follow T, O, A, D and see the flag is true, so it is present. If you stop at TOA and the flag is false there, then toa is not stored.',
      beyondLecture: false,
    },
    mistakes: [
      {
        mistake: 'Thinking the trie stores the string toad explicitly.',
        why: 'The word is implicit in the path of non-null pointers, with a boolean marking where it ends.',
      },
      {
        mistake: 'Thinking lookup time depends on the number of names stored.',
        why: 'It depends only on the length of the name, which is bounded, so it is effectively constant.',
      },
      {
        mistake: 'Thinking tries are the best choice because they are O(1).',
        why: 'They use a huge amount of memory with mostly null pointers, which is why hash tables are used more in practice.',
      },
    ],
  },
}
