import type { ItemFx } from './types'

/**
 * Verified practice bank for Lecture 3: Algorithms (F7.3).
 * GENERATED by scripts/seed-library.ts (Opus 5.5 extraction/drafting, GPT-6.1 Sol blind
 * verification). Do not edit by hand: change the script and re-run it.
 */
export const lecture3Items: ItemFx[] = [
  {
    concept: 'binary_search',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [30, 31, 32, 33],
    publicPayload: {
      stem: "A search algorithm checks the middle door of a sorted row of lockers. If the target is smaller, it says 'search the left half'; if larger, 'search the right half'. Even though the algorithm calls itself, why doesn't it run forever?",
      options: [
        {
          id: 'a',
          text: 'The compiler automatically limits how many times a function may call itself.',
        },
        {
          id: 'b',
          text: 'The middle door is always checked twice, which guarantees the number is found.',
        },
        {
          id: 'c',
          text: 'Each call is handed a smaller problem, about half as many doors, so it eventually reaches a case that answers immediately.',
        },
        {
          id: 'd',
          text: 'Recursive calls run in parallel, so all halves are searched at once and finish together.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        'Each recursive call searches only half of the remaining doors. Because the problem keeps shrinking, the search eventually bottoms out. Either the number is found or no doors are left, and those base cases answer right away.',
    },
    distractorMeta: {
      a: {
        misconception:
          'Termination comes from the compiler or system rather than from how the algorithm is designed.',
        whyWrong:
          'The algorithm stops because its problem shrinks toward a base case. No compiler-imposed call limit is involved.',
      },
      b: {
        misconception: 'Rechecking the middle door ensures success.',
        whyWrong:
          'The number may not be present at all. The search still ends because the doors run out, not because the middle is rechecked.',
      },
      d: {
        misconception: 'Recursion means running every subproblem at the same time.',
        whyWrong:
          'Only one half is searched at each step, and the calls happen one after another on smaller and smaller pieces.',
      },
    },
    rubric: null,
    hints: [
      'Think about what changes between one call and the next.',
      'Compare the number of doors passed into each call with the number in the original problem.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'binary_search',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [30, 31, 32, 33],
    publicPayload: {
      stem: 'The locker-search algorithm opens the middle door, and if the number we want is less than the number behind that door, it searches only the left half and never looks at the right half again. What must be true of the numbers behind the doors for skipping the right half to be safe?',
      options: [
        {
          id: 'a',
          text: 'The total number of doors must be a power of 2, so that each half splits evenly.',
        },
        {
          id: 'b',
          text: 'The number being searched for must actually be behind one of the doors.',
        },
        {
          id: 'c',
          text: 'The numbers must be in sorted order, so every number to the right of the middle is at least as large as the middle one and cannot be the smaller target.',
        },
        {
          id: 'd',
          text: 'The numbers must all be different from one another, so the middle door is unique.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        'The algorithm compares the target with the middle door and then discards a whole half. That only works if the doors are sorted. When they are, a target smaller than the middle number cannot be anywhere to its right, because every number there is at least as large as the middle one. If the doors were unsorted, the target could sit in the discarded half and the search would wrongly report that it is not there.',
    },
    distractorMeta: {
      a: {
        misconception: 'Thinks halving requires an exact even split to be correct.',
        whyWrong:
          'Uneven halves are fine. The middle just ends up slightly off-center, and discarding a half is still safe as long as the numbers are sorted.',
      },
      b: {
        misconception:
          'Confuses a precondition for correctness with the outcome the algorithm reports.',
        whyWrong:
          'The algorithm handles a missing number on its own: when no doors are left, it returns false. Whether the target is present has nothing to do with why the right half can be skipped.',
      },
      d: {
        misconception: 'Believes duplicate values break the left/right decision.',
        whyWrong:
          'With duplicates in sorted order, everything to the right of the middle is still at least as large as the middle value, so skipping it remains safe. Sortedness, not uniqueness, is what matters.',
      },
    },
    rubric: null,
    hints: [
      'Ask yourself what the algorithm learns about the unopened doors from a single comparison with the middle door.',
      'Picture doors whose numbers are scrambled. Could the number you want be hiding in the half you threw away?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'binary_search',
    kind: 'spot_flaw',
    variant: 1,
    segs: [30, 32, 33],
    publicPayload: {
      sentences: [
        'The locker search first checks whether any doors are left, and if none are, it returns false.',
        'If the number is behind the middle door, it returns true right away.',
        'Otherwise it searches either the left half or the right half, and those lines are recursive calls to the same algorithm.',
        "Because a function that calls itself always stops eventually, the size of the problem passed to each call doesn't really matter.",
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        'The claim that recursion stops no matter what is passed to each call is wrong. Termination depends on handing each call a smaller problem.',
      correction:
        'The recursion terminates only because each call receives a smaller problem, half the doors, so it eventually reaches a base case. Passing the same number of doors each time would never make progress.',
      explanation:
        'A self-calling function can easily recurse forever. The search ends because each call works on fewer doors until a base case, such as no doors left or the number found, answers immediately.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the error',
          description: 'Points out that recursion does not automatically terminate.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct reasoning',
          description:
            'Explains that each call must receive a smaller problem so it eventually reaches a base case.',
          max: 2,
        },
      ],
    },
    hints: [
      'Is it true that every self-calling function eventually stops?',
      'Think about what would happen if each call were handed the exact same set of doors.',
    ],
    leakKeywords: ['smaller problem', 'infinite', 'always stops', 'half as many'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'binary_search',
    kind: 'spot_flaw',
    variant: 2,
    segs: [31, 33, 35, 71, 72],
    publicPayload: {
      sentences: [
        'The locker search compares the target with the number behind the middle door; if the target is smaller it searches only the left half, and if it is larger it searches only the right half.',
        'That decision only makes sense if the numbers behind the doors are in sorted order, because otherwise the target could be hiding in the half that was just discarded.',
        'Each recursive call hands the algorithm a problem half as large as before, so 8 doors become 4, then 2, then 1.',
        'The number of times you can halve n doors before reaching a single door is log base 2 of n, which is 3 for 8 doors, so the work grows on the order of log n rather than n.',
      ],
    },
    answerKey: {
      hasFlaw: false,
      flawSentenceIdx: null,
      flawSummary: null,
      correction: null,
      explanation:
        'Every sentence is correct. The algorithm compares the target to the middle door and recurses on only the left or right half. Discarding a half is valid only when the doors are sorted, since the comparison then shows which side could hold the target. Each recursive call works on a problem half as large. Repeatedly halving n reaches 1 after about log base 2 of n steps (8 to 4 to 2 to 1 is 3 halvings, and log2 8 = 3). That is why the search takes on the order of log n steps instead of the n steps of linear search.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'verdict',
          label: 'Correct verdict',
          description:
            'States that the explanation contains no conceptual error (2). Hedges, or calls one sentence slightly off without a real error (1). Claims a specific sentence is wrong (0).',
          max: 2,
        },
        {
          id: 'justification',
          label: 'Justification',
          description:
            'Explains why both key ideas hold: sorted order is what lets a half be safely discarded, and repeated halving gives about log2 n steps (2). Explains only one of these (1). Gives no valid reasoning (0).',
          max: 2,
        },
      ],
    },
    hints: [
      'Check each claim: what lets the algorithm ignore half the doors, and how many times can a number be cut in half?',
      'Try it with 8 doors. Count the halvings needed to reach one door, then ask what would go wrong if the numbers were in random order.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'correct',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'binary_search',
    kind: 'transfer',
    variant: 1,
    segs: [31, 32, 33, 34],
    publicPayload: {
      prompt:
        'A classmate writes a recursive search over a sorted array of exam scores. It returns false if the range is empty and returns true if the middle score matches. But when the target is less than the middle score, it calls search on the entire original array again instead of the left half. Explain what goes wrong, and describe how to fix it so the function both terminates and correctly finds scores.',
    },
    answerKey: {
      modelSolution:
        'Calling search on the entire array hands the function the same-sized problem each time, so it never makes progress and recurses forever, or until it runs out of memory. Its base cases, an empty range or a matching middle, are never reached for targets smaller than the middle. The fix is to recurse only on the left half, the elements before the middle, when the target is smaller, and only on the right half when it is larger. Each call then works on about half as many elements, so it eventually hits a base case: the score is found or the range is empty.',
      explanation:
        'Recursion terminates only if each call shrinks the problem toward a base case. Binary search achieves this by halving the search range each time.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Diagnoses the bug',
          description:
            'Explains that recursing on the same-size problem makes no progress and never ends.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct fix',
          description:
            'Recurses on the left half when the target is smaller and on the right half when it is larger.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Base cases',
          description:
            "Explains that the shrinking range eventually reaches 'found' or 'empty', which stops the recursion.",
          max: 2,
        },
      ],
    },
    hints: [
      'Ask whether the problem gets any smaller on each call.',
      'Consider which part of the array could possibly contain a score smaller than the middle one.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        'Calling search on the entire original array can repeat the same middle comparison indefinitely: the problem does not shrink, so neither base case is reached. Keep the empty-range and matching-middle base cases. If the target is smaller, recursively search only the current range to the left of the middle; if larger, search only the range to the right. Exclude the middle element in both cases. Each call then strictly shrinks the range while preserving the only region where the target could occur, eventually returning true for a match or false for an empty range.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'asymptotic_notation',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [8, 9],
    publicPayload: {
      stem: "An algorithm's step count is n²/2 − n/2. Which statement best describes its running time in big O notation?",
      options: [
        {
          id: 'a',
          text: 'O(n²/2), because the constant 1/2 must be kept for accuracy.',
        },
        {
          id: 'b',
          text: 'O(n), because subtracting n/2 cancels out much of the growth.',
        },
        {
          id: 'c',
          text: 'O(n² − n), because every term contributes to the total.',
        },
        {
          id: 'd',
          text: 'O(n²), because for very large n the n² term dominates and lower-order terms and constants are dropped.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        'Big O keeps only the dominant term for large n and ignores constant factors. In n²/2 − n/2, the n² term dominates, so the running time is O(n²).',
    },
    distractorMeta: {
      a: {
        misconception: 'Constant factors are kept in big O.',
        whyWrong: 'Big O discards constant factors such as 1/2.',
      },
      b: {
        misconception: 'Lower-order terms can cancel the dominant term.',
        whyWrong: 'For large n, n²/2 far exceeds n/2, so the growth remains quadratic.',
      },
      c: {
        misconception: 'Lower-order terms must be kept in big O.',
        whyWrong:
          'The other terms do contribute to the exact count, but big O keeps only the most dominant term.',
      },
    },
    rubric: null,
    hints: [
      'Imagine plugging in a very large value of n.',
      'Big O ignores both constant multipliers and smaller terms.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'asymptotic_notation',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [10, 11, 12],
    publicPayload: {
      stem: 'Selection sort, as usually written, scans for the smallest remaining element on every pass, even when the array is already sorted. What can be said about its running time?',
      options: [
        {
          id: 'a',
          text: 'It is O(n²) and Ω(n), so no theta can be given.',
        },
        {
          id: 'b',
          text: 'It is O(n²) and Ω(n²), so it is Θ(n²).',
        },
        {
          id: 'c',
          text: 'It is O(n) on sorted input, so it is Θ(n).',
        },
        {
          id: 'd',
          text: 'It is O(n log n) because each pass gets shorter.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        'Selection sort makes the same comparisons regardless of the input order, so even its best case takes on the order of n² steps. Because its upper bound O(n²) and lower bound Ω(n²) are the same, it is in Θ(n²).',
    },
    distractorMeta: {
      a: {
        misconception: 'Every sorting algorithm has a linear best case on sorted input.',
        whyWrong:
          'That describes bubble sort with an early exit. Selection sort never checks whether the array is already sorted.',
      },
      c: {
        misconception: 'Sorted input makes selection sort fast.',
        whyWrong:
          'It still walks the list on every pass to find the smallest element, so sorted input does not save any comparisons.',
      },
      d: {
        misconception: 'Shorter passes reduce quadratic growth to n log n.',
        whyWrong:
          'The comparisons total (n−1)+(n−2)+…+1 = n(n−1)/2, which is still on the order of n².',
      },
    },
    rubric: null,
    hints: [
      'Consider whether the algorithm ever checks if the list is already in order.',
      'Theta is allowed only when the upper and lower bounds match.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'asymptotic_notation',
    kind: 'spot_flaw',
    variant: 1,
    segs: [7, 8, 11, 12],
    publicPayload: {
      sentences: [
        'Selection sort makes about (n−1)+(n−2)+…+1 comparisons, which equals n(n−1)/2.',
        'Dropping constants and lower-order terms gives O(n²).',
        'Its pseudocode never checks whether the list is already sorted, so it keeps scanning on every pass.',
        'Because its best case on already-sorted input is only Ω(n), we cannot give selection sort a theta bound.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary: "Selection sort's lower bound is Ω(n²), not Ω(n), so its theta bound is Θ(n²).",
      correction:
        'Even on sorted input, selection sort still does about n²/2 comparisons, so it is Ω(n²). Since O and Ω match, it is Θ(n²).',
      explanation:
        'The sentence just before the flaw explains why the best case is not faster: the algorithm ignores the input order. Its upper and lower bounds are therefore both n², and it is Θ(n²).',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Correct lower bound',
          description: "States that selection sort's best case is Ω(n²).",
          max: 2,
        },
        {
          id: 'c2',
          label: 'Theta conclusion',
          description: 'Concludes Θ(n²) because the big O and omega bounds match.',
          max: 2,
        },
      ],
    },
    hints: [
      'Does sorted input actually change how many comparisons selection sort makes?',
      'Compare the claimed best case with the previous sentence.',
    ],
    leakKeywords: ['n squared lower bound', 'same comparisons', 'theta of n squared'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'asymptotic_notation',
    kind: 'spot_flaw',
    variant: 2,
    segs: [18, 19, 20, 22, 23],
    publicPayload: {
      sentences: [
        "Bubble sort's outer loop runs about n−1 times, and its inner loop does about n−1 comparisons per pass.",
        'Comparisons and swaps each take a constant number of steps, so the nested loops determine the growth, giving O(n²).',
        "If we add the rule 'quit after a pass with no swaps', sorted input needs only one pass, so the algorithm is Ω(n).",
        'Since we now know both a big O and an omega bound, bubble sort with this optimization is Θ(n).',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        'Theta can be stated only when big O and omega are the same. Here they are O(n²) and Ω(n), so no theta bound applies.',
      correction:
        'Because the upper bound (n²) and the lower bound (n) differ, we cannot give a theta bound for optimized bubble sort.',
      explanation:
        'Theta requires the upper and lower bounds to match. With early exit, bubble sort is still O(n²) in the worst case but Ω(n) in the best case, so it has no theta bound.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the error',
          description: 'Notes that Θ(n) is incorrect for optimized bubble sort.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Explains the theta rule',
          description:
            'Explains that theta requires big O and omega to be the same, and here they differ (n² vs n).',
          max: 2,
        },
      ],
    },
    hints: [
      'Recall the condition under which theta notation may be used.',
      'Compare the upper bound and the lower bound stated earlier in the explanation.',
    ],
    leakKeywords: ['one and the same', 'bounds differ', 'no theta'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'asymptotic_notation',
    kind: 'transfer',
    variant: 1,
    segs: [9, 12, 18, 19, 20],
    publicPayload: {
      prompt:
        'A function checks an array of n numbers for duplicates. For every i from 0 to n−1, and for every j from 0 to n−1 with j ≠ i, it compares numbers[i] with numbers[j] and sets a flag if they are equal. It never stops early. Its exact step count is about 3n² + 2n + 5. Give its big O, omega and theta running times, and justify each.',
    },
    answerKey: {
      modelSolution:
        'Big O: O(n²). The nested loops produce about n² comparisons, and when we drop the constant 3 and the lower-order terms 2n and 5, n² dominates. Omega: Ω(n²). The function never stops early, so even a best-case input, such as one with a duplicate at the very start, still runs every iteration. Theta: Θ(n²). The upper and lower bounds are the same, so theta applies. Each comparison takes constant time, so the nested loops alone determine the growth.',
      explanation:
        'This exercise applies the rules of keeping only the dominant term, treating constant-time steps as irrelevant, and using theta only when O and Ω coincide.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Big O',
          description: 'Gives O(n²) by dropping constants and lower-order terms.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Omega',
          description:
            'Gives Ω(n²) because the function has no early exit, so the best case still does all the work.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Theta',
          description: 'Concludes Θ(n²) because the big O and omega bounds match.',
          max: 2,
        },
      ],
    },
    hints: [
      'Find the dominant term in the step count.',
      'Ask whether any input lets the function do less work.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        'O(n²), Ω(n²), and Θ(n²). The dominant term in 3n² + 2n + 5 is n²; constants and lower-order terms do not affect asymptotic growth. Because both loops run fully regardless of the values, best- and worst-case work are quadratic, giving matching upper and lower bounds and therefore a tight Θ(n²) bound.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'selection_sort',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [7, 8],
    publicPayload: {
      stem: 'Selection sort runs on an array of 8 numbers. Each pass compares the current smallest value it has found against every remaining unsorted element. How many comparisons does it make in total across all passes?',
      options: [
        {
          id: 'a',
          text: '64, because 8 passes each look at all 8 elements',
        },
        {
          id: 'b',
          text: '28, because the passes make 7 + 6 + 5 + 4 + 3 + 2 + 1 comparisons',
        },
        {
          id: 'c',
          text: '8, because each element is placed into position exactly once',
        },
        {
          id: 'd',
          text: '56, because each of 8 passes makes 7 comparisons',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        'The first pass makes n−1 = 7 comparisons. Each later pass has one fewer unsorted element, so the total is 7+6+…+1. That equals n(n−1)/2 = 8·7/2 = 28, which grows as O(n²).',
    },
    distractorMeta: {
      a: {
        misconception:
          'Thinks every pass rescans the whole array, including elements that are already sorted.',
        whyWrong:
          'After pass i, positions 0..i are already fixed. Later passes only scan the shrinking unsorted part, and a pass over k elements needs k−1 comparisons, not k.',
      },
      c: {
        misconception: 'Counts swaps or placements instead of comparisons.',
        whyWrong:
          'Placing one element needs a whole scan to find the smallest value. Comparisons therefore far outnumber placements.',
      },
      d: {
        misconception: 'Assumes the number of comparisons stays the same on every pass.',
        whyWrong:
          'The unsorted region shrinks by one each pass, so the counts go 7, 6, 5, and so on. They do not stay at 7.',
      },
    },
    rubric: null,
    hints: [
      'Consider how much of the array is still unsorted on each pass.',
      'Add n−1, then n−2, and so on down to 1, for n = 8.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'selection_sort',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [10, 11, 12],
    publicPayload: {
      stem: 'Selection sort is given an array that is already in sorted order, from 0 to 7. What is its running time in this best case?',
      options: [
        {
          id: 'a',
          text: 'Ω(n), because it notices on the first pass that nothing needs to move',
        },
        {
          id: 'b',
          text: 'Ω(1), because no swaps are needed',
        },
        {
          id: 'c',
          text: 'Ω(n²), because it still searches the unsorted part for the smallest element on every pass',
        },
        {
          id: 'd',
          text: 'Ω(n log n), because the sorted order halves the work on each pass',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        'Selection sort never checks whether the list is already sorted. Every pass still scans the rest of the array to find the smallest element. Its best case is therefore Ω(n²), and since its worst case is also O(n²), it is Θ(n²).',
    },
    distractorMeta: {
      a: {
        misconception: 'Confuses selection sort with bubble sort that has an early exit.',
        whyWrong:
          "Selection sort has no 'no swaps, so quit' check. It always performs all of its passes.",
      },
      b: {
        misconception: 'Equates the cost of the algorithm with the number of swaps.',
        whyWrong:
          'Comparisons dominate the cost, and selection sort makes all n(n−1)/2 of them no matter what order the input is in.',
      },
      d: {
        misconception: 'Assumes sorted input lets the algorithm skip work by dividing it.',
        whyWrong:
          'Nothing in selection sort divides the problem. Each pass removes only one element from the unsorted part.',
      },
    },
    rubric: null,
    hints: [
      'Ask whether the pseudocode ever looks at whether the list is already in order.',
      'Count the comparisons on a sorted list and compare that with the count on a random list.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'selection_sort',
    kind: 'spot_flaw',
    variant: 1,
    segs: [10, 11, 12],
    publicPayload: {
      sentences: [
        'Selection sort goes through positions i from 0 to n−1 of the array.',
        'On each pass, it finds the smallest number between numbers[i] and numbers[n−1] and swaps it into numbers[i].',
        'The comparisons add up to (n−1)+(n−2)+…+1, which is n(n−1)/2, so the worst case is O(n²).',
        'If the array is already sorted, selection sort sees during its first pass that every element is already the smallest in its region, so it finishes in Ω(n) time.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        'The scenario claims selection sort detects sorted input and finishes in linear time. In fact, it has no such check, so its best case is Ω(n²).',
      correction:
        'Even on a sorted array, selection sort still scans the rest of the array on every pass to find the smallest element. Its best case is therefore Ω(n²), which makes it Θ(n²).',
      explanation:
        "Selection sort's pseudocode makes no allowance for checking whether the list is already sorted. It repeats every pass and makes all n(n−1)/2 comparisons regardless of the input order.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the error',
          description: 'Points out that selection sort does not detect sorted input or stop early.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct bound',
          description: 'States that the best case is Ω(n²), so the algorithm is Θ(n²).',
          max: 2,
        },
      ],
    },
    hints: [
      'Check whether the pseudocode ever tests if the list is already in order.',
      'Compare the best-case claim with the number of comparisons each pass still makes.',
    ],
    leakKeywords: ['no early exit', 'Ω(n²)', 'Theta of n squared', 'never checks sorted'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'selection_sort',
    kind: 'spot_flaw',
    variant: 2,
    segs: [5, 6, 8, 9],
    publicPayload: {
      sentences: [
        'Selection sort keeps track of only the smallest element seen so far in a single variable, rather than memorizing every value.',
        'Because of this, it rediscovers the next smallest element on each pass, even though it has already looked at every number before.',
        'This is an example of a trade-off between memory and running time.',
        'Since the comparisons total n(n−1)/2, we keep only the dominant n² term and say selection sort is in O(n²).',
      ],
    },
    answerKey: {
      hasFlaw: false,
      flawSentenceIdx: null,
      flawSummary: null,
      correction: null,
      explanation:
        'Every sentence is accurate. Selection sort uses a single variable for the current minimum, which is why it repeats work on later passes, illustrating a time–memory trade-off. Expanding n(n−1)/2 gives n²/2 − n/2, and dropping the lower-order terms leaves O(n²).',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Recognizes correctness',
          description: 'Concludes that there is no flaw in the scenario.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Justification',
          description:
            'Explains the single-variable memory use and the n(n−1)/2 → O(n²) reasoning.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check each claim about memory use and about the arithmetic.',
      'Expand n(n−1)/2 and see which term dominates for large n.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'correct',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'selection_sort',
    kind: 'transfer',
    variant: 1,
    segs: [1, 2, 7, 8, 11, 12],
    publicPayload: {
      prompt:
        'Apply selection sort to the array [4, 1, 3, 0, 2]. Show the array after the first two passes. Then give the total number of comparisons the full sort makes, and explain how that number would change if the input array were already sorted.',
    },
    answerKey: {
      modelSolution:
        'Pass 1 (i=0): the smallest value among all five elements is 0, at index 3. Swap it with index 0 to get [0, 1, 3, 4, 2]. Pass 2 (i=1): the smallest value among indices 1 to 4 is 1, already at index 1, so the array stays [0, 1, 3, 4, 2]. The total number of comparisons is 4 + 3 + 2 + 1 = 10, which is n(n−1)/2 for n = 5. A sorted input still needs exactly 10 comparisons, because selection sort never checks whether the list is already sorted. Its best case equals its worst case, so it is Θ(n²).',
      explanation:
        'This problem applies the find-the-minimum-then-swap step, the shrinking-range comparison count, and the fact that selection sort ignores the initial order of its input.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Correct trace',
          description: 'Shows [0,1,3,4,2] after pass 1 and the unchanged array after pass 2.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Comparison count',
          description: 'Gives 10, the result of 4+3+2+1 or n(n−1)/2.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Sorted input',
          description: 'States that the count is unchanged for sorted input and explains why.',
          max: 2,
        },
      ],
    },
    hints: [
      'Each pass searches only from index i to the end of the array.',
      'Ask whether the algorithm can tell, before it starts comparing, that the list is already sorted.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        'After pass 1: [0, 1, 3, 4, 2]. After pass 2: [0, 1, 3, 4, 2], since 1 is already the smallest remaining element. The full sort makes 4 + 3 + 2 + 1 = 10 comparisons. An already sorted input still requires 10 comparisons because selection sort scans each remaining suffix regardless of the original order.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'bubble_sort',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [14, 15],
    publicPayload: {
      stem: "In bubble sort, the inner loop runs 'for i from 0 to n−2' and compares numbers[i] with numbers[i+1]. Why does it stop at n−2 instead of n−1?",
      options: [
        {
          id: 'a',
          text: 'Because the last element has already been checked on an earlier pass',
        },
        {
          id: 'b',
          text: 'Because the largest element is always already in place before the loop starts',
        },
        {
          id: 'c',
          text: 'Because stopping one early saves a comparison, which changes the big O running time',
        },
        {
          id: 'd',
          text: 'Because if i were n−1, then i+1 would be n, which is past the end of the array',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        "Each comparison looks at positions i and i+1. The array's valid indices run from 0 to n−1. If i reached n−1, the code would read numbers[n], which is outside the array. Stopping at n−2 keeps i+1 within bounds.",
    },
    distractorMeta: {
      a: {
        misconception: 'Thinks the bound reflects work already done on previous passes.',
        whyWrong:
          'The bound applies even on the very first pass. It exists to keep the index i+1 inside the array.',
      },
      b: {
        misconception:
          'Confuses the bounds check with the fact that large values bubble to the end.',
        whyWrong:
          'The largest values do move to the end over several passes, but they are not in place before the first pass begins.',
      },
      c: {
        misconception: 'Believes a single saved comparison changes the asymptotic running time.',
        whyWrong:
          'Dropping one comparison per pass is a lower-order change. It does not explain the bound, and it does not change O(n²).',
      },
    },
    rubric: null,
    hints: [
      'Look at which two positions each comparison accesses.',
      'Ask what index i+1 would be if i were equal to n−1.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'bubble_sort',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [21, 22, 23],
    publicPayload: {
      stem: "A programmer adds one change to bubble sort: after each full left-to-right pass of the inner loop, if no swaps were made during that pass, the algorithm stops immediately. How does this change affect bubble sort's running time?",
      options: [
        {
          id: 'a',
          text: 'It improves both cases: the best case becomes Omega(n) and the worst case becomes O(n log n), because fewer passes are ever needed.',
        },
        {
          id: 'b',
          text: 'It changes nothing in big O terms, because the outer loop still says to repeat n-1 times, so even a sorted list needs on the order of n^2 comparisons.',
        },
        {
          id: 'c',
          text: 'It makes the best case O(1), because an already sorted list can be detected without looking at its elements.',
        },
        {
          id: 'd',
          text: 'On an already sorted list it stops after one pass of about n comparisons, so the best case becomes Omega(n). The worst case is still O(n^2).',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        'With the early exit, a sorted list causes one full pass with no swaps, and then the algorithm quits. That pass is about n comparisons, so the lower bound becomes Omega(n). You cannot claim a list is sorted without checking every element once, so the best case cannot be smaller than that. In the average and worst cases, swaps keep happening on most passes, so the algorithm still runs about n-1 passes of about n-1 comparisons each. That is still O(n^2). Because the upper and lower bounds now differ, there is no single theta bound.',
    },
    distractorMeta: {
      a: {
        misconception: 'Believes the early exit improves the worst case as well as the best case.',
        whyWrong:
          'In the worst case, such as reverse-sorted input, every pass makes swaps, so the early exit never triggers. The running time stays O(n^2).',
      },
      b: {
        misconception:
          'Thinks the outer loop count fixes the running time no matter what the inner loop finds.',
        whyWrong:
          'The early exit ends the algorithm before the outer loop finishes. On sorted input, only one pass is made, so the best case is Omega(n), not n^2.',
      },
      c: {
        misconception: 'Assumes sortedness can be confirmed without examining the data.',
        whyWrong:
          'To know no pair is out of order, the algorithm must compare every adjacent pair at least once. That takes about n steps, not a constant number.',
      },
    },
    rubric: null,
    hints: [
      'Think separately about two inputs: a list that is already sorted, and a list in reverse order.',
      'How many passes happen on a sorted list before the no-swap check fires, and does that check ever fire early on reverse-sorted input?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'bubble_sort',
    kind: 'spot_flaw',
    variant: 1,
    segs: [14, 15, 17],
    publicPayload: {
      sentences: [
        'Bubble sort repeatedly walks the array and compares adjacent elements numbers[i] and numbers[i+1], swapping them if they are out of order.',
        'After each pass, the largest remaining value has bubbled to the end of the unsorted part.',
        'The inner loop goes from 0 to n−2 because the last element was already checked during the previous pass.',
        'With n−1 outer passes and n−1 inner comparisons, there are (n−1)(n−1) steps, which is O(n²).',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'The scenario gives the wrong reason for the n−2 bound. The real reason is to keep i+1 inside the array.',
      correction:
        'The inner loop stops at n−2 so that numbers[i+1] never refers to index n, which is past the end of an array whose indices run from 0 to n−1.',
      explanation:
        "The n−2 bound applies even on the first pass, before any element has been checked. It is a safety check that keeps the code from accessing memory beyond the array's boundary.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the error',
          description: "Rejects the 'already checked' explanation for the n−2 bound.",
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct reason',
          description: 'Explains that i+1 would equal n, which is out of bounds.',
          max: 2,
        },
      ],
    },
    hints: [
      'Consider whether the bound applies on the very first pass.',
      'Ask what index i+1 would be at the final value of i.',
    ],
    leakKeywords: ['out of bounds', 'i+1', 'index n', 'end of the array'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'bubble_sort',
    kind: 'spot_flaw',
    variant: 2,
    segs: [21, 22, 23],
    publicPayload: {
      sentences: [
        'Plain bubble sort makes all of its comparisons even on an already sorted list, so it is O(n²) in the worst case.',
        'We can improve it by stopping after any pass of the inner loop that makes no swaps.',
        'With this change, a sorted list needs just one pass, so the best case is Ω(n).',
        'Since the lower bound is now n, the improved bubble sort runs in Θ(n) overall.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        'The scenario concludes Θ(n) from the best case alone. The worst case is still O(n²), so the bounds differ and no Θ applies.',
      correction:
        'The best case is Ω(n), but the average and worst cases remain on the order of n². Because the big O and Omega bounds differ, we cannot state a single Θ for bubble sort.',
      explanation:
        'Θ applies only when the upper and lower bounds match. The early exit helps only on sorted or nearly sorted inputs. Unsorted inputs still need about n² work.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the error',
          description: 'Explains that Θ(n) does not follow from the best case alone.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct bounds',
          description:
            'States the worst case is O(n²) and the best case is Ω(n), so there is no single Θ.',
          max: 2,
        },
      ],
    },
    hints: [
      'Recall what conditions must hold before we can use Θ.',
      'Ask whether the early exit helps when the list is in reverse order.',
    ],
    leakKeywords: [
      'no theta',
      'worst case still n²',
      'bounds differ',
      'big O and Omega not the same',
    ],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'bubble_sort',
    kind: 'transfer',
    variant: 1,
    segs: [18, 19, 20, 21, 22, 23],
    publicPayload: {
      prompt:
        "Bubble sort runs on an already sorted array of 6 elements. It uses n−1 outer passes and an inner loop from i = 0 to n−2. (a) How many comparisons does it make without the 'quit if no swaps' check? (b) How many does it make with that check? (c) Explain why the check does not improve the algorithm's worst-case big O.",
    },
    answerKey: {
      modelSolution:
        '(a) There are 5 outer passes, each making 5 comparisons (i from 0 to 4), for 5 × 5 = 25 comparisons. This matches (n−1)(n−1). (b) With the check, the first pass makes 5 comparisons and no swaps, so the algorithm stops after 5 comparisons. This is linear, Ω(n). (c) In the worst case, such as a reversed list, every pass makes swaps, so the algorithm never stops early. It still does about (n−1)², which is O(n²), work. The check helps only on sorted or nearly sorted inputs.',
      explanation:
        'This problem applies the loop-bound counting of (n−1)(n−1), the early-exit optimization, and the distinction between best-case and worst-case behavior.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Without check',
          description: 'Computes 25 comparisons.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'With check',
          description: 'Computes 5 comparisons, a single pass.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Worst case reasoning',
          description:
            'Explains that unsorted inputs keep producing swaps, so the worst case stays O(n²).',
          max: 2,
        },
      ],
    },
    hints: [
      'Count the iterations of each loop separately, then combine them.',
      'Think about an input where every pass makes at least one swap.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        '(a) 5 outer passes × 5 comparisons per pass = 25 comparisons. (b) 5 comparisons: the first pass makes no swaps, so the algorithm quits. (c) Worst-case inputs still require a number of passes proportional to n, each with n−1 comparisons, so the worst-case running time remains O(n²).',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'recursion',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [48, 50, 51, 52],
    publicPayload: {
      stem: 'A programmer writes this C function and compiles it with make in CS50\'s environment, where compiler warnings are treated as errors:\n\nvoid draw(int n)\n{\n    draw(n - 1);\n    for (int i = 0; i < n; i++)\n    {\n        printf("#");\n    }\n    printf("\\n");\n}\n\nWhat happens, and what is the appropriate fix?',
      options: [
        {
          id: 'a',
          text: 'It compiles fine. The recursion stops on its own once n reaches 0, because a loop that runs 0 times prints nothing.',
        },
        {
          id: 'b',
          text: 'The build fails because the compiler sees that every path through draw calls draw again. Adding if (n <= 0) return; at the top of the function fixes it.',
        },
        {
          id: 'c',
          text: 'The build fails because C does not allow a function to call itself, so the pyramid must be rewritten with nested loops.',
        },
        {
          id: 'd',
          text: 'The build fails, and the fix is to move the call draw(n - 1) after the printing loop so that each row is printed before recursing.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        "Without a base case, every execution path through draw calls draw again, so the recursion can never end. Clang flags this as infinite recursion. Under CS50's make, warnings are treated as errors, so the build fails. The fix is a base case placed before the recursive call, such as if (n <= 0) return;. Then the calls draw(4), draw(3), draw(2), draw(1) eventually reach draw(0), which returns immediately. Using <= rather than == also handles negative inputs safely.",
    },
    distractorMeta: {
      a: {
        misconception:
          'Believes recursion stops by itself once the problem becomes trivially small.',
        whyWrong:
          'Nothing in the code checks n, so draw(0) still calls draw(-1), then draw(-2), and so on forever. A loop that runs zero times does not prevent the recursive call above it.',
      },
      c: {
        misconception: 'Believes C forbids a function from calling itself.',
        whyWrong:
          'C allows recursion. The working recursive pyramid is the same function with a base case added. The problem here is only the missing stopping condition.',
      },
      d: {
        misconception: 'Believes reordering the statements in a function can replace a base case.',
        whyWrong:
          'With the call moved after the loop, every path still calls draw unconditionally, so the recursion is still infinite. Only a condition that returns without recursing can stop it.',
      },
    },
    rubric: null,
    hints: [
      'Ask what would ever make this function stop calling itself.',
      'Trace draw(1): what does it call next, and is there any line that checks n before recursing?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'recursion',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [54, 55, 56],
    publicPayload: {
      stem: 'A recursive draw function prints a pyramid of height 4 correctly. When the user types an extremely large height, the program crashes, but a loop-based version of the same program does not. What is the best explanation?',
      options: [
        {
          id: 'a',
          text: 'Each recursive call uses a little more memory, and so many nested calls exhaust the memory available to the program.',
        },
        {
          id: 'b',
          text: 'The base case if (n <= 0) only works for small values of n.',
        },
        {
          id: 'c',
          text: 'All the recursive calls share a single loop variable i, which gets corrupted when there are too many calls.',
        },
        {
          id: 'd',
          text: 'printf cannot print more than a fixed number of hashes per program run.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'a',
      explanation:
        "Each call to draw uses some additional memory, and a computer has only so much of it. A huge height means a huge number of nested calls, which uses too much memory and crashes the program. The iterative version does not stack up calls this way. This is the trade-off for recursion's elegance.",
    },
    distractorMeta: {
      b: {
        misconception: "Thinks the base case's correctness depends on the size of the input.",
        whyWrong:
          'The base case n <= 0 is correct for any n. The recursion would eventually reach it, but memory runs out first.',
      },
      c: {
        misconception: 'Believes recursive calls share local variables.',
        whyWrong: 'Each call gets its own copy of i, so there is no shared variable to corrupt.',
      },
      d: {
        misconception:
          'Attributes the crash to output limits rather than to the cost of function calls.',
        whyWrong:
          'The iterative version prints the same hashes without crashing, so printing is not the problem.',
      },
    },
    rubric: null,
    hints: [
      'Think about what differs between the two versions besides the output they produce.',
      'Consider what resource each new function call consumes.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'a',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'recursion',
    kind: 'spot_flaw',
    variant: 1,
    segs: [32, 33, 34, 47, 48],
    publicPayload: {
      sentences: [
        'A recursive function is a function that calls itself somewhere in its own body.',
        'For the Mario pyramid, a pyramid of height n can be defined as a pyramid of height n - 1 plus one more row.',
        'As long as the function has a base case, it does not matter whether the recursive call passes n or n - 1, because the base case will eventually stop it.',
        'A base case like if (n <= 0) return; answers immediately without calling the function again.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'A base case alone does not prevent infinite recursion. Each recursive call must also work on a smaller problem so that it eventually reaches the base case.',
      correction:
        'Each recursive call must pass a smaller problem, such as n - 1, so the input shrinks toward the base case. If draw(n) called draw(n), it would never reach n <= 0 and would recurse forever.',
      explanation:
        'The lecture stresses two requirements: a base case, and recursive calls on a smaller problem. Handing yourself the exact same problem means you never make progress toward the base case, so the recursion never ends.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flawed sentence',
          description: 'Points to the claim that passing n or n - 1 does not matter.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Explains the shrinking requirement',
          description:
            'States that each recursive call must work on a smaller input so that the base case is eventually reached. Otherwise the recursion is infinite.',
          max: 2,
        },
      ],
    },
    hints: [
      'Recall the two things a recursive function needs in order to stop.',
      'Imagine draw(4) calling draw(4). Would n ever reach 0?',
    ],
    leakKeywords: [
      'smaller problem',
      'same input',
      'infinite recursion',
      'never reaches base case',
      'shrink',
    ],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'recursion',
    kind: 'spot_flaw',
    variant: 2,
    segs: [37, 38, 48, 49, 51, 52, 54],
    publicPayload: {
      sentences: [
        'To draw a pyramid of height 4 recursively, draw first calls itself to draw a pyramid of height 3 and then prints one more row of 4 hashes.',
        'That call to draw a pyramid of height 3 in turn draws a pyramid of height 2 before printing its own row, and so on down the chain.',
        'When n reaches 0, the base case if (n <= 0) return; makes the function return without printing anything.',
        'Using <= instead of == also safely handles a negative height by printing nothing.',
        "Each call has its own copy of its loop variable i, so one call's loop does not interfere with another's.",
      ],
    },
    answerKey: {
      hasFlaw: false,
      flawSentenceIdx: null,
      flawSummary: null,
      correction: null,
      explanation:
        'Every sentence is accurate. The pyramid of height n is built as a pyramid of height n - 1 plus one row. The base case n <= 0 stops the recursion and also guards against negative input. Each call keeps its own copy of i.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Recognizes correctness',
          description: 'Concludes that the explanation contains no conceptual error.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Justifies with key ideas',
          description:
            'Cites the smaller subproblem (n - 1), the base case n <= 0, and the separate local variables per call as correct.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check each claim against how the recursive pyramid function is structured.',
      'Pay attention to the base case condition and to what each call owns.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'correct',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'recursion',
    kind: 'transfer',
    variant: 1,
    segs: [33, 34, 37, 38, 51, 52, 55, 56],
    publicPayload: {
      prompt:
        'Write (in C or clear pseudocode) a recursive function int sum(int n) that returns 1 + 2 + ... + n, and returns 0 for n <= 0. Identify the base case and the recursive case. Then explain one risk of calling it with an extremely large n compared with a loop-based version.',
    },
    answerKey: {
      modelSolution:
        'int sum(int n) { if (n <= 0) return 0; return n + sum(n - 1); }. The base case is n <= 0, which returns 0 immediately without calling sum again. The recursive case returns n + sum(n - 1), which calls the function on a smaller problem so that it eventually reaches the base case. The risk is memory: every recursive call uses a bit more memory, so an extremely large n can exhaust it and crash the program. A for loop that adds 1 through n would not have this problem.',
      explanation:
        'This mirrors the pyramid definition: the sum up to n is n plus the sum up to n - 1, much as a pyramid of height n is a pyramid of height n - 1 plus one row. It requires both a shrinking subproblem and a base case, and it carries the same memory trade-off as the recursive pyramid.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'r1',
          label: 'Correct base case',
          description: 'Includes a condition such as n <= 0 that returns 0 without recursing.',
          max: 2,
        },
        {
          id: 'r2',
          label: 'Correct recursive case',
          description: 'Returns n + sum(n - 1), or an equivalent call on a smaller input.',
          max: 2,
        },
        {
          id: 'r3',
          label: 'Memory trade-off',
          description:
            'Explains that each call uses more memory, so a huge n can crash where a loop would not.',
          max: 2,
        },
      ],
    },
    hints: [
      'Express the sum up to n in terms of the sum up to a smaller number.',
      'Decide what the answer should be when there is nothing left to add, and think about what each pending call costs.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        'int sum(int n) {\n    if (n <= 0) return 0;\n    return n + sum(n - 1);\n}\nBase case: n <= 0 returns 0. Recursive case: n > 0 returns n plus the sum for the smaller problem n - 1. Extremely large n can exhaust call-stack memory because each recursive call uses additional memory; a loop-based version avoids this growing stack usage.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'merge_sort',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [58, 59, 60, 61],
    publicPayload: {
      stem: 'Merge sort is merging the sorted list 1 3 4 6 with the sorted list 0 2 5 7 into one sorted list of 8 numbers. Which statement best describes how the merge works and how much work it takes?',
      options: [
        {
          id: 'a',
          text: 'For each element of the left list, scan the entire right list to find where it belongs, which takes about n squared steps.',
        },
        {
          id: 'b',
          text: 'Point at the front of each list, repeatedly take the smaller of the two pointed-at numbers, and move only that pointer rightward, which takes about n steps.',
        },
        {
          id: 'c',
          text: 'Concatenate the two lists and run selection sort on the result, which takes about n log n steps.',
        },
        {
          id: 'd',
          text: 'Compare the two middle elements and recursively merge the halves, which takes about log n steps.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        'Merging uses a left pointer and a right pointer. Each step takes the smaller of the two numbers being pointed at and advances that pointer. The pointers only move right and never go back, so each of the n numbers is placed exactly once, for about n steps in total.',
    },
    distractorMeta: {
      a: {
        misconception:
          'Thinks merging requires repeated back-and-forth scanning, as in selection sort or bubble sort.',
        whyWrong:
          'Because both halves are already sorted, the pointers never need to go back. Merging is linear, not quadratic.',
      },
      c: {
        misconception: 'Confuses the merge step with re-sorting the combined list.',
        whyWrong:
          'Selection sort is Θ(n²), and running it would waste the fact that the halves are already sorted.',
      },
      d: {
        misconception: "Confuses merging with binary search's halving.",
        whyWrong:
          'Every element must be placed into the output, so merging cannot take fewer than n steps.',
      },
    },
    rubric: null,
    hints: [
      'Use the fact that both lists are already sorted.',
      'Track which direction the two pointers move during the merge.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'merge_sort',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [70, 71, 72, 73],
    publicPayload: {
      stem: 'Suppose merge sort, as described with no early-exit check, is given a list of n numbers that is already sorted. Which statement about its running time is correct?',
      options: [
        {
          id: 'a',
          text: 'It finishes in Ω(n), because it can detect after one pass that the list is sorted.',
        },
        {
          id: 'b',
          text: 'It still takes Θ(n²), just like selection sort.',
        },
        {
          id: 'c',
          text: 'It runs in Θ(log n), because it only needs log n levels of halving.',
        },
        {
          id: 'd',
          text: 'It still does about n steps of merging on each of about log n levels, so it is Ω(n log n) and therefore Θ(n log n).',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        "Merge sort has no optimization like bubble sort's rule to stop when no swaps were made. Even on sorted input, it still halves the list about log n times and merges n elements at each level. Its lower bound is therefore n log n. Because its upper and lower bounds are the same, it is Θ(n log n).",
    },
    distractorMeta: {
      a: {
        misconception: "Applies bubble sort's early-exit optimization to merge sort.",
        whyWrong:
          'Merge sort has no swap-checking early exit, so it does the full work even on sorted input.',
      },
      b: {
        misconception: 'Thinks every sorting algorithm on sorted input is quadratic.',
        whyWrong: "Merge sort's work is n per level across log n levels, which is n log n, not n².",
      },
      c: {
        misconception:
          'Counts only the number of levels and ignores the merging work on each level.',
        whyWrong:
          'Each level requires n steps of merging, so the total is n times log n, not log n.',
      },
    },
    rubric: null,
    hints: [
      'Ask whether merge sort ever checks whether its input is already in order.',
      'Multiply the work done per level by the number of levels.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'merge_sort',
    kind: 'spot_flaw',
    variant: 1,
    segs: [57, 58, 59, 60, 61, 70],
    publicPayload: {
      sentences: [
        'Merge sort works by sorting the left half, sorting the right half, and then merging the two sorted halves.',
        'Its base case is a list of one element, which is already sorted, so there is nothing to do.',
        'To merge, you point at the front of each sorted half and repeatedly move the smaller number to the output.',
        'After placing each number, both pointers go back to the start of their halves so that no smaller number is missed.',
        'Repeated halving of 8 numbers gives 3 levels, and each level involves merging all 8 numbers.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        'During a merge, the pointers never go back. Only the pointer whose number was taken advances, and it moves rightward.',
      correction:
        "After taking the smaller number, only that half's pointer moves one step to the right. Neither pointer ever resets, so each number is examined once and merging takes about n steps.",
      explanation:
        'Because both halves are already sorted, the next smallest number is always at one of the two pointers. Moving the pointers back would reintroduce the back-and-forth comparisons that make selection sort and bubble sort slow, and would destroy the linear-time merge.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flawed sentence',
          description:
            'Points to the claim that the pointers go back to the start after each placement.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct pointer behavior',
          description:
            'Explains that only the used pointer advances rightward and nothing resets, so merging takes about n steps.',
          max: 2,
        },
      ],
    },
    hints: [
      'Think about why sorted halves make it easy to find the next smallest number.',
      'Picture the two hands during a merge. Do they ever move left?',
    ],
    leakKeywords: ['only move right', 'never go back', 'reset', 'linear merge', 'n steps'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'merge_sort',
    kind: 'spot_flaw',
    variant: 2,
    segs: [56, 69, 71, 72, 73],
    publicPayload: {
      sentences: [
        'Merge sort is fundamentally faster than selection sort and bubble sort because it does not keep comparing the same numbers again and again.',
        'For n numbers, there are about log base 2 of n levels of halving, and about n steps of merging on each level.',
        'That makes its running time O(n log n), and with no early-exit optimization it is also Ω(n log n), so it is Θ(n log n).',
        'Its speed comes for free, because the merging can be done entirely within the original array without any extra memory.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        "Merge sort's speed is not free. It needs extra space, roughly twice as much memory, in order to merge the halves.",
      correction:
        'Merge sort trades memory for time: merging needs a second area (like a second shelf) to hold the merged output, so it uses about twice as much space as the original array.',
      explanation:
        'The lecture notes that the catch of merge sort is the extra space it needs. Merging two halves required a second shelf to place the sorted output. This illustrates the recurring trade-off between time and memory.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flawed sentence',
          description: 'Points to the claim that merge sort needs no extra memory.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'States the space trade-off',
          description:
            'Explains that merge sort needs about twice as much space to merge, trading memory for speed.',
          max: 2,
        },
      ],
    },
    hints: [
      'Every algorithm choice tends to involve some trade-off.',
      'Think about where the merged numbers are placed while the merge is happening.',
    ],
    leakKeywords: ['twice as much space', 'extra memory', 'second shelf', 'trade-off', 'space'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'merge_sort',
    kind: 'transfer',
    variant: 1,
    segs: [61, 69, 70, 71, 72],
    publicPayload: {
      prompt:
        "A library app must sort 16 book IDs using merge sort. How many levels of halving occur, and roughly how many merging steps happen on each level? Estimate the total work, and compare it with selection sort's roughly n squared steps. Finally, name one cost that merge sort pays for this speed.",
    },
    answerKey: {
      modelSolution:
        'Halving 16 elements gives log base 2 of 16 = 4 levels, since 16 = 2 to the 4th power. On each level, every one of the 16 IDs is placed once during merging, so there are about 16 steps per level. The total is about 16 × 4 = 64 steps, which is n log n. Selection sort would need on the order of 16² = 256 steps, so merge sort does far less work. The cost is memory: merge sort needs about twice as much space, because merging requires a separate area to hold the merged output.',
      explanation:
        'This applies the same analysis as the 8-element example, where there were 3 levels with n merge steps each, giving n log n. It also reflects the time-versus-space trade-off of merge sort.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'r1',
          label: 'Levels',
          description: 'Correctly computes log base 2 of 16 = 4 levels.',
          max: 2,
        },
        {
          id: 'r2',
          label: 'Total work',
          description:
            'Identifies about n = 16 steps per level for about 64 total (n log n), and contrasts this with about 256 steps for selection sort.',
          max: 2,
        },
        {
          id: 'r3',
          label: 'Space cost',
          description: 'Notes that merge sort needs extra memory, about twice the space.',
          max: 2,
        },
      ],
    },
    hints: [
      'Count how many times you can halve 16 before reaching lists of size 1.',
      'On each level, how many numbers get placed during merging?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        "There are log2(16) = 4 halving levels. Each merging level processes roughly 16 elements total, so the estimated work is 16 × 4 = 64 merging steps, versus selection sort's rough n² estimate of 256 steps. Merge sort pays for its speed with additional memory for merging (an auxiliary array of roughly 16 elements in the demonstrated approach).",
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
]
