import type { LectureFx } from './types'

/**
 * CS50x 2026 Lecture 3: Algorithms, core window 1:12:30–1:57:30 (video time).
 * Selection sort (chapter 1:12:20) → bubble sort → recursion → merge sort; ends as the sort race starts (1:57:23).
 * Segments are the official subtitles (https://cdn.cs50.net/2025/fall/lectures/3/lang/en/lecture3.srt), segmented by @lectheo/domain;
 * CC BY-NC-SA 4.0, CS50x 2026 by Harvard University, adapted by Lectheo.
 * Subtitles lightly corrected for ASR errors (scripts/lib/reviewed.ts); timestamps unchanged.
 * GENERATED by scripts/seed-library.ts (Opus 5.5 extraction/drafting, GPT-6.1 Sol blind
 * verification). Do not edit by hand: change the script and re-run it.
 */
export const lecture3: LectureFx = {
  key: 'l3',
  seq: 3,
  title: 'Lecture 3: Algorithms',
  youtubeId: '6Svu_ae5ebk',
  start: '1:12:30',
  end: '1:57:30',
  duration: '1:59:35',
  fallbackAudioUrl: 'https://cdn.cs50.net/2025/fall/lectures/3/lecture3.mp3',
  segments: [
    {
      idx: 0,
      startMs: 4350810,
      endMs: 4385160,
      text: "Let's see if we can't slap some pseudo code on this, thinking of our humans now as more generically in array. So we had the first person at location 0 and we had the last person at location N minus 1. And just for clarity so that you've kind of seen the symbology, this obviously is going to be location N minus 2. Location and minus 3 and so forth until it's sort of you hit the other end that we've already written out. So that's just how we refer to all of our 8 volunteers' locations or in this case 1234567 locations, but in the middle connoting that this can be a much, much larger array.",
    },
    {
      idx: 1,
      startMs: 4385370,
      endMs: 4420709,
      text: "So here's some pseudo code for the first algorithm selection sort for I from 0 ton minus 1. So from the first element to the last element, find the smallest number between. The numbers bracket I and numbers and minus 1. In other words, if you're starting I at 0, look at specifically every lighted number between 0 and location N minus 1. When you have found that smallest element, swap it with the number at location I, which starts again at 0. That's how we got, I think, Jaden into place at the very beginning.",
    },
    {
      idx: 2,
      startMs: 4420959,
      endMs: 4456680,
      text: "Then I, by nature of how 4 loops work, gets updated from 0 to 1 so that we do the same thing. Find the smallest number between numbers 1, so the second element through the 8th element because this number is unchanged and is the total number of values, so the end point there is not changing. Once we found the second smallest person, we swap them with. Location I aka 1, and that's how we got the number 1 into position and then the number 2 and then the number 3 and number 4. So this then was selection sort in pseudo code form and that allowed us to actually go through this list again and again and again in order to find the next smallest element.",
    },
    {
      idx: 3,
      startMs: 4456759,
      endMs: 4489649,
      text: "So what was happening a little more methodically if it helps just to map that symbology of the bracket notation in the eyes, if this is where we started with location I and we did everything between location and minus 1. Essentially I traversed this whole list from left to right, literally walking in front of our volunteers looking at each element, and the first element I saw was 7. At the moment that was the smallest element I had found, and who knows, in a different list. Maybe 7 would be the smallest element, so I kind of stored it in a variable in my mind, but I checked then 2 and remembered, no, 2 is clearly less than now I'm going to remember 2.",
    },
    {
      idx: 4,
      startMs: 4490100,
      endMs: 4528812,
      text: "OK, now I'm going to remember one when I find it, and then I'm going to remember 0 when I find it, and then what I did once I found jade in it with the value of 0, light it up. I moved that location to here and then evicted Precious recall and moved Precious over to that location that we had freed up. Why? Why all this sort of back and forth? Well, you have to assume with an array that you're not entitled to the memory over here. You're not entitled to the memory over here if you've already decided that you have 7 lockers or 8 people, you have to commit to the computer in advance. That's why we put the number typically in the square brackets or the compiler infers from the curly brackets how big the array actually is.",
    },
    {
      idx: 5,
      startMs: 4529022,
      endMs: 4564686,
      text: "All right, and suffice it to say when I went through this again and again and again, I did the same thing over and over. Now you might have thought me sort of dumb for having asked the same. Questions again and again like I was surprised to discover the number 1. I was surprised to discover the number 2, even though on my very first pass I literally looked at all eight of those numbers. But you have to think about what memory I'm actually using now. I certainly could have memorized all of the numbers and where they are, but I proposed that just very simply I was using like a single variable in my brain just to keep track of the then smallest element. And once I'm done finding that and solving that problem, I moved on to do it again and again.",
    },
    {
      idx: 6,
      startMs: 4564939,
      endMs: 4594270,
      text: "But that's going to be a trade off, and this is going to be thematic in the coming weeks whereby, well, sure you could use more memory and I could have been smarter about it and maybe that would have improved or hurt the running time of the algorithm. There's often going to be a trade-off between how much memory or how much time you actually use. So we'll discover that over time. So how fast or slow is selection sort? Well, consider when I had 8 humans on stage, I first went through. Uh, all of them, but how many comparisons did I make?",
    },
    {
      idx: 7,
      startMs: 4594410,
      endMs: 4630790,
      text: "Really, I was doing N minus 1 comparisons because if I've got N people, I've got to compare the smallest number I found against everyone else, and you compare N people left to right, N minus 1 times total. So the first pass I was making, I was asking N minus 1 questions. Is this the smallest? Is this the smallest N minus 1 times? Once I solved one problem when we got Jayden into Jayden's right place, then I had one fewer problem, then. One fewer fewer problem and so forth. So it was like n minus 1 steps plus N minus 2 steps plus N minus 3 steps plus one final step once I got to the final of the eight problems.",
    },
    {
      idx: 8,
      startMs: 4630890,
      endMs: 4657209,
      text: "Now if you remember kind of the cheat sheet at the back of your math books, say growing up, you'll note that this series here can be more simply written as N times N minus 1, all divided by 2. And if you've not seen that before, just take on faith that this is identical to this series of numbers up here. So now we can just kind of multiply this out. So that's technically n2 minus N all divided by 2, which is great if we multiply that out, that's n2d over 2 minus n over 2. We're getting 2 into the weeds.",
    },
    {
      idx: 9,
      startMs: 4657290,
      endMs: 4696220,
      text: "Let's whip out our big O notation now whereby we can wave our hands at the lower order terms, only care about the biggest, most dominant term which mathematically in this expression, if you plug in a really big value of n, which is going to matter more the N squared, the 2, the N, or the 2. Like the N squared, like the others absolutely contribute to the total value, but if you plug in a really big value, the dominant force is going to be this n squared because that's really going to blow up the total value. So we can say that selection sort when analyzed in this way, ah, it's on the order of n squared steps because I'm doing so many comparisons so many times.",
    },
    {
      idx: 10,
      startMs: 4696629,
      endMs: 4734069,
      text: "So if that's the case, the question then is, Um, what is indeed not just its upper bound but maybe it's lower bound as we'll eventually see. So for selection sort for now, let's stipulate that it's indeed in big O of n², and that's actually the worst of the algorithms we've seen. Like that's way slower than linear search because at least linear search was big O of N. Selection sort is n square, which of course is n times n, which is and will feel much, much slower than that. So what if though we consider the lower bound of selection sort? All right, maybe it's bad in the worst case, but maybe it's really good when the numbers are mostly sorted. Unfortunately this is the same pseudo code for selection sort.",
    },
    {
      idx: 11,
      startMs: 4734319,
      endMs: 4773785,
      text: "We make no allowance for checking the list to make sure it's already sorted, and in fact that's kind of a perverse case to consider for any algorithm. What if the problem's already solved? How's your algorithm going to perform? All of my volunteers, as they kind of almost did accidentally, they started lining up roughly in order. Suppose they literally had been in order from 0 to 7. Well, my stupid algorithm would still have me walking back and forth, back and forth, back and forth. Why? Because the code literally tells me do this this many times and every time I do that find the smallest element. So it's going to be sort of a stupid output because the list is not going to be any change, any any at all changed, but my code is not taking into account in any way.",
    },
    {
      idx: 12,
      startMs: 4774149,
      endMs: 4811700,
      text: "The original order of the numbers. So no matter what, this is to say that if we consider whether the lockers or the humans, the omega notation for this algorithm, even in the best case where the data is already sorted, is crazily also n squad. Now I could certainly change the pseudo code, but selection sort as the world knows it is more of a. Constrative algorithm or sort of a quick and dirty one, its running time is going to be in omega of n², and now we can actually deploy our fader notation because the big O notation is n² and the omega notation is n2 1 and the same. We can also say that selection sort is in theta of n², which is not great because that's annoyingly slow.",
    },
    {
      idx: 13,
      startMs: 4812100,
      endMs: 4841270,
      text: "So maybe the solution here is don't do that. Let's use bubble sort instead. The second algorithm where I just compared everyone side by side again and again. Well, here's some pseudo code for bubbleor, which you can assume applies to the same kind of array from 0 on up to n minus 1. Here's one way to write bubble sort. Repeat the following N times. For I, from 0 ton minus 2, if the number at location I and the number at location I + 1 are out of order, swap them.",
    },
    {
      idx: 14,
      startMs: 4841870,
      endMs: 4879490,
      text: "And there's kind of an elegance to this algorithm and that like that's it and you just assume that when you go through the list, this is how from I from 0 ton minus 2, this is how I was effectively comparing elements 0 and 11 and 22 and 33 and 476 and 7, but notice I didn't say 8, there were 8 total people. Why do we go from 0 ton minus 2 instead of from 0 ton minus 1? Uh, yeah. Yeah You already checked the glass. Not quite. So it's not that we've already checked the last one.",
    },
    {
      idx: 15,
      startMs: 4879560,
      endMs: 4913470,
      text: "I'm saying with this line of code here, we never even go to N minus 1 technically. If we have N minus 345, and it's going to compare against N minus 1 because that's. Exactly, because we're doing this simple arithmetic here, we're checking current location I plus 1. You can think of these as my left and right hand. Left hand is pointing at 0, right hand's pointing at 1. I don't want to do something stupid and have my left hand point at N minus 1 because then my right hand arithmetically when you add 1 is going to point at N, which does not exist. That's beyond the boundary of the array because the array goes from 0 ton minus 1. So just a live.",
    },
    {
      idx: 16,
      startMs: 4913540,
      endMs: 4952600,
      text: "A bit of a safety check there to make sure we don't walk right off the end of the array, but we do this end times because recall that Precious ended up being where 7 needed to be at the very end of the list, but that didn't mean there weren't 77 more problems still to solve 0 through 6. So I did it again and I did it again and per its name bubble sort, the biggest element bubbled up first, then the next biggest, then. biggest that is 7, then 6, then 5, then 4, and we got lucky on some of them, but eventually we finished with 0. So how do we analyze this thing? Well, we could also technically do this N minus 1 times as an aside if you're thinking through that I'm wasting some time because we get one for free.",
    },
    {
      idx: 17,
      startMs: 4952680,
      endMs: 4991839,
      text: "Once we get to solving 7ve problems, you get the 8th 1 for free because that person is obviously where they need to go. So when we had these numbers initially, And we were comparing them with bubbleword again, left hand right hand. It's like treat this as I, this is I plus 1, and we just kept swapping pair wise numbers if in fact they were out of order. So all this is saying is what our humans were doing for us organically. So how do we actually analyze the running time of this? Last time I just kind of spitballed that it was minus 1 steps plus N minus 2 steps. Well, you can actually look at pseudocode sometimes and if it's neatly written, you can actually Infer from the pseudo code how many steps each line is going to take.",
    },
    {
      idx: 18,
      startMs: 4992049,
      endMs: 5030990,
      text: "For instance, how many steps does this first line take? I mean, like literally n minus 1. The answer is right there because it's saying to the computer or to me acting it out, repeat the following N minus 1 times. All right, so that's helpful. How many lines, how many steps does this inner loop induce? Well, you're going from 1 ton minus 2, so that's actually N minus 1, total steps, not n. And then this question here, if numbers bracket 1 and numbers 1 are out of order, it's a single question. It's like our Boolean expression, we'll call it one. I mean, maybe you need to do a bit of more work than that, but it's a constant number of steps. Doesn't matter how big the list is, comparing two numbers is always going to take the same amount of time.",
    },
    {
      idx: 19,
      startMs: 5031319,
      endMs: 5063064,
      text: "And then swapping them, oh, I don't know, it's going to take like 1 or 2 or 3 steps, but constant doesn't matter which the numbers are, takes the same amount of work. So let's stipulate, let me rewind, stipulate that the real things that matter are the loops, these constant number of steps, who really cares? But the loops are what are going to add up as N gets large. So this really then is. If this is the outer loop and this is the inner loop, think about our two dimensional Mario square from week one. We did something on the outside and then something on the inside to get our rows and columns. This is equivalent to N minus 1 times N minus 1.",
    },
    {
      idx: 20,
      startMs: 5063294,
      endMs: 5100272,
      text: "If we do our little foil method n² minus N minus N + 1 combined like terms, n² minus 2 N + 1, who cares? This is ultimately going to be on the order of big O of. N squared only because again if you ask yourself when I plug in a really big value for N, which of these is really going to contribute most to the answer, it's obviously going to be n2d again and we can ignore the lower order terms. So this doesn't seem to have made any progress. Like selection sort was on the order of big events was on the order of n². Bubble sort, based on this analysis is. Also on the order of n², maybe we're getting lucky in the lower bound.",
    },
    {
      idx: 21,
      startMs: 5100312,
      endMs: 5133766,
      text: "So on the upper bound for bubble sort, it's indeed n², as was selection sort. But with this pseudo code for bubble sort, unfortunately we, or rather unfortunately we were not doing anything clever to catch that perverse case where maybe the list was already sorted. After all, consider if the list was sorted from 0 to. I was still asking all the same darn questions. Even if I did no work, I was going to repeat that n minus 1 times back and forth, making no swaps, but making all of those comparisons. But here's an enhancement to bubble sort that we can add that selection sort didn't really have room for.",
    },
    {
      idx: 22,
      startMs: 5134175,
      endMs: 5171379,
      text: "I can say after one pass of this inner loop walking from left to right, if I made no swaps, quit. So put another way, if I traversed the list from left to right, I make no swaps. I might as well just terminate the algorithm then. Because there's no more work clearly to be done. All right, so based on that modification, the lower bound of bubble sorts running time would be said to be an omega then of. And because I'm minimally going to need to make one pass through the list. You can't possibly claim that the list is sorted unless you actually check it once.",
    },
    {
      idx: 23,
      startMs: 5171459,
      endMs: 5206319,
      text: "And if there's an elements, you're going to have to look at all of them to make sure that it's in order. But after that, if you've done no work and made no swaps, no reason to traverse the list again and again and again. So a bubble sort can be said to be an omega of N because indeed we can just terminate. After that single pass if we've done no work, we can't say anything about theta because they're not one and the same big O and Omega, but that does seem to have given us some savings. Unfortunately, it really only saves us time when the list is already or mostly sorted, but in the average case and in the worst case, odds are they're both going to perform just as bad on the order of n2.",
    },
    {
      idx: 24,
      startMs: 5206399,
      endMs: 5239620,
      text: "In fact, let's take a look at a visualization that will make this a little clearer than our own humans and voices might have. Explained here is a bunch of vertical purple bars made by a friend of ours in the real world, and this is an animation that has a bunch of buttons that lets us execute certain algorithms. A small bar represents a small number. A big bar represents a big number, and the goal is to get them from small numbers or small bars to big numbers or big bars left to right. So I'm going to go ahead and click on selection sort initially, and what you'll see from left to right is in pink the current smallest element.",
    },
    {
      idx: 25,
      startMs: 5239742,
      endMs: 5278523,
      text: "That's been discovered, but also in pink, the equivalent of my walking across the stage left to right again and again and again trying to find the next smallest element and you'll see clearly just like when we put Jayden at the far left, the smallest element ended up over here, but it might take some time for Precious, for instance, or number 7 to end up all the way over on the right because with each pass we're really just fixing one problem at a time and there's N problems total, which is giving us on the order of. N squared steps and now the list is getting shorter, so we're at least doing some work that you don't have to keep touching the elements you already sorted with just like I was. So now selection sort is complete. Let's visualize instead bubble sort.",
    },
    {
      idx: 26,
      startMs: 5278583,
      endMs: 5309666,
      text: "So let me re-randomize the array just so we're starting with a random order. Now let's click on bubble sort and you'll see the pink bars work a little differently. It connotes which two numbers are being compared at that moment in time, just like my left hand and right hand going left to right, and you'll see that even though it's not quite as pretty. A selection sort where I was getting at least the smallest elements all the way to the left. Here we're just fixing pair wise problems, but the biggest elements like Precious's number 7 are indeed bubbling their way up to the top one after the other.",
    },
    {
      idx: 27,
      startMs: 5309916,
      endMs: 5330839,
      text: "But as you can see, and this is where n2d is sort of visual visualizable, we're touching these elements or looking at them so many times again and again. We are making so many darn comparisons. This is taking frustratingly long, and this is only what, a few dozen bars or numbers. You can imagine how long this might take with hundreds, thousands or millions of values.",
    },
    {
      idx: 28,
      startMs: 5331089,
      endMs: 5364220,
      text: "I dare say we're gonna have to do better than bubble sort and Selection sort because we're not stun even yet, just trying to give the satisfaction of getting to the end and now we are, but neither of those algorithms seems incredibly performing because it's still taking us quite a bit of time to actually get to that there solution. So how can we actually do better than that? Well, we can try taking a fundamentally different approach, and this is one technique that you might have encountered in math or even in the real world, even if you haven't sort of applied this name to it.",
    },
    {
      idx: 29,
      startMs: 5364549,
      endMs: 5402100,
      text: "Recursion is a technique in mathematics and in programming that allows you to take sort of a fundamentally different approach to a problem and in short, a recursive function is one that's defined in terms of itself. So if you had like F of X equals F of something on the right hand side of a mathematical expression, that would be recursive in that the function is dependent on itself. More practically in the world of programming, a recursive function is a function that calls it. Self. So if you are writing some function in C and in that function you call yourself. You actually have a line of code that says call that same function by the same name, that function is recursive.",
    },
    {
      idx: 30,
      startMs: 5402350,
      endMs: 5441149,
      text: "Now this might feel a little weird because if a function is calling itself, it feels like this is the easiest way to get into an infinite loop because why would it ever stop if the function is calling itself, calling itself, calling itself? We're going to have to actually address that kind of problem. But in the real world. We've actually, or rather in this class already, we've actually seen implicitly an example of this, including today as well as in week 0. So here's that algorithm for searching the doors of the lockers and recall that after we did this check at the very top if there are any doors left, returned false, if not, we did these conditions. We said if the numbers behind the middle door returned true because we found it, but things got interesting here.",
    },
    {
      idx: 31,
      startMs: 5441319,
      endMs: 5478700,
      text: "I said if else if the number is less than the middle door, then search the left half. Else if the number is greater than the middle door, then search the right half. Well, at that point in time, you should be asking me or yourself, well, how do I search the left half? How do I search the right half? Well, here you go. Like on the screen right now is a search algorithm, and even though it says down here search the left half or search the right half, which is like, well, how do I do? That we'll just use the same algorithm again and this is how in terms of my voiceover you end up searching the left half of the left half or the right half of the left half or any such combination.",
    },
    {
      idx: 32,
      startMs: 5479109,
      endMs: 5511609,
      text: 'This line here search left half, this line here search right half is representative of a recursive call. This is an algorithm or a function that calls itself, but why does it not induce an infinite loop? Like why is it important that this line and this line are written exactly as they are, so as to avoid this thing just forever searching aimlessly, yeah. We do have this condition at which it stops, but more importantly, what is happening before I make these recursive calls?',
    },
    {
      idx: 33,
      startMs: 5514540,
      endMs: 5549466,
      text: "Exactly, I'm recursing, that is calling myself, but I'm handing myself a smaller problem, a smaller problem, a smaller problem. It would be bad if I just handed myself the exact same number of doors and just kept saying search these, search these, search these because you would never make any progress. But just like our volunteers earlier, so long as we did divide and conquer and we searched smaller and smaller numbers of doors, eventually indeed we're going to bottom out and either find the number we're looking for or we're not. So. we're going to call these kinds of conditions that sort of just ask a very obvious question and want an immediate answer base cases.",
    },
    {
      idx: 34,
      startMs: 5549597,
      endMs: 5586604,
      text: 'Base cases are generally conditionals that ask a question to which the answer is going to be yes or no right then and there. A recursive case, by contrast, these two down here is when you actually need to do a bit more work to get to your final answer. You call yourself, but with a smaller version of the problem. So we could have in fact in week 0 have written this. Sort of similarly, if you go back to in your mind to week 0, we had more of a procedural approach, so to speak. When we were searching the phone book, I proposed that this induced what we called loops on line 8 and line 11, which is literally said go back to line 3, and that was more of a mechanical way of sort of inducing a loop structure.',
    },
    {
      idx: 35,
      startMs: 5586733,
      endMs: 5626471,
      text: "But if I really wanted to be elegant, I could have said, well, you know what, 7 and 8 together really just means search the left half and 10 and 11 together really mean just search the right half. So let's condense these. Pairs of lines into shorter instructions. Search the left half of the book, search the right half of the book. I can then delete two blank lines, and now I have a recursive algorithm for searching a phone book. It's a little less obvious because you have to ask yourself when you get to line 7 or 9, Wait a minute, how do I search the left half or the right half? And that's when you need to realize you start the same algorithm again but with a problem that's half as large. In week 0 we do the procedural approach where we literally tell you what line of code to go to.",
    },
    {
      idx: 36,
      startMs: 5626910,
      endMs: 5661064,
      text: "But today we're offering a different formulation, a recursive approach where it's more implicit what you should do. And we'll see now a couple of examples from the real world, so to speak. So here's a screenshot from Super Mario Brothers 1 on the original Nintendo Entertainment System. Let me go ahead and get rid of some of the distraction, like the ground and the mountains there, and here we have a sort of half pyramid, not unlike that you implemented in Problems set 1, but this is an interesting real world physical structure in that you can define it recursively, like what is a pyramid of height. 4, if you will.",
    },
    {
      idx: 37,
      startMs: 5661375,
      endMs: 5686435,
      text: "Well, just to be a little, a little difficult, a pyramid of height 4 is really just a pyramid of height 3 plus one more row. OK, well, what is a pyramid of height 3? Well, a pyramid of height 3 is really just a pyramid of height 2 plus one more row. Well, what's a pyramid of height 2? Well, a pyramid of height 2 is really just a pyramid of height 1 plus one more row. Well, what's a pyramid of height 1? A single brick on the screen.",
    },
    {
      idx: 38,
      startMs: 5686759,
      endMs: 5722359,
      text: "And I sort of changed my tone with that last remark to convey that this could then be our base case whereby I just tell you what the thing is without sort of kicking the can and inviting you to think through what a smaller structure is plus one more row, whereas every other definition I gave you then of a pyramid of some height was defined in terms of that same structure, albeit a smaller version thereof. So we can actually see this in the real world. Let me go ahead and pull up one thing here. I'm going to go to. Give me one sec before I flip over. Here I am on Google.com, if you'd like a little computer science humor here.",
    },
    {
      idx: 39,
      startMs: 5722529,
      endMs: 5757520,
      text: "Uh, if you ever Google search for recursion and hit enter, you'll see uh a joke that computer scientists at Google find funny. Ha ha, 12, lasts. Does anyone see the joke? I did not make a typo, but Google's asking me, did I mean recursion? And if I click on that, I just get the same ha ha page. OK, all right, that didn't go over well. Anyhow, so there are these Easter eggs in the wild everywhere because computer scientists are the ones that implement these things. But let's go ahead and actually implement, for instance, a version of this in code.",
    },
    {
      idx: 40,
      startMs: 5757580,
      endMs: 5787524,
      text: "Let me go back over here in a moment to VS code, and in VS Code, let me propose that in my terminal window. Let me create one of two final programs. This one's. Going to be called iteration.c just to make clear that this is the iterative that is loop-based version of a program whose purpose in life is to print out a simple Mario pyramid. I'm going to go ahead and include CS50. H at the top as well as standardio.h. I'm not going to need string.h. I don't need any command line arguments today, so this is going to start off with main void.",
    },
    {
      idx: 41,
      startMs: 5787759,
      endMs: 5821904,
      text: "And now I'm going to go ahead and ask a question like, uh, give me a variable called height of type integer and ask the human for the height of this Mario like pyramid. And then let's assume for the moment that I've already implemented a function called Draw whose purpose in life is to draw a pyramid of that height semicolon. So I've abstracted away for the moment the notion of drawing that pyramid. Now let's actually implement Dra, whose purpose in life again is to print out a pyramid akin to the one we saw a moment ago like this here on the screen. Well, in order to print out a pyramid of a given height, I think I need to say void.",
    },
    {
      idx: 42,
      startMs: 5822540,
      endMs: 5858379,
      text: "Uh, drawn for instance because I'm not going to bother returning a value. I just want this thing to print something on the screen, so void is the return type, but I do want to take as input an integer like the height of the thing I want to print. I can call this argument or parameter anything I want. I'll call it N for number. So how can I print out a pyramid that again looks like this? Well, I'll do this quicker than you might have in problem set 1, but it seems obvious that like on the first row I want 1 brick. On the second row I want 2. On the 3rd I want 3. On the 4th, I want 4. So it's actually a little easier than problem set 1 in that it's sloped in a different direction. So let me go ahead and do exactly this in code.",
    },
    {
      idx: 43,
      startMs: 5858490,
      endMs: 5893000,
      text: "Let me say 4 NI equals 01 less than n, the height, I plus plus. So this is going to be really for each row of the pyramid pyramid. Let me go ahead now and in an inner loop for in J equals 0, let's do J less than. I plus 1 for reasons we'll see in a moment and then J++ and then inside of this loop, let's just print out a single hash, no new line, but at the end of the row, let's print out a single new line to move the cursor to the next line. Now why am I doing this?",
    },
    {
      idx: 44,
      startMs: 5893049,
      endMs: 5931529,
      text: "Well, this represents for each column of pyramid, and if you think about it on the first row, which is row 0, I actually want to print not zero bricks but one brick. That's why I want to go ahead here and go from 0 to I plus 1, because if I is +01 + 1 is 1, so my inner loop is going to go from 0 to 1, which is going to give me 1 brick. It's a little annoying to think about the math, but this just makes sure that I'm actually getting bricks in the order I want them. And then it's going to give me 2 bricks and then 3 and then 4, and between each of those rows it's going to print a new line. So let's go ahead and do make iteration to compile this code. Ah, I messed up.",
    },
    {
      idx: 45,
      startMs: 5932569,
      endMs: 5968859,
      text: "Why do I have a mistake online? 8 of this code. Let me hide my terminal and scroll back up. It seems clang. My compiler does not like my draw function. Yeah. Yeah, I forgot the prototype. So this is the one and only time where it seems reasonable to copy paste. Let's grab the prototype of that function up here and go ahead and teach the compiler from the get-go what this function is going to look like, even though I'm not defining it now until line 13 onward. All right, let's go ahead and make iteration again. Ah, iteration enter. Let's do a height of say 4 and voila. Now I've got that there pyramid.",
    },
    {
      idx: 46,
      startMs: 5969049,
      endMs: 5997850,
      text: "So I did it a little quickly and it's certainly to be expected if it took you hours on problems set one to get the other type of pyramid printed, but the point for today is really to demonstrate how we can print a pyramid like this using indeed what I'd call iteration. Iteration just means using loops to solve some problem, but we can. Alternatively use recursion by reimplementing our draw function in a way that's defined in terms of itself. So let me go into my code here and I'm actually going to leave the prototype the same.",
    },
    {
      idx: 47,
      startMs: 5997990,
      endMs: 6025700,
      text: "I'm going to leave main the same, but what I'm going to go ahead and do is delete all of this iterative code that's doing things very procedurally, step by step by step with loops, and I'm instead going to do something like this. Well, if I want to print a pyramid of height N. What did I say earlier? Well, a pyramid of height N is really just a pyramid of height N minus 1 plus 1 more row. So how do I implement in code that idea?",
    },
    {
      idx: 48,
      startMs: 6025830,
      endMs: 6063549,
      text: "Well, let me go back in code here and say, well, if a pyramid of height N first requires drawing a pyramid of height N minus 1, I think I can just write this, which is kind of crazy to look at, but because you're calling yourself in yourself, but let's see where this takes us. Once I have drawn a pyramid of height and minus 1. That is a height 3 for instance. What remains for me to do is to myself print one more row. And so to print one more row, I think I can do that really easily with fewer loops. I can do 4 in, I equals 01 less than N I plus plus, and then very simply in this loop I can. Print out a single hash one at a time.",
    },
    {
      idx: 49,
      startMs: 6063560,
      endMs: 6103209,
      text: "At the end of this loop, I can print out a new line, but no more nesting of loops. What I've done is print one more row, and here I've done print a pyramid of height and minus 1. I'm not quite done yet, but I think this is consistent with my verbal definition that a pyramid of height 3 is a pyramid of a pyramid of height 4 is a pyramid of height 3, which I can implement per line 16. Just draw me a pyramid of height and minus 1, and then I myself will take the trouble to print the 4th and final row. But something's missing in this code.",
    },
    {
      idx: 50,
      startMs: 6103580,
      endMs: 6143049,
      text: "Let me go ahead and try running it. Let's see what happens. Make, oh darn it. I meant to call this something else, so I'm going to do this. I'm going to close this version here. I'm going to rename iteration.c to recursion.c to make clear that this version is completely different. Let me now go ahead and make the recursion version and huh, Klang is noticing that I have screwed up on line 14, it says error. All paths through this function will call itself, and Klang doesn't even want to let me compile this code because that would mean literally just forever. Loop effectively by calling yourself. So what am I missing in my code here if I open up what we're now calling recursion.c.",
    },
    {
      idx: 51,
      startMs: 6143990,
      endMs: 6183355,
      text: "In my editor What's missing here over here? Yeah, I'm missing a base case, and I can express this in a few different ways, but I would propose that before I do any drawing of anything at all, let's just ask ourselves if there is anything to draw. So how about if N equals equals 0? Well then don't do anything, just return. You don't return a value when your return value is void, it means you don't return anything, so you just return period or return semicolon. Or just to be super safe, I could actually do something like this, which is arguably better practice just in case I get into this perverse scenario where someone hands me a negative number, I want to be able to handle that and not print anything either.",
    },
    {
      idx: 52,
      startMs: 6183476,
      endMs: 6217401,
      text: "So just to be safe, I might say less than or equal to 0. I'm not doing one because if I did do one, then I would want to at least myself print out one brick, which is fine, but I have to like change all of my code. Little bit, so I think it's safer if my base case is just if n is less than or equal to 0, you're done. Don't do anything. And this then ensures that even though thereafter, I keep calling draw again and again and again and the problem's getting smaller and smaller from 4 to 3 to 2 to 1, as soon as I hit 0, the function will finally return.",
    },
    {
      idx: 53,
      startMs: 6218339,
      endMs: 6255029,
      text: "So let's go ahead and open up my terminal, rerun make recursion to make this version did compile this time recursion enter. Let's type in 4 cross my fingers, and this too prints the exact same thing. And even though it doesn't look like fewer lines of code, I would offer that there's an elegance to what I've just done, whereas with the iterative version with all the loops, it was very clunky, like step by step, just print this and print that and have a nested loop inside of another. But with this, especially if we distill it into its essence. By getting rid of my comments like this and frankly I can get rid of the unnecessary curly braces only because for single lines in conditionals you don't need them.",
    },
    {
      idx: 54,
      startMs: 6255240,
      endMs: 6292979,
      text: "Like this is arguably like a very beautiful implementation of drawing Mario's pyramid even though it's calling itself and arguably because it is calling itself. Questions then on this idea of recursion or this implementation of Mario, yeah. Call Good question. Are there any scope issues involved? Short answer No. However, the current value of I, for instance, will not be visible to the next time the function is called. It will have its own copy of I if that's what you mean. And we'll next week talk in more detail about what's going on here.",
    },
    {
      idx: 55,
      startMs: 6293060,
      endMs: 6331339,
      text: "And in fact, I probably can't break this in class very easily, but it turns out if I use a very large version for heights, let's just hit a lot of zeros and see what happens. That was too many. Let's see what happens. That's also too many. Let's see what happens there. That's the first time at least I and class have encountered this error. You might have encountered this weird bug in office hours or in your problem set, and that's fine if you did. We'll talk about what this means next week too, but this is bad. Like this clearly hints at a problem in my code. However, the iterative version of this program would not have that same error. So this relates to something involving memory because it turns out as a little teaser for next week.",
    },
    {
      idx: 56,
      startMs: 6331485,
      endMs: 6369041,
      text: "Each time I call Draw, I'm using a little more memory, a little more memory, and my computer only has so much memory. This program in its current form is using too much memory. There are workarounds to this, but that is a trade off to the elegance we're gaining in this solution. So what's the point of all this and how do we get sidetracked by Mario? There's another sorting algorithm, the 3rd and final one that we'll consider today that actually Is recursion to solve the problem not only elegantly arguably, but also way faster somehow than bubble sort and selection sort. And in essence it does so by making far fewer comparisons and wasting a lot less work.",
    },
    {
      idx: 57,
      startMs: 6369131,
      endMs: 6408214,
      text: "It doesn't keep comparing the same numbers again and again. Here in its essence is the pseudo code for merge sort. Sort the left half of the numbers. So the right half of the numbers, then merge the sorted halves, and this is kind of a weird implementation of an algorithm because I'm not really telling you anything. It seems like you're asking me how do I sort numbers, and I say, we'll sort the left half, sort the right half. It's like someone being difficult and yet implicit in this third line is apparently some magic, this notion of merging halves that are somehow already. is actually going to yield a successful result. As an aside, we're actually going to need one base case here too. So if you're only given one number, you might as well quit right away because there's nothing to do.",
    },
    {
      idx: 58,
      startMs: 6408504,
      endMs: 6441069,
      text: "So we'll toss that in there as well. And base cases are often for 0 or 1 or some small num sized problem. In this case it's a little easier to express it as one because if you have one element, it's indeed already sorted. So what does it mean to merge two sorted halves? Well, let's actually consider this. I'm going to reuse some of these same numbers here. I'm going to put my 1, my 3, my 4, and my 6 on the left, and these together represent a list that is indeed sorted of size 4. And then I'm going to put 4 other numbers on the right there that are similarly sorted.",
    },
    {
      idx: 59,
      startMs: 6441169,
      endMs: 6479959,
      text: "As well, and by merging these two lists, I mean start at the left end of this list, and just decide one step at a time which number is the next smallest, and then I'm going to put it on the top shelf to make clear what is sorted. So if my left hand's pointing at this list, my right hand's pointing at there, which hand is obviously pointing to the smaller element, left or right. Like the right, so I'm going to grab this and I'm going to use a little more space up top here and put the 0 in place and then I'm going to point to the next element there. So my left hand has not moved yet. It's still pointing at the 1. My right hand is pointing at the 2, which number comes next clearly? Left, so I'm going to grab the 1 and put it up there and update where my left hand is pointing.",
    },
    {
      idx: 60,
      startMs: 6480040,
      endMs: 6516120,
      text: "So now I'm pointing at the 3 here and the 2 there. What comes next? Obviously the 2. What comes next? Obviously the 3. What comes next, obviously the 4. What comes next, obviously the 5, but notice my hands are not going back and forth, back and forth, back and forth like any of the algorithms thus far. I'm just taking baby steps, moving them only to the right, effectively pointing at for a final time each number once and only once. What comes next, 6, and now my left hand is done. What comes last, the number 7. What I just did is what I mean by merge the sorted halves.",
    },
    {
      idx: 61,
      startMs: 6516160,
      endMs: 6553640,
      text: "If you can somehow get into a scenario where you've got a small list sorted and another small list sorted, it's super easy now to merge them together using that left right approach, which I'll claim only takes end steps. Why? Because every time I asked you a question, I was taking one. Out of the problem, there's 8 bytes total. I asked you 8 questions or I would have if I verbalized them all. So it's N steps total to merge lists of that size. So what then is merge sort? Mergesort is really all three of these steps together, only one of which we've acted out, 2 of which are sort of cyclical in nature. They're recursive by design. So what does this mean?",
    },
    {
      idx: 62,
      startMs: 6553729,
      endMs: 6592149,
      text: "Well, let's start with this list of eight numbers, which is clearly out of order 63, 4152, 70 and let's apply mergesor to this set of numbers and I'll do it digitally here because it'll take forever to keep moving the numbers up and down physically. So let's move it to the top just to give ourselves a little bit more room and let me propose that we apply mergesort. What was the very first step in mergesort, at least that we highlighted, the juicy steps. What's the first step in mergesor? Sort the left half, yeah. And then the second step was going to be sort the right half and then the third step was going to be merge the sorted halves. So let's see what this means by actually acting it out on these numbers. So here's my 8 numbers.",
    },
    {
      idx: 63,
      startMs: 6592279,
      endMs: 6630350,
      text: "Let's go ahead and sort the left half. Well, the left half is obviously going to be the 4 numbers on the left, and I'm just going to pull them out just to draw our attention to them over here. Now I have a list of size 4, and the goal is to sort the left half. How do I sort a list of size 4? Uh, be what was yes, but just be more pedantic. Like how do I sort any list using merge sort? Sort the left half. So let's do just that. So of the list of size 4, how do I sort this? Well, I'm going to sort the left half. How do I sort a list of size 2? Sort the left half, right, well, I'm just gonna write the 6 here.",
    },
    {
      idx: 64,
      startMs: 6630479,
      endMs: 6667479,
      text: "How do I sort a list of size 1? I just don't. I'm done. That was the so-called base case where I just said return, like I'm done sorting the list. OK, so here I here's the story recap. So the left half, sort the left half, and I just finished sorting this. So what comes next? Sort the right half, which is this, and now I've sorted the left half of the left half of the left half, which is a big mouthful, but what do I do as a third and final step when sorting this list of size 2. Merge them. This part we know how to do.",
    },
    {
      idx: 65,
      startMs: 6667609,
      endMs: 6704930,
      text: "I point left and right, and I now take the smallest element first, which is the 3. Then I take the 6 and now this list of size 2 is sorted. So if you remind in your mind's eye what step are we on, well, we have now sorted the left half of the left half. So what comes after the left half is sorted? We sort the right half. So we're sort of rewinding in time, but that's OK. I'm keeping track of the steps in my mind. I want to now sort this list of size 2. How do you sort a list of size 2? Well, you divide it into a list of size 1. How do you sort this? You're done. You then take the other right half and you sort it. Done. Now you merge the two sorted halves.",
    },
    {
      idx: 66,
      startMs: 6704970,
      endMs: 6742990,
      text: "So I point at the 4 and the 1, obviously the one comes first, then the 4. Now I have sorted the right half of the uh the right half of the left half of the original numbers. What's the next step now that I have the left and right halves of this list of 4 sorted? Merge those, so same idea but fewer elements. I'm pointing at the 3 and the 1. Obviously the 1 comes now I'm pointing at the 3 and the 4. Obviously the 3 comes next, pointing at the 6 and the 4, the 4 comes next, and now the 6 comes last. Now I have sorted the left half and it's intentional that 1346 is the original arrangement of the lighted numbers I had on the shelves a moment ago.",
    },
    {
      idx: 67,
      startMs: 6743310,
      endMs: 6782660,
      text: "All right, it's a long story it seems, but what comes after you sorting the left half of the original list? You sort the right half. So let's put some, uh, put those numbers over here. How do I sort a list of size 4? Well, you sort the left half. How do you sort this thing of size 2? You sort the left half, you sort the right half, and now you merge those together. How do I now sort the right half of the right half? Well, I sort the left half, I sort the right half, and then I merge those together. Now, I have sorted the left half and the right half of the right half of the original elements. What's next? The merging, 025. And 7.",
    },
    {
      idx: 68,
      startMs: 6782910,
      endMs: 6820919,
      text: "Now we're exactly where we were originally with the lighted numbers. I've got 1346, the left half sorted, 02 57. The right half sorted. What's the third and final step? Merge those two halves, of course, 0123456. And 7 And hopefully even though there's a lot of words that come out of my mouth as acting this out, there wasn't a lot of back and forth. Like I definitely wasn't like walking back and forth physically and I also wasn't comparing the same numbers again and again. I was doing sort of different work at different conceptual levels, but that was like only what, like 3 levels total. It wasn't N levels on the board visually.",
    },
    {
      idx: 69,
      startMs: 6821370,
      endMs: 6860247,
      text: "So where does this get us with merge sort? Well, with mergesort, it would seem that we have an algorithm that I claim is doing a lot less work. The catch. Is that merge sort requires twice as much space just as we saw when I needed two shelves in order to merge those two lists. So how much less work is actually going to be possible? Well, let's consider sort of the analysis of the original list and how we might describe its its running time in terms of this big O notation. Hopefully it's not going to be as bad as n2d ultimately. So here are some like bread crumbs that if I hadn't kept updating the screen and deleting numbers once we move them around, here's sort of like traces of every.",
    },
    {
      idx: 70,
      startMs: 6860333,
      endMs: 6899920,
      text: "Bit of work that we did, we started up here, we did the left half, the left half of the left half, the right half of the right half, and then everything else in between, and you'll see that essentially I took a list of size 8 and I did 3 different passes through it at this conceptual level, at this conceptual level, and at this one. And each time I did that I had to merge elements together and if you kind of think about it here, I pointed at 4 elements here and 4 elements here and in total I pointed at 8 elements. So there was end steps here for merging and if you. Trust me, I'll claim that on this level conceptually there were also 8 steps. I wasn't merging lists of size 4, but I was merging 2 lists of size 2 over here and 2 more lists of size 2 over there.",
    },
    {
      idx: 71,
      startMs: 6900000,
      endMs: 6939430,
      text: "So if you add those up, those are in total steps or or merges if you will. And then down here this was kind of silly. I was, but I was merging ultimately 8 single lists altogether into the higher level of of conceptually. So from a list of size 8 we sort of had 3 levels of work. And on each level we did n steps, the merging. So whereas 3? Well, it turns out if you have 8 elements up here, the relationship between 8 and 3 is actually something formulaic, and we can describe it as log base 2 of n. Why? Because if n is 8, if you don't mind doing some logarithms here, logba 2 of 8 is the same thing as logbase 2 of 23 power.",
    },
    {
      idx: 72,
      startMs: 6939600,
      endMs: 6979069,
      text: "The log 2 and the 2 cancel itself out, which gives you exactly the number 3. That I sort of visualized with those traces on the screen, which is to say, irrespective of the specific value of N, the big O running time of merge sort is apparently not n squared, but it's log n times n or more conventionally n times log n. Because you're doing things, log n times technically based 2, but we don't care about that generally for big O notation. And indeed in big O notation we would say that merge sort is on the order of N log N. That's its big O running time sort of at the upper bound.",
    },
    {
      idx: 73,
      startMs: 6979109,
      endMs: 7018035,
      text: "What about the lower order bound? Well, there's no clever optimization in our current implementation as there was for bubble sort, and so it turns out the lower bound would be in omega of N log N and in theta, therefore, Of and log in as well because Big O and Omega are in fact in this case one and the same. And if we actually go back to our visualization from earlier, give me just a moment to pull that up here in our earlier implementation or an earlier demonstration of these algorithms, we had a side by side comparison of all of the comparisons, but here if I go ahead and randomize it and click Merge sort, you'll see a very different and clearly faster algorithm, even though the computer speed has not changed.",
    },
    {
      idx: 74,
      startMs: 7018669,
      endMs: 7049439,
      text: "But it's touching these elements so many fewer times it's wasting a lot less time because of this cleverness where it's instead dividing and conquering the problem into smaller and smaller and smaller pieces. And to give this a final flourish, since that was, yes, faster, but not necessarily obviously faster than other things that we've done, how might we actually compare these things side by side by side? Well, in our final moments together, let's go ahead and. Amatically and for no real reason, just dim the lights so that I'll hit play on a visualization that at the",
    },
  ],
  concepts: [
    {
      key: 'binary_search',
      name: 'Binary search',
      summary:
        'The locker/phone-book search algorithm checks the middle door and then searches the left or right half, which the lecture reframes as a recursive algorithm.',
      keyPoints: [
        {
          id: 'k1',
          text: 'It first checks if any doors are left (return false), then returns true if the middle door holds the number.',
          segs: [30],
        },
        {
          id: 'k2',
          text: 'If the number is less than the middle, search the left half; if greater, search the right half.',
          segs: [31],
        },
        {
          id: 'k3',
          text: "'Search the left/right half' is a recursive call on a smaller problem, so it eventually bottoms out.",
          segs: [32, 33],
        },
        {
          id: 'k4',
          text: "The week 0 phone-book version used 'go back to line 3' loops; condensing those lines yields a recursive version.",
          segs: [34, 35],
        },
      ],
      segs: [30, 31, 32, 33, 34, 35],
      salience: 0.4,
    },
    {
      key: 'asymptotic_notation',
      name: 'Big O, Ω and Θ',
      summary:
        'Big O gives an upper bound and Ω a lower bound on running time, keeping only the dominant term; Θ applies when both bounds are the same.',
      keyPoints: [
        {
          id: 'k1',
          text: 'Big O ignores lower-order terms and constants, keeping only the dominant term for large n (e.g., n²/2 − n/2 is O(n²)).',
          segs: [8, 9, 20],
        },
        {
          id: 'k2',
          text: 'Omega describes the lower bound, such as best-case behavior on already-sorted input.',
          segs: [10, 12, 22],
        },
        {
          id: 'k3',
          text: 'Theta can be used only when the Big O and Omega bounds are the same.',
          segs: [12, 23, 73],
        },
        {
          id: 'k4',
          text: "Constant-time steps like comparisons and swaps don't matter; nested loops determine the growth.",
          segs: [18, 19],
        },
      ],
      segs: [9, 10, 12, 20, 22, 23, 72, 73],
      salience: 0.75,
    },
    {
      key: 'selection_sort',
      name: 'Selection sort',
      summary:
        'Selection sort repeatedly finds the smallest element in the unsorted part of the array and swaps it into position i, taking Θ(n²) time.',
      keyPoints: [
        {
          id: 'k1',
          text: 'For i from 0 to n−1, find the smallest number between numbers[i] and numbers[n−1], then swap it with numbers[i].',
          segs: [1, 2],
        },
        {
          id: 'k2',
          text: 'It tracks only the current smallest element in a single variable, trading time for minimal memory.',
          segs: [3, 5, 6],
        },
        {
          id: 'k3',
          text: 'Comparisons total (n−1)+(n−2)+…+1 = n(n−1)/2, which is O(n²).',
          segs: [7, 8, 9],
        },
        {
          id: 'k4',
          text: 'It never checks whether the list is already sorted, so even its best case is Ω(n²), making it Θ(n²).',
          segs: [11, 12],
        },
      ],
      segs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 24, 25],
      salience: 0.75,
    },
    {
      key: 'bubble_sort',
      name: 'Bubble sort',
      summary:
        'Bubble sort repeatedly compares adjacent pairs and swaps those out of order so the largest values bubble to the end, running in O(n²) but Ω(n) with an early exit.',
      keyPoints: [
        {
          id: 'k1',
          text: 'Repeat n−1 times: for i from 0 to n−2, swap numbers[i] and numbers[i+1] if they are out of order.',
          segs: [13, 16, 17],
        },
        {
          id: 'k2',
          text: 'The inner loop stops at n−2 so that i+1 never goes past the end of the array.',
          segs: [14, 15],
        },
        {
          id: 'k3',
          text: 'The nested loops give (n−1)(n−1) = n² − 2n + 1 steps, which is O(n²).',
          segs: [18, 19, 20],
        },
        {
          id: 'k4',
          text: 'Quitting after a pass with no swaps makes the best case Ω(n), but the average and worst cases are still n².',
          segs: [21, 22, 23],
        },
      ],
      segs: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 26, 27],
      salience: 0.75,
    },
    {
      key: 'recursion',
      name: 'Recursion',
      summary:
        'A recursive function calls itself on a smaller version of the problem and needs a base case to stop, as shown by drawing a Mario pyramid recursively in C.',
      keyPoints: [
        {
          id: 'k1',
          text: 'A recursive function is defined in terms of itself, meaning it calls itself.',
          segs: [29],
        },
        {
          id: 'k2',
          text: 'To avoid infinite recursion, each call must work on a smaller problem, and a base case must return immediately.',
          segs: [30, 33, 34],
        },
        {
          id: 'k3',
          text: 'A pyramid of height n is a pyramid of height n−1 plus one more row; height 1 (or 0) is the base case.',
          segs: [37, 38, 47, 48],
        },
        {
          id: 'k4',
          text: "Without a base case, clang errors that all paths call the function itself; adding 'if n <= 0 return' fixes it.",
          segs: [50, 51, 52],
        },
        {
          id: 'k5',
          text: 'Each recursive call uses more memory, so very large inputs can crash where an iterative version would not.',
          segs: [55, 56],
        },
      ],
      segs: [29, 30, 32, 33, 34, 36, 37, 38, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
      salience: 0.85,
    },
    {
      key: 'merge_sort',
      name: 'Merge sort',
      summary:
        'Merge sort recursively sorts the left and right halves and then merges the sorted halves, running in Θ(n log n) at the cost of extra memory.',
      keyPoints: [
        {
          id: 'k1',
          text: 'The pseudocode is: sort the left half, sort the right half, merge the sorted halves, with a base case of one element being already sorted.',
          segs: [57, 58],
        },
        {
          id: 'k2',
          text: 'Merging uses two pointers that only move rightward, taking the smaller element each time, so merging takes n steps.',
          segs: [59, 60, 61],
        },
        {
          id: 'k3',
          text: 'Recursively halving 8 elements yields log₂8 = 3 levels, each doing n steps of merging, for O(n log n).',
          segs: [70, 71, 72],
        },
        {
          id: 'k4',
          text: 'It has no early-exit optimization, so it is Ω(n log n) and therefore Θ(n log n).',
          segs: [73],
        },
        {
          id: 'k5',
          text: 'It requires about twice as much space, trading memory for speed.',
          segs: [69],
        },
      ],
      segs: [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74],
      salience: 0.9,
    },
  ],
}
