import type { ItemFx } from './types'

/**
 * Verified practice bank for Lecture 4: Memory (F7.3).
 * GENERATED by scripts/seed-library.ts (Opus 5.5 extraction/drafting, GPT-6.1 Sol blind
 * verification). Do not edit by hand: change the script and re-run it.
 */
export const lecture4Items: ItemFx[] = [
  {
    concept: 'strings_as_char_pointers',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [0, 1, 4, 5, 8],
    publicPayload: {
      stem: 'A user types the word "cat" into a program that copies it into a new chunk of memory t using a for loop. How many bytes should be passed to malloc, and how far must the loop\'s index go?',
      options: [
        {
          id: 'a',
          text: '3 bytes; i goes from 0 while i < strlen(s)',
        },
        {
          id: 'b',
          text: '4 bytes; i goes from 0 while i <= strlen(s)',
        },
        {
          id: 'c',
          text: '4 bytes; i goes from 0 while i < strlen(s)',
        },
        {
          id: 'd',
          text: '3 bytes; i goes from 0 while i <= strlen(s)',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        'strlen("cat") is 3, but the string occupies 4 bytes because of the null terminator, so malloc(strlen(s) + 1) is needed. The loop must also copy that terminator, so it runs while i <= strlen(s), which iterates 4 times (0 through 3).',
    },
    distractorMeta: {
      a: {
        misconception: 'The real-world length of a string is all the memory it needs.',
        whyWrong:
          'This forgets the null terminator in both the allocation and the copy, so t is not a properly terminated string.',
      },
      c: {
        misconception:
          'Allocating room for the terminator is enough; the loop does not need to copy it.',
        whyWrong:
          'The extra byte is allocated but left as a garbage value, because i < 3 stops before copying the null character.',
      },
      d: {
        misconception: 'Copying the terminator is needed, but room for it is not.',
        whyWrong:
          'The loop writes 4 bytes into a 3-byte chunk, touching memory that was never allocated.',
      },
    },
    rubric: null,
    hints: [
      'Think about what is stored after the last visible character of every string.',
      'strlen counts only the visible characters; does the copy need one more byte, and does the loop need one more iteration?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'strings_as_char_pointers',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [7, 9, 3],
    publicPayload: {
      stem: 'A program has already done t = malloc(strlen(s) + 1); and now wants to copy the string s into t using the standard library instead of a loop. Which call is correct, and what happens to s if the program then capitalizes t[0]?',
      options: [
        {
          id: 'a',
          text: 'strcpy(s, t); s is also capitalized because both refer to the same characters',
        },
        {
          id: 'b',
          text: 'strcpy(s, t); s stays unchanged because t has its own memory',
        },
        {
          id: 'c',
          text: 'strcpy(t, s); s is also capitalized because both refer to the same characters',
        },
        {
          id: 'd',
          text: 'strcpy(t, s); s stays unchanged because t has its own memory',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        "strcpy takes the destination first and the source second, so strcpy(t, s) copies s's bytes into t. Because t points to its own separately malloc'd chunk, changing t[0] does not affect s.",
    },
    distractorMeta: {
      a: {
        misconception:
          'strcpy takes the source first, and a copy still shares memory with the original.',
        whyWrong:
          'The argument order is reversed, and after a real copy into a separate chunk, the two strings no longer share characters.',
      },
      b: {
        misconception: "strcpy's arguments go source, then destination.",
        whyWrong:
          'strcpy(s, t) would copy t (still garbage) over s; the destination must come first.',
      },
      c: {
        misconception:
          "Copying into malloc'd memory still leaves t and s sharing the same characters.",
        whyWrong:
          't holds the address of a different chunk, so capitalizing t[0] only changes that chunk.',
      },
    },
    rubric: null,
    hints: [
      'Recall the order in which strcpy expects its arguments, even if it feels backwards.',
      'Ask whether t and s hold the same address or two different addresses after malloc.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'strings_as_char_pointers',
    kind: 'spot_flaw',
    variant: 1,
    segs: [4, 5, 6, 8],
    publicPayload: {
      sentences: [
        'To copy s into a new string t, I call malloc(strlen(s) + 1) so there is room for every character plus the null terminator.',
        'I store strlen(s) in a variable n before the loop so the length is not recomputed on every iteration.',
        'My loop runs i from 0 while i < n, and that copies every character of s including the null terminator.',
        'Because t points to its own chunk of memory, capitalizing t[0] afterward leaves s unchanged.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'A loop with i < n stops before index n, which is where the null terminator lives, so the terminator is never copied.',
      correction:
        'The loop must run while i <= n (up to and including strlen(s)) so that the final iteration copies the null terminator.',
      explanation:
        'strlen returns only the visible length, so the terminator sits at index n. With i < n, t ends up with garbage in its last byte instead of a terminator. Using <= makes the loop iterate n + 1 times, copying the terminator too.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the bound error',
          description: 'States that i < n stops before the null terminator is copied.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Gives the fix',
          description:
            'Proposes using i <= n (or otherwise copying index n) rather than hard-coding a terminator position.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check exactly which indices the loop visits compared to where the terminator is stored.',
      'If strlen(s) is 3, at which index is the terminator, and does the loop reach it?',
    ],
    leakKeywords: ['<=', 'less than or equal', 'off by one', 'index n', 'terminator not copied'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'strings_as_char_pointers',
    kind: 'spot_flaw',
    variant: 2,
    segs: [0, 1, 7, 9],
    publicPayload: {
      sentences: [
        'A string in C is accessed through the address of its first character.',
        'To duplicate s, I first allocate strlen(s) + 1 bytes and store the returned address in t.',
        'Then I call strcpy(t, s), because strcpy takes the destination first and the source second.',
        'Since t now refers to a separate chunk holding its own copy of the characters, uppercasing t[0] does not change s.',
      ],
    },
    answerKey: {
      hasFlaw: false,
      flawSentenceIdx: null,
      flawSummary: null,
      correction: null,
      explanation:
        "Every sentence is correct: strings are reached via the address of the first char, the allocation includes a byte for the terminator, strcpy's order is destination then source, and modifying the separate copy leaves the original intact.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Recognizes correctness',
          description: 'Concludes that there is no flaw in the explanation.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Justifies key points',
          description:
            'Notes the +1 for the terminator and the destination-first order of strcpy as correct.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check the allocation size, the strcpy argument order, and the claim about s separately.',
      'Compare each claim against what strlen returns and what strcpy expects.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'correct',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'strings_as_char_pointers',
    kind: 'transfer',
    variant: 1,
    segs: [0, 1, 4, 5, 6, 7, 9],
    publicPayload: {
      prompt:
        "A program reads a user's name into s and wants a separate copy t that it can convert entirely to uppercase while keeping s exactly as typed. A classmate allocates the copy with t = malloc(strlen(s)); and copies with a loop running i from 0 while i < strlen(s). Explain what is wrong, and describe a correct way to make the copy (including one design improvement to the loop or an alternative to the loop).",
    },
    answerKey: {
      modelSolution:
        "The allocation is one byte short: strlen(s) gives only the visible characters, but the string also needs a byte for the null terminator, so it should be malloc(strlen(s) + 1). The loop also never copies the terminator, because i < strlen(s) stops just before it; it should run while i <= strlen(s). As a design improvement, store strlen(s) in a variable n before the loop so the length isn't recomputed every iteration, or replace the loop entirely with strcpy(t, s), destination first. Because t points to its own chunk, uppercasing t will not change s.",
      explanation:
        'This applies the length-plus-one rule, the inclusive loop bound for copying the terminator, the n optimization or strcpy, and the fact that a separate chunk keeps the original intact.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Allocation size',
          description: 'Identifies that malloc needs strlen(s) + 1 bytes for the null terminator.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Loop bound',
          description:
            'Explains the loop must include index strlen(s) (use <=) to copy the terminator.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Improvement',
          description:
            'Suggests caching strlen in n or using strcpy(t, s) with correct argument order.',
          max: 2,
        },
        {
          id: 'c4',
          label: 'Independence of copy',
          description: 'Notes that modifying t leaves s unchanged because t has its own memory.',
          max: 2,
        },
      ],
    },
    hints: [
      'Consider what every C string has at its end that strlen does not count.',
      'Check both the number of bytes requested and whether the last byte ever gets copied.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        "strlen(s) excludes the terminating '\\0', so the allocation is one byte too small for a C string and the loop omits the terminator. After checking that s is not NULL, cache size_t n = strlen(s), allocate t = malloc(n + 1), and check t for NULL before using it. Copy with i = 0 through i <= n, including the terminator; caching n avoids repeatedly calling strlen. Alternatively, use strcpy(t, s) after allocating enough space. Uppercase t's characters before its terminator; because t has separate storage, s stays unchanged. Free t when finished.",
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'malloc_and_null',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [10, 11, 13],
    publicPayload: {
      stem: 'Which statement correctly distinguishes NULL from NUL in C?',
      options: [
        {
          id: 'a',
          text: 'NULL is the special memory address 0x0 where nothing is stored; NUL is the single all-zero byte (backslash zero) that ends a string.',
        },
        {
          id: 'b',
          text: 'They are two spellings of the same thing: the zero byte at the end of every string.',
        },
        {
          id: 'c',
          text: 'NUL is the address 0x0 returned on error; NULL is the byte that terminates a string.',
        },
        {
          id: 'd',
          text: 'NULL is the first valid address malloc normally hands out; NUL marks the end of a string.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'a',
      explanation:
        'NUL is the string terminator, a single byte of eight zero bits written as backslash zero. NULL is a special address, 0x0, where nothing is supposed to live, used by functions like malloc and get_string to signal that something went wrong.',
    },
    distractorMeta: {
      b: {
        misconception: 'Because both are pronounced "null", they mean the same thing.',
        whyWrong:
          'One is a character value that ends strings; the other is a pointer value (an address) that signals an error.',
      },
      c: {
        misconception: 'The names are swapped.',
        whyWrong: 'NULL (two Ls) is the address 0x0; NUL (one L) is the backslash-zero terminator.',
      },
      d: {
        misconception: 'Address 0x0 is an ordinary usable location.',
        whyWrong:
          'Address 0x0 is deliberately never used, so it can serve as a sentinel meaning failure.',
      },
    },
    rubric: null,
    hints: [
      'One of these is a character, the other is a pointer.',
      'Which one would a function return when it cannot give you a valid address?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'a',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'malloc_and_null',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [20, 21],
    publicPayload: {
      stem: 'A programmer wants space for 3 integers and writes int *x = malloc(3 * sizeof(int)); instead of int *x = malloc(12);. Why is the sizeof version preferred?',
      options: [
        {
          id: 'a',
          text: "malloc's argument is a count of integers, so sizeof converts it into bytes for the compiler.",
        },
        {
          id: 'b',
          text: 'sizeof makes malloc initialize every integer to 0.',
        },
        {
          id: 'c',
          text: 'An int is not 4 bytes on every system, so asking for sizeof(int) keeps the code correct and portable.',
        },
        {
          id: 'd',
          text: 'Using sizeof guarantees malloc will never return NULL.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        'malloc takes a number of bytes. On most systems an int is 4 bytes, so 12 would usually work, but hard-coding it makes the code less portable. sizeof(int) asks the computer how big an int is on that specific system.',
    },
    distractorMeta: {
      a: {
        misconception: 'malloc counts elements rather than bytes.',
        whyWrong:
          "malloc's argument is already a number of bytes; sizeof is used to compute that number correctly.",
      },
      b: {
        misconception: 'sizeof affects the contents of the memory returned.',
        whyWrong:
          "malloc'd memory initially holds garbage values; sizeof only reports a type's size.",
      },
      d: {
        misconception: 'Requesting the right size prevents allocation failure.',
        whyWrong: 'malloc can still fail and return NULL, so the result must still be checked.',
      },
    },
    rubric: null,
    hints: [
      'Is the size of an int fixed by the C language on every machine?',
      'Think about what happens to the hard-coded 12 if the code runs on a system with a different int size.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'malloc_and_null',
    kind: 'spot_flaw',
    variant: 1,
    segs: [20, 30, 31, 32],
    publicPayload: {
      sentences: [
        'I include stdlib.h so the compiler knows about malloc and free.',
        'I call malloc(3 * sizeof(int)) and store the returned address in an int * named x.',
        'If x equals NULL, malloc could not give me memory, so I return 1 instead of touching it.',
        'Otherwise, x[1] = 73 means the same thing as *(x + 4), because each int is 4 bytes and pointer arithmetic counts bytes.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        'Pointer arithmetic on an int * moves in units of ints, not bytes, so x[1] is *(x + 1), not *(x + 4).',
      correction:
        'x[1] = 73 is the same as *(x + 1) = 73; the bracket notation is syntactic sugar for adding the index to the pointer and dereferencing.',
      explanation:
        "Bracket notation on malloc'd memory is just syntactic sugar: x[0], x[1], x[2] correspond to *x, *(x + 1), *(x + 2). Adding 1 to an int * already advances to the next int, so writing x + 4 would jump to the fifth int, beyond the 3 allocated.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the error',
          description: 'Recognizes that x[1] does not equal *(x + 4).',
          max: 2,
        },
        {
          id: 'c2',
          label: 'States the correct equivalence',
          description:
            'Explains that x[1] equals *(x + 1) because pointer arithmetic on an int * advances by whole ints.',
          max: 2,
        },
      ],
    },
    hints: [
      'Compare how the bracket form and the pointer form line up for index 0, 1 and 2.',
      'If x[0] is *x, what pointer expression corresponds to the very next element?',
    ],
    leakKeywords: ['x + 1', 'units of ints', 'not bytes', 'pointer arithmetic scales'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'malloc_and_null',
    kind: 'spot_flaw',
    variant: 2,
    segs: [10, 11, 12, 13, 14, 15],
    publicPayload: {
      sentences: [
        'get_string can return NULL if, for example, there is not enough memory for everything the user typed.',
        'NULL is the special address 0x0, where nothing is ever supposed to be stored.',
        'That means NULL is really the same thing as NUL, the backslash-zero byte at the end of every string.',
        'Before capitalizing t[0], I also check that strlen(s) > 0, because for an empty string t[0] is just the terminator.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'NULL and NUL are different: NULL is an address (0x0) signaling failure, while NUL is the single zero byte that terminates strings.',
      correction:
        'NULL is not the same as NUL; NULL is the pointer value 0x0 that functions return on error, whereas NUL is a character, the backslash-zero byte that ends a string.',
      explanation:
        'Despite similar names and pronunciation, NUL is a one-byte character of all zero bits used as a string terminator, and NULL is a special memory address used as a sentinel for errors from functions like get_string and malloc.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the conflation',
          description: 'States that NULL and NUL are not the same thing.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Distinguishes them correctly',
          description:
            'Explains NULL is an address (0x0) used for errors and NUL is the backslash-zero terminator byte.',
          max: 2,
        },
      ],
    },
    hints: [
      'Two terms that sound alike are not necessarily the same kind of thing.',
      'Is one of them a pointer and the other a character?',
    ],
    leakKeywords: [
      'NUL is a character',
      'different things',
      'terminator byte vs address',
      'not the same',
    ],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'malloc_and_null',
    kind: 'transfer',
    variant: 1,
    segs: [13, 20, 21, 30, 31, 32],
    publicPayload: {
      prompt:
        'A weather program asks the user how many temperature readings, n, they want to store, and then needs memory for n values of type double obtained from malloc. Describe how to write the malloc call so it works on any system, what the program should do immediately after calling malloc, and why that step matters.',
    },
    answerKey: {
      modelSolution:
        'Include stdlib.h and write double *temps = malloc(n * sizeof(double)); because malloc takes a number of bytes, and sizeof(double) gives the correct size on whatever system the code runs on instead of hard-coding a byte count. Immediately afterward, check whether temps == NULL. If it is, malloc could not provide the memory (for example, not enough is available), so the program should not touch it and should return 1 to signal an error. This matters because NULL is the special address 0x0 where nothing is stored, and writing through it would be invalid. Only if the check passes should the program store readings, using temps[i], which is equivalent to *(temps + i).',
      explanation:
        "This transfers malloc's byte-count interface, sizeof for portability, and the NULL check with return 1 to a new data type and situation.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Portable malloc call',
          description: 'Uses n * sizeof(double) and notes malloc takes bytes (and needs stdlib.h).',
          max: 2,
        },
        {
          id: 'c2',
          label: 'NULL check',
          description:
            'Checks if the returned pointer equals NULL and returns 1 (or otherwise stops) on failure.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Reasoning',
          description:
            'Explains that NULL means allocation failed and is address 0x0, so the memory must not be used.',
          max: 2,
        },
      ],
    },
    hints: [
      "Remember what unit malloc's argument is measured in, and that type sizes can vary.",
      'What special value does malloc return when it cannot give you memory?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        "For a valid, representable count n, use double *readings = malloc(n * sizeof(double)); (equivalently, malloc(n * sizeof *readings)). Immediately check whether readings == NULL. If so, report or handle the allocation failure, such as returning an error, rather than accessing the memory. sizeof supplies the system's actual double size, and the NULL check prevents accessing an invalid pointer when allocation fails.",
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'memory_leaks',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [22, 23, 25, 26],
    publicPayload: {
      stem: 'A program runs int *x = malloc(3 * sizeof(int)); and then x[1] = 72; x[2] = 73; x[3] = 33;. On a system where an int is 4 bytes, which Valgrind complaint does the line x[3] = 33; most directly cause?',
      options: [
        {
          id: 'a',
          text: 'Definitely lost 12 bytes in 1 block',
        },
        {
          id: 'b',
          text: 'Invalid read of size 12',
        },
        {
          id: 'c',
          text: 'Invalid write of size 4',
        },
        {
          id: 'd',
          text: 'All heap blocks were freed, no leaks are possible',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        'Allocating 3 ints gives valid indices 0, 1 and 2. Assigning to x[3] changes a value just past the end of the allocated chunk. Valgrind reports that as an invalid write, and its size is 4 because one int is 4 bytes.',
    },
    distractorMeta: {
      a: {
        misconception: 'Confusing an out-of-bounds write with a memory leak',
        whyWrong:
          '"Definitely lost 12 bytes" comes from never freeing the 12-byte allocation, not from writing past its end.',
      },
      b: {
        misconception: 'Mixing up reads with writes and assuming the size is the whole allocation',
        whyWrong:
          'Assigning a value is a write, not a read, and the size reported is that of one int (4 bytes), not the full 12-byte block.',
      },
      d: {
        misconception: 'Thinking that a program which runs without crashing must be memory-safe',
        whyWrong:
          'The out-of-bounds write is a latent bug that Valgrind still flags even though the program appeared to run fine.',
      },
    },
    rubric: null,
    hints: [
      'Think about which indices are valid for a chunk holding exactly 3 ints.',
      'Is x[3] = 33 changing a value or accessing one, and how many bytes does one int take up?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'memory_leaks',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [15, 16, 18, 19],
    publicPayload: {
      stem: 'A CS50 program reads string s = get_string("s: "); and then does char *t = malloc(strlen(s) + 1); and copies s into t. Following the course\'s rule of thumb, which memory must the programmer free before the program ends?',
      options: [
        {
          id: 'a',
          text: 'Both s and t, because every string lives in memory that must be freed',
        },
        {
          id: 'b',
          text: 'Only t, because the programmer called malloc for it',
        },
        {
          id: 'c',
          text: 'Only s, because get_string allocated it behind the scenes',
        },
        {
          id: 'd',
          text: 'Neither, because the operating system reclaims all memory when the program ends',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        "The rule of thumb is: if you malloc'd it, you must free it. Memory that CS50's get_string allocated is freed automatically by its implementation. So only t needs free(t).",
    },
    distractorMeta: {
      a: {
        misconception:
          'Believing the programmer must free all string memory, regardless of who allocated it',
        whyWrong:
          "CS50's get_string automatically frees the memory it handed out, so the programmer should not free s.",
      },
      c: {
        misconception: 'Reversing who is responsible for which allocation',
        whyWrong:
          "get_string's memory is handled for you. The memory you got yourself with malloc (t) is the memory you must free.",
      },
      d: {
        misconception: 'Treating automatic reclamation at exit as permission to skip free',
        whyWrong:
          'Short programs may get away with this, but in long-running programs unfreed memory leaks. Valgrind would still report t as lost, and correct practice is to free it.',
      },
    },
    rubric: null,
    hints: [
      'Ask who actually requested each chunk of memory.',
      'Recall the short rule about malloc and free, and the special treatment CS50 gives get_string.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'memory_leaks',
    kind: 'spot_flaw',
    variant: 1,
    segs: [27, 28, 29, 33],
    publicPayload: {
      sentences: [
        'In my program I called malloc(3 * sizeof(int)) on line 8 and stored the address in x, but I never called free.',
        'When I ran valgrind ./memory, the leak summary said 12 bytes were definitely lost in 1 block, which matches 3 ints of 4 bytes each.',
        'Valgrind also printed a line number with that leak, and that line is where the program should have called free, so that is the line to fix.',
        'After I added free(x) at the end of main, Valgrind reported that all heap blocks were freed and no leaks were possible.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        "Valgrind's leak report points to the line where the leaked memory was allocated, not to the spot where free should go.",
      correction:
        'The line number Valgrind gives for a leak is the line where the memory was allocated (the malloc on line 8). That tells you which allocation still needs a matching free later in the program.',
      explanation:
        'Valgrind cannot know where you intended to free memory. It records where the lost block was allocated and points you there as a bread crumb. You then add free for that allocation once you are done with it.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flawed sentence',
          description: "Points to the claim about what Valgrind's line number means.",
          max: 2,
        },
        {
          id: 'c2',
          label: 'States the correct meaning',
          description:
            'Explains that the reported line is where the leaked memory was allocated (the malloc call).',
          max: 2,
        },
      ],
    },
    hints: [
      'Consider what information Valgrind actually has about a block of memory that was never returned.',
      'Is there any way Valgrind could know where you meant to call free?',
    ],
    leakKeywords: ['allocated', 'allocation line', 'malloc line', 'source of the leak'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'memory_leaks',
    kind: 'spot_flaw',
    variant: 2,
    segs: [15, 16, 17, 18, 19],
    publicPayload: {
      sentences: [
        'I used get_string to read s and then malloc(strlen(s) + 1) to get space for a copy called t.',
        "Because I malloc'd t myself, I must call free(t) once I am completely done with it.",
        "I do not need to free s, because CS50's get_string automatically frees the memory it allocated for me.",
        'If a long-running program like a server repeatedly skipped free(t), the leaked memory would add up and the program could get slower and slower.',
      ],
    },
    answerKey: {
      hasFlaw: false,
      flawSentenceIdx: null,
      flawSummary: null,
      correction: null,
      explanation:
        "Every sentence is correct. You must free what you malloc. CS50's get_string frees its own memory. Unfreed memory in long-running programs is a memory leak that can make the program get slower and slower.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Recognizes no flaw',
          description: 'Correctly judges that every sentence is accurate.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Justifies with the rule of thumb',
          description:
            "Notes that whoever mallocs memory must free it and that get_string's memory is handled automatically.",
          max: 2,
        },
      ],
    },
    hints: [
      'Check each claim about who is responsible for freeing which memory.',
      'Recall the rule of thumb about malloc and free, and how get_string is treated.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'correct',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'memory_leaks',
    kind: 'transfer',
    variant: 1,
    segs: [15, 16, 17, 27, 28, 29, 33],
    publicPayload: {
      prompt:
        "A server program handles 1000 requests in a loop. On each iteration it runs char *buf = malloc(100); , checks that buf is not NULL, uses buf to build a reply, and moves on to the next request without ever calling free. Explain what problem this causes, what kind of message Valgrind's leak summary would likely show and which line it would point to, and how to fix the code.",
    },
    answerKey: {
      modelSolution:
        "Each iteration allocates 100 bytes and never returns them, so the program has a memory leak. Over 1000 requests it loses about 100,000 bytes. In a server that runs indefinitely, the leaked memory keeps growing and the program can get slower and slower. Valgrind's leak summary would report memory definitely lost, roughly 100,000 bytes in 1000 blocks. It would point to the line containing the malloc call, since that is where the lost memory was allocated. The fix is to call free(buf) at the end of each iteration, once buf is no longer needed. After that change, Valgrind should report that all heap blocks were freed and there are no errors.",
      explanation:
        "This applies the rule that malloc'd memory must be freed. It also uses the fact that Valgrind's leak report totals the lost bytes and points to the allocation site, plus the effect leaks have on long-running programs.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Diagnoses the leak',
          description:
            'Identifies the missing free as a memory leak whose cost grows with each request and can slow a long-running program.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Predicts Valgrind output',
          description:
            'Says Valgrind would report bytes definitely lost (about 100 times 1000) and point to the malloc line.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Correct fix',
          description:
            'Calls free(buf) once per iteration after buf is no longer needed, not just once at the end of the program.',
          max: 2,
        },
      ],
    },
    hints: [
      'Count how much memory is requested in total and how much is ever given back.',
      'Remember which line Valgrind associates with a lost block, and where free must go so that each allocation is returned.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        "This causes a memory leak: each successful allocation remains allocated after the request finishes. If all 1000 allocations succeed, 100,000 bytes are leaked. Valgrind would likely report 'definitely lost: 100,000 bytes in 1,000 blocks' and identify the malloc(100) line as the allocation source. Call free(buf) after the reply no longer needs the buffer, before moving to the next request, including on error paths after successful allocation.",
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pointers',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [38, 39, 40, 44, 46],
    publicPayload: {
      stem: 'Consider this code: int *x; int *y; x = malloc(sizeof(int)); *x = 42; *y = 13;. Which statement is the dangerous one?',
      options: [
        {
          id: 'a',
          text: 'int *x; because declaring a pointer without an equal sign is illegal',
        },
        {
          id: 'b',
          text: 'x = malloc(sizeof(int)); because malloc can only allocate arrays',
        },
        {
          id: 'c',
          text: '*x = 42; because x has not been given a pointee',
        },
        {
          id: 'd',
          text: '*y = 13; because y was never set to point anywhere',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        'Declaring y does not give it a pointee. Setting that up is a separate step. Because y was never assigned, it holds a garbage address. Dereferencing y with *y = 13 tries to store 13 at some random location, and bad things happen.',
    },
    distractorMeta: {
      a: {
        misconception: 'Thinking a pointer must be initialized when it is declared',
        whyWrong:
          'Declaring a pointer without assigning it is fine. You just must assign it a valid value before you dereference it.',
      },
      b: {
        misconception: 'Believing malloc only works for arrays',
        whyWrong:
          'malloc takes a number of bytes and can allocate space for a single int. That gives x a valid pointee.',
      },
      c: {
        misconception: 'Overlooking that the malloc call gave x a pointee',
        whyWrong:
          'x was assigned the address returned by malloc, so *x = 42 validly stores 42 in that memory (assuming malloc did not return NULL).',
      },
    },
    rubric: null,
    hints: [
      'For each pointer, check whether it was ever assigned an address before it was dereferenced.',
      'One pointer received an address from malloc. What value does the other one hold?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pointers',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [38, 39, 42, 43, 44, 45, 46],
    publicPayload: {
      stem: 'Assume malloc succeeds and returns a valid address. What does this C fragment print?\n\nint *x = malloc(sizeof(int));\nint *y;\n*x = 42;\ny = x;\n*y = 13;\nprintf("%i\\n", *x);',
      options: [
        {
          id: 'a',
          text: '42, because y = x copied the value 42 into a separate integer that belongs to y',
        },
        {
          id: 'b',
          text: 'Unpredictable output, because y never got its own memory from malloc, so dereferencing it is invalid',
        },
        {
          id: 'c',
          text: '13, because after y = x both pointers refer to the same integer',
        },
        {
          id: 'd',
          text: '42, because *y = 13 changes where y points rather than changing any stored integer',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        'y = x is pointer assignment. It copies the address, not the integer, so x and y share one pointee. *y = 13 goes to that shared address and stores 13 there, which overwrites the 42. Reading *x then gives 13. y was declared uninitialized, but it was given a valid address before it was dereferenced, so the dereference is safe.',
    },
    distractorMeta: {
      a: {
        misconception: 'Believes pointer assignment copies the pointed-to data into new storage.',
        whyWrong:
          'y = x copies only the address. No new integer is created, so both pointers share the one pointee.',
      },
      b: {
        misconception: 'Believes every pointer needs its own malloc before it can be dereferenced.',
        whyWrong:
          'A pointer only needs to hold a valid address before it is dereferenced. y = x gives y the valid address that malloc returned for x.',
      },
      d: {
        misconception: 'Confuses dereferencing (*y = ...) with reassigning the pointer itself.',
        whyWrong:
          'The star on the left of the assignment means go to the address in y and store a value there. The pointer itself does not change.',
      },
    },
    rubric: null,
    hints: [
      'Think about what is actually copied when one pointer variable is assigned to another.',
      'After y = x, how many integers exist in memory, and where do x and y each lead?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pointers',
    kind: 'spot_flaw',
    variant: 1,
    segs: [38, 39, 40, 42, 44],
    publicPayload: {
      sentences: [
        'The declaration int *x; int *y; creates two variables that can each store the address of an int.',
        'Declaring y this way also sets aside an int for y to point to, so *y = 13 is safe right away.',
        'The statement x = malloc(sizeof(int)); gives x a pointee, and *x = 42 goes to that address and stores 42 there.',
        'Until a pointer is given a valid address, it holds a garbage value, just like any uninitialized variable.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 1,
      flawSummary:
        'Declaring a pointer does not allocate a pointee, so dereferencing y before assigning it is unsafe.',
      correction:
        'Declaring y only creates the pointer. Setting up a pointee is a separate step, done with malloc or by assigning an existing address such as y = x. Until then, *y = 13 dereferences a garbage address.',
      explanation:
        'Pointers and pointees are separate. A freshly declared pointer holds a garbage address. Writing through it sends the value to some random location, and bad things happen.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flawed sentence',
          description: 'Points to the claim that declaring y provides a pointee.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Explains the correct behavior',
          description:
            'States that the pointee must be set up separately and that dereferencing an uninitialized pointer follows a garbage address.',
          max: 2,
        },
      ],
    },
    hints: [
      'Think about which steps are needed before a pointer can be safely dereferenced.',
      'Does writing int *y; involve any call that obtains memory for an int?',
    ],
    leakKeywords: ['pointee', 'separate step', 'uninitialized pointer', 'garbage address'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pointers',
    kind: 'spot_flaw',
    variant: 2,
    segs: [44, 45, 46],
    publicPayload: {
      sentences: [
        'After x = malloc(sizeof(int)); and *x = 42;, x points to a 4-byte chunk of memory holding 42.',
        'To give y something to point to, I can write y = x;, which is pointer assignment.',
        'Pointer assignment makes a fresh copy of the 42 for y, so x and y now point to two separate ints.',
        'After that, *y = 13 is valid because y now holds a valid address.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'Pointer assignment copies only the address, so x and y share one pointee and no data is copied.',
      correction:
        'y = x copies the address in x into y, so both pointers point to the same single int. No copy of 42 is made, and storing 13 through y changes the value x sees too.',
      explanation:
        'Pointer assignment does not touch the pointees. It just makes one pointer point where another does. That is why, after *y = 13, the shared int holds 13 for both x and y.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flawed sentence',
          description: 'Points to the claim that y = x creates a separate copy of the int.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Describes sharing correctly',
          description:
            'Explains that both pointers share one pointee, so a change through y is visible through x.',
          max: 2,
        },
      ],
    },
    hints: [
      'Consider what value is actually stored inside a pointer variable.',
      'After y = x, how many ints exist in memory?',
    ],
    leakKeywords: ['share', 'same pointee', 'copies the address', 'both see 13'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pointers',
    kind: 'transfer',
    variant: 1,
    segs: [38, 39, 40, 42, 44, 46],
    publicPayload: {
      prompt:
        'A student writes int *count; *count = 0; at the start of main, intending to use count as a counter that other code updates through the pointer. Explain what is wrong with this code and describe two different ways to fix it so that *count = 0 becomes safe.',
    },
    answerKey: {
      modelSolution:
        'Declaring int *count only creates the pointer. It does not give count a pointee, so count holds a garbage address. The statement *count = 0 goes to that random address and tries to store 0 there, which can crash the program or corrupt memory. The first fix is to allocate a pointee: write count = malloc(sizeof(int));, check that count is not NULL, then do *count = 0;, and later call free(count). The second fix is to point count at an existing variable: declare int n; and assign count = &n;. Then *count = 0 stores 0 in n.',
      explanation:
        'This applies the ideas that a pointee is set up separately from its pointer, that dereferencing an uninitialized pointer follows a garbage address, and that a pointer must be given a valid address before *p is used.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the bug',
          description:
            'Explains that count is uninitialized and holds a garbage address, so dereferencing it is unsafe.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Fix with malloc',
          description: 'Allocates an int with malloc, checks for NULL, and frees the memory later.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Fix by pointing to an existing variable',
          description:
            'Assigns count the address of an existing int, such as count = &n, before dereferencing.',
          max: 2,
        },
      ],
    },
    hints: [
      'Ask what address count holds immediately after it is declared.',
      'A pointer can get a valid address either from new memory or from a variable that already exists.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        'Declaring count creates a pointer variable but neither initializes its address nor creates an int pointee. Dereferencing that uninitialized pointer has undefined behavior. Two fixes are: (1) create a local int storage; then set int *count = &storage; before *count = 0;, keeping storage alive while the pointer is used; or (2) use int *count = malloc(sizeof *count);, check count != NULL before *count = 0;, and free(count) when finished.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pass_by_reference',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [58, 59, 60, 67, 68, 69],
    publicPayload: {
      stem: "A program sets int x = 1 and int y = 2, then calls swap(x, y), where swap is declared as void swap(int a, int b) and correctly exchanges a and b using a temp variable. Afterward, main prints x is 1, y is 2. Why weren't x and y swapped?",
      options: [
        {
          id: 'a',
          text: 'The swap function forgot to use a temporary variable, so both a and b ended up with the same value.',
        },
        {
          id: 'b',
          text: 'The compiler optimized the call away because swap returns void.',
        },
        {
          id: 'c',
          text: 'C passes arguments by value, so a and b are copies of x and y; swapping the copies leaves the originals untouched.',
        },
        {
          id: 'd',
          text: 'x and y are global variables, so swap cannot see them.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        "In C, arguments are passed by value: a becomes a copy of x and b a copy of y in swap's own frame. The function really does swap a and b, but x and y in main are never touched.",
    },
    distractorMeta: {
      a: {
        misconception: 'Assumes the bug is in the swap logic.',
        whyWrong:
          'The stem says swap uses a temp variable and correctly exchanges a and b; the problem is that only the copies change.',
      },
      b: {
        misconception: 'Thinks void functions may be skipped.',
        whyWrong:
          'A void function still runs; it simply returns no value. The swap happens, just on the copies.',
      },
      d: {
        misconception: 'Confuses this with a problem of global versus local variables.',
        whyWrong:
          'x and y are local to main here. The issue is pass-by-value copying, not visibility of globals.',
      },
    },
    rubric: null,
    hints: [
      'Think about what a and b actually are when swap starts running.',
      'Does swap receive x and y themselves, or something else?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pass_by_reference',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [71, 72, 73],
    publicPayload: {
      stem: 'In the corrected function void swap(int *a, int *b), the first line of the body is int tmp = *a; What does the * in *a mean on that line?',
      options: [
        {
          id: 'a',
          text: 'Multiply tmp by a.',
        },
        {
          id: 'b',
          text: 'Declare a new pointer variable named a.',
        },
        {
          id: 'c',
          text: 'Take the address of a.',
        },
        {
          id: 'd',
          text: 'Go to the address stored in a and use the value found there.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        "When * appears with no data type immediately to its left, it is the dereference operator: it means go to that address. So tmp gets the int stored at the address in a, which is x's value. The * in int *a in the parameter list, by contrast, declares a as a pointer.",
    },
    distractorMeta: {
      a: {
        misconception: 'Reads * as multiplication in every context.',
        whyWrong:
          'Here * is a unary operator applied to a pointer, so it means dereference. Multiplication requires two operands.',
      },
      b: {
        misconception: 'Confuses dereferencing with pointer declaration.',
        whyWrong:
          'A declaration puts a type to the left of the *, as in int *a in the parameter list. In the expression *a, the * means go to that address.',
      },
      c: {
        misconception: 'Confuses * with &.',
        whyWrong: '& gets an address. * follows an address to the value stored there.',
      },
    },
    rubric: null,
    hints: [
      'The star means different things in different contexts in C.',
      'Is there a data type directly to the left of this star?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pass_by_reference',
    kind: 'spot_flaw',
    variant: 1,
    segs: [60, 69, 70, 71, 72],
    publicPayload: {
      sentences: [
        'In the naive version, swap(int a, int b) receives copies of x and y because C passes arguments by value.',
        "Inside swap, a temporary variable holds a's value so that it isn't lost when a is overwritten with b.",
        'When swap returns, a and b have been exchanged, but x and y in main still hold 1 and 2.',
        'To fix it, we can keep the parameters as int a and int b and simply write *a and *b in the body, since putting stars at the use sites is enough to reach the original variables.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        "The parameters must become pointers (int *a, int *b), and main must pass the addresses of x and y. You can't dereference plain ints that are only copies.",
      correction:
        'To fix it, declare swap(int *a, int *b) and call it with the addresses of x and y. Then *a and *b in the body go to those addresses and change the originals.',
      explanation:
        'Passing by reference requires both pieces: the parameters must be declared as addresses of ints, and the caller must pass the addresses of x and y. Writing stars inside the body alone cannot work, because a and b would still just be int copies.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies flawed sentence',
          description: 'Points to the claim that stars at the use sites alone are enough.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct fix',
          description:
            'States that the parameters become int * and that the addresses of x and y are passed in.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check whether every step of the proposed fix actually changes what swap receives.',
      'What type would a and b need to be for *a to make sense?',
    ],
    leakKeywords: ['int *a', 'address of x', 'parameter type', 'pointer parameter'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pass_by_reference',
    kind: 'spot_flaw',
    variant: 2,
    segs: [53, 54, 70, 71, 72, 73],
    publicPayload: {
      sentences: [
        'Swapping two values needs a temporary place to hold one of them, just as swapping two liquids needs an empty glass.',
        'In the fixed swap, a and b are declared as int *, so they hold the addresses of x and y instead of copies of their values.',
        'The line int tmp = *a; goes to the address in a and copies the 1 stored in x into tmp.',
        "Then *a = *b; puts the 2 from y into x, and *b = tmp; puts the 1 into y, so main's variables really are swapped.",
        'The star here does double duty: in the parameter list it declares pointers, and in the body it dereferences them.',
      ],
    },
    answerKey: {
      hasFlaw: false,
      flawSentenceIdx: null,
      flawSummary: null,
      correction: null,
      explanation:
        'Every sentence is accurate. A temp variable is required to swap. Pointer parameters receive the addresses of x and y. Dereferencing reads and writes the original variables. And * is overloaded: it declares a pointer in one context and dereferences in another.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Recognizes correctness',
          description: 'Concludes there is no flaw.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Justification',
          description: 'Briefly explains why dereferencing the address parameters changes x and y.',
          max: 2,
        },
      ],
    },
    hints: [
      'Trace the values of x, y and tmp through each line.',
      'Check what * means in the parameter list compared with the body.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'correct',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'pass_by_reference',
    kind: 'transfer',
    variant: 1,
    segs: [60, 69, 70, 71, 72],
    publicPayload: {
      prompt:
        'A student writes void add_bonus(int score) { score = score + 10; } and calls add_bonus(grade) in main, where grade is 80. Afterward, main prints 80. Explain why, then rewrite the function header, the body line, and the call so that grade becomes 90.',
    },
    answerKey: {
      modelSolution:
        "C passes arguments by value, so score is a copy of grade stored in add_bonus's own frame. Adding 10 changes only that copy, and it disappears when the function returns. To fix it, pass by reference: void add_bonus(int *score) { *score = *score + 10; } and call add_bonus(&grade). Now score holds grade's address, and *score goes to that address, so grade itself becomes 90.",
      explanation:
        "This applies the swap lesson to a single variable. Changing a caller's variable requires passing its address and dereferencing it inside the function.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Explains pass by value',
          description: 'States that score is a copy, so grade is unchanged.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Pointer parameter and dereference',
          description: 'Uses an int * parameter and *score in the body.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Passes the address',
          description: 'Calls the function with &grade.',
          max: 2,
        },
      ],
    },
    hints: [
      'This is the same problem as the broken swap, just with one variable.',
      'The function needs to know where grade lives, not just what it holds.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        'C passes arguments by value, so score is a copy of grade. Changing score leaves grade unchanged. Use the header void add_bonus(int *score), the body line *score = *score + 10;, and the call add_bonus(&grade);. Dereferencing the pointer updates grade itself from 80 to 90.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'stack_and_heap',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [62, 63, 64],
    publicPayload: {
      stem: "In the conventional picture of a program's memory, which region does malloc allocate from, and which way does that region grow?",
      options: [
        {
          id: 'a',
          text: 'The stack, which grows upward.',
        },
        {
          id: 'b',
          text: 'The heap, which grows downward, just below the globals.',
        },
        {
          id: 'c',
          text: 'The machine-code region at the top of memory.',
        },
        {
          id: 'd',
          text: 'The heap, which grows upward from the bottom of memory.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        'Machine code sits at the top of memory, with global variables just below it. Below those is the heap, which malloc uses and which grows downward. The stack, used for function frames and local variables, grows upward from the bottom.',
    },
    distractorMeta: {
      a: {
        misconception: 'Mixes up the heap and the stack.',
        whyWrong:
          'The stack holds local variables and function frames. malloc allocates from the heap.',
      },
      c: {
        misconception: "Thinks dynamic memory comes from the area holding the program's code.",
        whyWrong:
          "That region holds the program's compiled zeros and ones. malloc does not allocate from it.",
      },
      d: {
        misconception: 'Gets the region right but the direction wrong.',
        whyWrong:
          'In this model it is the stack that grows upward from the bottom; the heap grows downward.',
      },
    },
    rubric: null,
    hints: [
      'The two big regions grow toward each other.',
      "malloc's region sits just below the global variables.",
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'stack_and_heap',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [65, 66, 74],
    publicPayload: {
      stem: "main calls a function swap, which has parameters a and b and a local variable temp. Which statement best describes what happens to swap's memory on the stack?",
      options: [
        {
          id: 'a',
          text: "swap gets its own frame just above main's frame; when swap returns, that frame is conceptually freed, but its old values remain as garbage that later calls may reuse.",
        },
        {
          id: 'b',
          text: "swap's variables are stored inside main's frame, so they persist until main ends.",
        },
        {
          id: 'c',
          text: "swap's frame is allocated on the heap by malloc and must be freed by the programmer.",
        },
        {
          id: 'd',
          text: 'When swap returns, the computer overwrites its frame with zeros so no old values remain.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'a',
      explanation:
        "Each function call gets its own frame on the stack, placed above the caller's frame. When the function returns, that memory becomes available for reuse, but the zeros and ones stay behind. Those leftovers are why garbage values appear.",
    },
    distractorMeta: {
      b: {
        misconception: "Thinks a called function shares its caller's frame.",
        whyWrong:
          'Each call gets its own separate frame, which is why a and b are distinct copies of x and y.',
      },
      c: {
        misconception: 'Confuses function frames with dynamic allocation.',
        whyWrong:
          'Frames live on the stack and are handled automatically. Only memory you get from malloc must be freed.',
      },
      d: {
        misconception: 'Believes returned frames are wiped clean.',
        whyWrong:
          'The bits remain in memory; that leftover data is exactly what garbage values are.',
      },
    },
    rubric: null,
    hints: [
      'Think about where garbage values come from.',
      'Is memory erased when a function finishes, or just marked reusable?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'a',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'stack_and_heap',
    kind: 'spot_flaw',
    variant: 1,
    segs: [65, 66, 74],
    publicPayload: {
      sentences: [
        "When main runs, its local variables, such as x and y, live in main's frame near the bottom of the stack.",
        "When main calls swap, swap gets the next frame above main's, holding its parameters a and b and its local variable temp.",
        'When swap returns, the computer erases that frame by setting all of its bytes to zero, so no trace of a, b or temp remains.',
        'That same memory can then be reused by the next function call.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'Returning from a function does not zero out its frame. The old bits remain, which is the source of garbage values.',
      correction:
        'When swap returns, its frame is conceptually freed, but the zeros and ones are still there. The memory is merely available for reuse, which is why garbage values show up later.',
      explanation:
        'A frame that has gone away is just marked reusable; its contents are not wiped. Leftover values from earlier calls are exactly the garbage values you see in uninitialized variables.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies flawed sentence',
          description: 'Points to the claim that the frame is zeroed out.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct explanation',
          description:
            'Explains that the old values remain as garbage and the memory is simply reused.',
          max: 2,
        },
      ],
    },
    hints: [
      'Think about where garbage values come from.',
      'Does freeing a frame actually change the bits stored in it?',
    ],
    leakKeywords: ['garbage values', 'remnants', 'not erased', 'zeros and ones still there'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'stack_and_heap',
    kind: 'spot_flaw',
    variant: 2,
    segs: [61, 62, 63, 64, 65, 66],
    publicPayload: {
      sentences: [
        'When a program starts, its machine code is copied from persistent storage into RAM, and in the usual picture it sits at the top of memory.',
        'Any global variables, meaning variables defined outside of main and other functions, are placed just below that machine code.',
        'Below the globals is the heap, the region malloc allocates from, and it grows downward as more memory is requested.',
        'At the other end is the stack, which holds local variables and function calls, and it grows upward like trays stacked in a cafeteria.',
        'When a function returns, the computer wipes its frame back to all zeros so that the next function call starts with clean memory.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 4,
      flawSummary:
        "A returning function's frame is not cleared. It is only conceptually freed for reuse, and its old bits stay behind.",
      correction:
        'When a function returns, its frame is conceptually freed and can be reused by later calls, but the zeros and ones are left in place. Those leftovers are why uninitialized variables show garbage values.',
      explanation:
        'Sentences 0–3 correctly describe the layout: machine code at the top, globals just below it, the heap that malloc uses growing downward, and the stack of locals and function calls growing upward. Sentence 4 is wrong. Memory from a finished frame is not zeroed. It is simply made available again with its old contents still there. That is exactly why later function calls can see garbage values, which are remnants of earlier use.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flawed claim',
          description:
            "Points to the claim that a returned function's frame is wiped to zeros as the error.",
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct behavior',
          description:
            'Explains that the frame is only conceptually freed for reuse and the old values remain, which produces garbage values in later frames.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check each claim about what physically happens to memory, not just where each region sits.',
      'If memory were always cleaned up after a function returned, where would garbage values come from?',
    ],
    leakKeywords: ['garbage values', 'remnants', 'wiped', 'zeros', 'reuse'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'stack_and_heap',
    kind: 'transfer',
    variant: 1,
    segs: [15, 16, 19, 63, 64, 65, 66],
    publicPayload: {
      prompt:
        'main calls a function build(), and build calls malloc to get 40 bytes, storing the address in a local pointer p. build returns that address to main and then finishes. Describe where p and the 40 bytes each live in memory, and explain what happens to each when build returns.',
    },
    answerKey: {
      modelSolution:
        "p is a local variable, so it lives in build's frame on the stack, just above main's frame. The 40 bytes come from malloc, so they live in the heap. When build returns, its stack frame is conceptually freed: p's bytes remain as garbage, and that memory can be reused by later calls. The heap memory is not affected by the return. Because build returned the address, main can still use those 40 bytes, and they stay allocated until someone calls free on them. Otherwise the program leaks memory.",
      explanation:
        'Stack frames come and go automatically with function calls, but heap memory from malloc persists until it is freed. Keeping these lifetimes straight explains both garbage values and memory leaks.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Locates p',
          description: "Places p in build's stack frame.",
          max: 2,
        },
        {
          id: 'c2',
          label: 'Locates the allocation',
          description: 'Places the 40 bytes in the heap.',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Lifetimes',
          description:
            'Explains that the frame goes away on return, leaving garbage, while the heap memory persists until it is freed.',
          max: 2,
        },
      ],
    },
    hints: [
      'Ask which region each piece of data comes from.',
      'Only one of the two goes away automatically when build returns.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        "The local pointer p lives in build's stack frame; the 40 allocated bytes live on the heap, assuming malloc succeeds. When build returns, p's lifetime ends and its stack storage becomes reusable. The heap allocation remains allocated, and main receives a copy of its address. main can use that address until the allocation is freed and should call free on it when finished.",
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
]
