import type { LectureFx } from './types'

/**
 * CS50x 2026 Lecture 4: Memory, core window 1:02:30–1:47:30 (video time).
 * malloc(4) and strlen + 1 → copying strings → free/Valgrind → garbage values → Binky → swap by value vs by reference (chapters 0:57:11–1:48:14), capped at 45 min.
 * Segments are the official subtitles (https://cdn.cs50.net/2025/fall/lectures/4/lang/en/lecture4.srt), segmented by @lectheo/domain;
 * CC BY-NC-SA 4.0, CS50x 2026 by Harvard University, adapted by Lectheo.
 * Subtitles lightly corrected for ASR errors (scripts/lib/reviewed.ts); timestamps unchanged.
 * GENERATED by scripts/seed-library.ts (Opus 5.5 extraction/drafting, GPT-6.1 Sol blind
 * verification). Do not edit by hand: change the script and re-run it.
 */
export const lecture4: LectureFx = {
  key: 'l4',
  seq: 4,
  title: 'Lecture 4: Memory',
  youtubeId: 'db0H0U13YsA',
  start: '1:02:30',
  end: '1:47:30',
  duration: '2:19:54',
  fallbackAudioUrl: 'https://cdn.cs50.net/2025/fall/lectures/4/lecture4.mp3',
  segments: [
    {
      idx: 0,
      startMs: 3750270,
      endMs: 3784814,
      text: "the address of a chunk of memory for me. How many bytes do I want? Well, technically I just want 4 bytes, so I could do malloc of 4, and that will literally ask the operating system running in the cloud in VS code for. 4 bytes of memory somewhere in that black and yellow grid I keep drawing on the screen. I don't know where it's going to be, but I don't care because malloc's return value will be the address of the first bye thereof. Now it's a little dumb to hard code for not knowing what the human's going to type in, but that's OK. We can do this more dynamically and use our old friend strlen, ask the computer what is the length of S.",
    },
    {
      idx: 1,
      startMs: 3785530,
      endMs: 3819800,
      text: "And then Add one because we know that we need to additionally have an extra byte even though the length of high in the real world is 3, but we know underneath the hood we actually need that 4th byte, hence the plus 1. Now to use malloc, I actually need to add another library here, stdlib for standard library.h, and that's going to give me access to the prototype for and in turn. The malloc function. Now with this chunk of memory, it's up to me to copy the string. So how do I go about copying a string from S into T?",
    },
    {
      idx: 2,
      startMs: 3819879,
      endMs: 3844830,
      text: "Well, I can do this in a bunch of ways, but let me propose that we do it like this for into i equals 0, I is less than the string length of S, whatever that is, I + plus, and then inside of this fairly mundane loop, let's just set this uh I. Value of T equal to the value of S, and copy literally, very mechanically, every character from S into T.",
    },
    {
      idx: 3,
      startMs: 3846360,
      endMs: 3886110,
      text: "Then down here let's go ahead and capitalize just the first character of T by using 2 upper as before with or without the syntactic sugar, and then at the very bottom of this program, let's print out the value of S itself just for good measure to make sure we didn't screw it up this time and let's print out the value of T just so we see that I in fact have capitalized T and only T, but I'm not quite done yet. There's a design flaw here and a mistake, but it's subtle. Does anyone want to pluck off one or the other? Check 50 and design 50 are not gonna like this. Yeah.",
    },
    {
      idx: 4,
      startMs: 3889870,
      endMs: 3920074,
      text: "Yes, because strlen always returns the sort of real world length of the string, H3, this would seem to accidentally forget to copy the null character. So I can fix this in a few different ways. I could, for instance, at the bottom of my loop actually do something like T4 equals singles and manually terminate it myself because I know it's got to end with a null. This would be frowned upon too. I shouldn't be hard coding the 4. This is all too sloppy. So don't do this.",
    },
    {
      idx: 5,
      startMs: 3920385,
      endMs: 3951120,
      text: "What I could instead do is say go up to and through the length of S because if the length of S is 3, but I use less than or equal to, that thing's going to iterate of course 4 times because I'm starting at 0 as always. So that I think fixes that problem, but now the design flaw, which is subtle, but we've seen it before, yeah. Exactly. It's just dumb of me to be asking the computer what's the length of S? What's the length of S? And every iteration.",
    },
    {
      idx: 6,
      startMs: 3951340,
      endMs: 3988909,
      text: "So this is why we introduced this trick where you can set another integer variable like N equal to that string length, and then after the semicolon just keep comparing I against N, which means you're not calling functions wastefully as before. All right, if I didn't mess up anything else, let me go into my terminal. Let me do uh oh, did I mess something up? I still, yes, I did mess something up. I should have put this back as well. Thank you. All right, so let's go ahead and do make copy, Escopy, and now, I'm gonna go ahead and type in high in all lowercase and hit enter.",
    },
    {
      idx: 7,
      startMs: 3989300,
      endMs: 4023385,
      text: "And you'll see now that s is unchanged. It's printed out again in lowercase, but t is in fact capitalized here. Now why is this? Well, in this case, what's happened is that I've got s in memory, but this time when I allocate T, I then use malloc to get a whole chunk of memory here that initially just contains who knows what garbage values as we've called them before. I'll just leave them as blank here, but it happens to be. For the sake of discussion at 0x456, 78 and 9, when then I actually set T equal to the return value of malloc, it's as though T is just pointing to this chunk of memory.",
    },
    {
      idx: 8,
      startMs: 4023564,
      endMs: 4056209,
      text: "Then in my own loop when I go from zero on up through N, that just means to copy the H, then the I, then the exclamation point, and because of the equal sign also print copy the null character instead. So this is getting a little tedious though admittedly like this is a lot of work just to copy a couple of strings. Could we be doing this a little bit better? So we actually can because of the libraries we're including turns out there's functions for copying strings that come with C. So in fact if I go back to BS code here, I don't actually need any of.",
    },
    {
      idx: 9,
      startMs: 4056304,
      endMs: 4095750,
      text: "This for loop here so long as I have actually allocated enough memory for the string, which I do think I've had, I can actually use literally a function called strcpy STRCPY for short, and pass in the destination and the source in that order almost feels a little backwards, but that's the way it's done to copy S's bytes into T. It's easy to mess them up, but don't mess them up for the documentation, the destination comes first and then the source string. Instead, so if I do this now, let's do make copy. We're good to go. If I do scopy now and type in high and all lowercase, we still have preserved that good property.",
    },
    {
      idx: 10,
      startMs: 4095959,
      endMs: 4133930,
      text: "But let me propose that things can go wrong and in fact this is about to make the program look way more complicated than it feels ideal, but I've been a little lazy here. There's a bunch of things that can go wrong for which it's worth knowing about the return values of these here functions. So all of this time. It has been possible for certain functions we've been using, get string among them to return confusingly, this null value NULL again humans decades ago decided that one would be called NUL, other humans decided this new thing would be called NULL. NUL pronounced null, it's just a null terminator backslash zero.",
    },
    {
      idx: 11,
      startMs: 4134089,
      endMs: 4171189,
      text: "It is a single byte of 8 bits, all of which are zeros. That's been true for a few weeks now. NULL happens to be a special memory address, literally 0x0 at which nothing is supposed to ever live. So whenever I describe the top left corner is this is address 0, this is 1, this is 2, humans years ago. Decided, you know what, let's just waste bye location 0 and never put anything there so that we have a special value to ensure that we can signal when something has gone wrong. So humans just decided don't use memory address 0x0 specifically and a few bytes after it. So what does this mean?",
    },
    {
      idx: 12,
      startMs: 4171399,
      endMs: 4208779,
      text: "Well, in my code all this time and since week one, frankly things could have gone wrong. So in VS code here I'm using get_string and I'm using malloc and I'm using strcpy and all of these print statements here, but I'm not actually adding as many error checks as I should. So it turns out if you read the actual documentation for Get string, which in fairness we never told you about until now, in cases of error, get string can return null. Why would it ever have an error if the human types in such a large paragraph of text maybe that there's no room in the computer's memory for everything they've typed in? Well, you don't want to just get back part of the text and not know that something went wrong.",
    },
    {
      idx: 13,
      startMs: 4208970,
      endMs: 4248830,
      text: "Get string is designed to return a special sentinel value, NULL in all caps. That just means I can't oblige. I can't return you a correct value. Here's an error instead. So what I should always have been doing since week one, but we consciously don't because it adds just too much overhead, is check if S equals equals null, then we should abort the program altogether and for instance like return one, as we've done before to just signify error like we cannot proceed because get string did not work. That is true of malloc too. Technically we should say if the address in T also equals null, that is 0x0, we should also return 1 because something.",
    },
    {
      idx: 14,
      startMs: 4249270,
      endMs: 4289095,
      text: "Uh, went wrong. So let's do this one more time. Turns out that even 2 upper is taking for granted the fact that the humans typed in anything at all. What if the human just types enter? Well, that's a valid string. It's the so-called empty string, quote unquote, but what is the length of nothing? It's going to be 0 and that's problematic because if you try to go to T at the first location, what is actually there? Well, that's actually the null character, which is not something you should even try to capitalize it would seem. So what we should really do here too is check only if. The sterling of S is greater than 0.",
    },
    {
      idx: 15,
      startMs: 4289234,
      endMs: 4327306,
      text: "Should you even bother upper casing that first character? I mean, one, at best it makes no sense because if there's no string, there's nothing uppercase. At worst I could break something by touching memory that I should not. And if I may, there's another issue now. On line 15, I'm asking the computer for memory, and it's going to hand me those 4 bytes, but technically I'm never giving them back. And so even though this program is so short that it's going to quit pretty soon and it's not a big deal, the computer will automatically reclaim that memory in long running programs that like servers or things that are running for a long time. If you use malloc and ask for memory but never give. Back to the computer, never free it, so to speak.",
    },
    {
      idx: 16,
      startMs: 4327476,
      endMs: 4354671,
      text: "Your computer might get slower and slower and slower and slower, essentially because it's running out of memory, not physically, but the computer thinks it's using all of its memory even if it's not actively in use. You, as the human know best and so at the end of this program, when I am completely done with T, you should similarly call free of T. Passing in the address that you allocated previously so that the operating system gets that memory back. If you don't do that, it's what's called a memory leak.",
    },
    {
      idx: 17,
      startMs: 4354791,
      endMs: 4392540,
      text: "If you've ever used a Mac program, a Windows program, iPhone or Android program that some of how it's just getting slower and slower and slower and slower, that is often a symptom of a human having messed up and not freeing memory that they don't actually need anymore. Questions on null or any of these kinds of checks. No All right, well, as a teaser, in just a bit we're going to reveal when and why things can go terribly wrong by way of a little bit of claymation from our friends at Stanford, but it feels like we're long past a good snack break.",
    },
    {
      idx: 18,
      startMs: 4392589,
      endMs: 4427585,
      text: "So why don't we go ahead and have some oranges and some fruit snacks, and we'll see you in 10. All right, we are back. So with memory, a lot of things can go wrong and in fact, a question came up during the break about whether or not I should have also called free on S, which was the string that I actually got back from GetString. The short answer is no. This has been a deliberate choice over the past several weeks whereby the implementation by CS 50 of GetString automatically frees memory that it has given to you once it is no longer needed, so that's a bit. Magic underneath the hood. Once those once you no longer use that though that feature goes away.",
    },
    {
      idx: 19,
      startMs: 4427755,
      endMs: 4467321,
      text: "But because I actually used malloc to get my memory for T, I did have to free that specific memory. So the rule of thumb quite simply is if you mallocked it, you must free it. If we get string mallocked it, you do not have to free it yourself. But of course things can go wrong and thankfully there are tools by which we can find memory related errors. And one thing we're To show you briefly is another tool called Valgrind, which is a nice complement to something like Debug 50 and PrintF and the Duck for actually chasing down specifically in this case memory related errors. So in fact, let me go over to VS code and open up a program I wrote in advance because it's just not all that useful, but it is demonstrative of some things that can go wrong.",
    },
    {
      idx: 20,
      startMs: 4467481,
      endMs: 4507124,
      text: "And in memory.c we have this code here. We include standardio.h and we include standard lib.h, the last. Of which recall is necessary now when you want to use malloc and in turn free and inside of this main function I'm doing a few things. I am first allocating 3 integers in kind of an interesting way because it turns out that malloc takes as its argument the number of bytes that you want to get. Now I know on most systems an integer is indeed 4 bytes. So if I want space for 3 integers, I could just do 3 times 4 is 12 and put 12. the parenthesis here, but that's generally frowned upon because it would make my code less portable to other systems where it might not be 4 bytes.",
    },
    {
      idx: 21,
      startMs: 4507324,
      endMs: 4542149,
      text: "So turns out you can use this operator size of and actually ask the computer how big is a data type, like an int on this specific system. And for CHARS you'll always get back 1. For ins you'll usually get back 4, and same goes for other data types as well, but this is the more dynamic way to ask that question if you want to get 3. Uh integers worth of memory. What I'm then going to do is assign on the left hand side the return value of malloc to this variable X just because an X itself is a pointer to an integer, more specifically to this chunk of memory, which is a sequence of 3 integers.",
    },
    {
      idx: 22,
      startMs: 4542229,
      endMs: 4581479,
      text: "This is very arbitrary and this is only meant to demonstrate things you can do incorrectly ultimately, but this is how I would dynamically get space for 3 integers. From malloc and store the address thereof in X. So it stands to reason that I could put my first value at X1 equals 72, my second value equaling 73, and my third value equaling 33. Now if some of this is rubbing you wrong, like these are actually, there's riddled with mistakes already, some of which are old to us, what's the first thing I've done wrong, even if you have no idea what's going on with line 8? What about lines 9, 1011? What I do wrong? Yeah.",
    },
    {
      idx: 23,
      startMs: 4582459,
      endMs: 4620750,
      text: "Yeah, my indexing is wrong. Like we've known for weeks now that with the arrays or with the ray syntax you always start counting at 0, then 1, then 2, not 123. So that's an issue, and this is a new detail. But given that I've used malloc Online 8, what other mistake have I done in this version of the program? What's missing? Free. So I didn't actually call free so this program has a memory leak. It's asking for memory and never handing it back. Now that's pretty good, you know, a few of us were able to just kind of eyeball the code and debug it, but that's not gonna be true for all people, all programs, certainly when the programs get larger and more complicated, so a program.",
    },
    {
      idx: 24,
      startMs: 4620859,
      endMs: 4660680,
      text: "Like Valgrind's purpose in life is to help you spot these kinds of errors. So for instance, when I run, make memory to compile this program and then do slash memory at a glance, it actually seems perfectly fine if only because I'm not seeing any errors even when I compile it or when I run it. But I do claim that there's at least 2 that we've seen here. It's just we're not getting so unlucky that the program's actually crashing as a result. So this is a more latent harder to detect bug. But what I'm going to do now is this I'm going to open up my terminal window and full screen. I'm going to then do Valgrind space.slash memory so as to run the Valgrind memory checker on this.",
    },
    {
      idx: 25,
      startMs: 4660814,
      endMs: 4698020,
      text: "Program, so similar to debug 50, but the name now is Valgrind. This isn't a CS 50 thing. This is a common program that programmers use. When I hit enter, the output is going to be atrocious, frankly. It's more way more complicated than it needs to be. They put this number here, which means something specific, but it's just stupid that it's on every line of output. So it's overwhelming at a glance. But once you've trained your eyes to look for useful information, there's a couple of useful insights here. So one, invalid right of size 4 that apparently is somehow related to line 11. So let's go there. Let me use this minimize my terminal window. look at line 11 of memory.c and just see which line that was.",
    },
    {
      idx: 26,
      startMs: 4698109,
      endMs: 4732450,
      text: "OK, invalid right of size 4. Well, writing means like changing a value. Reading means accessing a value, so they're sort of opposites. Invalid right of size 4. Well, here's why it's generally useful to know generally how big an it is like 4 you're trying to write 4 bytes incorrectly. So why is line 11 invalid? Just to be clear, Because the index is off, like I'm touching memory that I should not. If I ask the computer for space for 3 integers, each of which is 4 bytes, that should give me location 01 and 2, not location 3.",
    },
    {
      idx: 27,
      startMs: 4732580,
      endMs: 4763812,
      text: "So you still have to know a little something about programming to be able to make good use of that information invalid right of size 4. But once you've sort of trained your mind and your eye to catch it like, oh, now I'm an idiot, I have to go in and fix that problem. But what else? Wrong based on Valgrind's output here. So this is kind of worrisome leak summary. Definitely lost 12 bytes in one block. I don't really know what 1 blocks means for now, but 12 bytes should be familiar because if you generally remember that an inch is 4 bytes and you ask for 3 of them, oh, there's my 12.",
    },
    {
      idx: 28,
      startMs: 4763982,
      endMs: 4801759,
      text: "So somehow I'm losing 12 bytes of memory, not in the literal sense, but it means by the time the program finishes, you have not returned or free. all of the memory that you asked for. So this line here is your hint that you've done something wrong with respect to 12 bytes in total. And sometimes you'll see slightly different output here. For instance, we see mention up here 12 bytes and 1 blocks are definitely lost in lost record 101, very verbose, but the juicy part is, ah, on line 8 is the source of that error specifically. So there too, it's a little bit of a bread crumb leading me to the solution for fixing this. So if I go up here. I look at line 8.",
    },
    {
      idx: 29,
      startMs: 4801799,
      endMs: 4834250,
      text: "OK, there's only so much that I could have done wrong on line 8 if I've mallocked the memory on line 8. Sounds like I do need to free it later on. So let's fix both of these problems. The first one is just the indexing issue. Change the 123 to 012. Let's then fix the second problem by just freeing X at the very end and just for good measure. This was not caught by Valgrind because it doesn't always happen, but there's one other scenario that could go wrong, and it relates to line 8. What should I be doing?",
    },
    {
      idx: 30,
      startMs: 4835500,
      endMs: 4871390,
      text: "Uh I am doing an array, but recall that we can use array syntax on chunks of memory. So technically what Lion 8 is doing is this it is allocating 12 bytes of memory from the computer just because, just to demonstrate how malloc works, and it's storing the address of that first byte in a variable called X. The bracket notation is just the syntactic sugar that allows me to change values at X's address. I could alternatively just use pointers and say go to X and put 72 there.",
    },
    {
      idx: 31,
      startMs: 4871720,
      endMs: 4907129,
      text: "Go to X + 1 and put 73 there. Go to X + 2 and put 33 there. Using pointer arithmetic, but those are identical and no, generally, you know, most people would just use square bracket notation because it's just a little cleaner and easier to read and write. OK, but back to this question, there's still a subtle bug here, based on our example just before break, what should you be doing any time you call malloc and get string, and a few other functions for that matter. Did I hear the answer?",
    },
    {
      idx: 32,
      startMs: 4907950,
      endMs: 4946950,
      text: "Checking for Checking for null, right, because if lock has an error, there's not enough memory for whatever reason, you should not be proceeding to touch that memory because it might be the null address that is 0 X0. So what you should really be checking is, well, if X equals equals null, there's no more work to be done here. Let's just return one down here and only if we get all the way to the bottom should we maybe return 0 to signify. Uh, explicitly that there is in fact successful operation. All right, with that said, let's go back down here, remake memory, no error messages from the compiler slash memory that too seems OK, but it was fine the first time.",
    },
    {
      idx: 33,
      startMs: 4947029,
      endMs: 4978279,
      text: "Let's now run Valgrind. Let me, uh, maximize my window. One run Valgrind.slash memory crossing my fingers as always, and now. This is actually pretty good. It's much shorter output even though it's just as scary at a glance, but most of this is fluffy and not very revealing. Heap summary in use at exit 0 and 0. So look, like all heap blocks were freed, no leaks are possible. Heap is a word we'll come back to, but this means there's nothing wrong. In fact, zero errors, which is a good thing. So in short, Valgrind is among the most arcane programs we're going to use.",
    },
    {
      idx: 34,
      startMs: 4978362,
      endMs: 5017355,
      text: "Its output was really designed for those more comfortable, if you will, but there's still juicy insights there if you just kind of look for things that lead you to like this file on this line number, odds are that will lead you to the most subtle of bugs. In fact, another type of bug is when we do indeed touch memory, we shouldn't. So let me zoom out on that, clear my terminal, and let me open up another program or maybe write this one real. Fast incorrectly. So let me create a program called Garbage.c to demonstrate what we've generally called garbage values, that is values that are still in memory, but I didn't put them there myself necessarily. I'm going to include standardio.h. I'm going to include standard lib.h.",
    },
    {
      idx: 35,
      startMs: 5017866,
      endMs: 5053560,
      text: "and then I'm going to go ahead and actually no need for standard lib this time. Let's do in main void. And inside of main, let's give myself an array of like way too many exam scores or whatnot. We used to do just a few, but let's say there's 1,0024. Then let's go ahead and do 4 in uh for in I equals 0, I less than 124, I plus plus, and in here, let's go ahead and print out, uh, whoops, let's go ahead and print out using print F each of those scores. Of course, I have clearly forgotten to do something in this program, which is what?",
    },
    {
      idx: 36,
      startMs: 5059689,
      endMs: 5095584,
      text: "I haven't actually put in any scores there for real. Like I've asked the computer, give me an array for 11,024 integers, but I've not used get into or even manually typed in any of my quiz scores, which we did in the past. That's because I'm intentionally trying to show us garbage inside of the. Computer's memory. What this loop is going to do on line 8 now is literally print out the first in, the second in, the 3rd in all 100 24 ins, but all of them should be garbage values because I myself haven't put anything in those dresses yet. So let's go ahead and make garbage. Let's go ahead and maximize my terminal window just to see more on the screen. Do garbage.",
    },
    {
      idx: 37,
      startMs: 5095625,
      endMs: 5134830,
      text: "It's going to be super fast output because the computer is way faster than 1,0024 variable values alone. There is a lot of garbage output. So when we talk about garbage values in the abstract, like here's just some random zeros, a 25, a 32,000, a negative number, and so forth, that's because it's essentially remnants from the computer's memory of stuff that might have happened previously, not necessarily by me in this moment, which is to say you just shouldn't touch that memory at all whatsoever. So now we're seeing garbage values for the actual first time. Let's consider another example of a program that doesn't contain that does. Contain potentially memory errors and let's look at this too.",
    },
    {
      idx: 38,
      startMs: 5135040,
      endMs: 5174875,
      text: "So this is not really a useful program, it's meant to be demonstrative of some of these concepts. So here we have a program takes no command line arguments. Up here we've got a line. That pair of lines that declares two pointers but doesn't yet initialize them to any variables and that's fine. You don't have to have an equal sign with any variable. You just eventually should assign it some value. But this just tells the computer, give me a variable X that's going to store the address of an end. Give me another variable Y that's going to store the address of another N. OK. What happens next? Well, on this line of code. This simple example, we're allocating enough space for a single integer just because it's a stupid exercise. There's no reason to do this other than to demonstrate how malloc works for the moment.",
    },
    {
      idx: 39,
      startMs: 5175165,
      endMs: 5213419,
      text: "malloc returns the address of that chunk of memory, so that's what goes in X. So X is now pointing at somewhere in memory 4 bytes of space that it can certainly put a value at. How do we do that? Well, if you do X and use the D-reference operator, that means go to that chunk of memory and put the number 42 there. That's totally valid. This says, go to the address in Y and put the unlucky number 13 there. Unlucky quite literally because what is Y pointing to at this moment? It's just the garbage address. Why? Because if you don't initialize why, who knows what it's going to be pointing to.",
    },
    {
      idx: 40,
      startMs: 5213459,
      endMs: 5241459,
      text: "Maybe it's 0, maybe it's 25, maybe it's 32,000, a negative number, just like we saw in the previous example. You have no idea what values are going to be in X and Y unless you yourself put those values there. So this is highlighted in red because bad things are going to happen if you try to dereference an invalid or a bogus pointer, even worse than just touching uh variables that might not have value. If you dereference an address and try going to some random place, the computer is generally not going to like that.",
    },
    {
      idx: 41,
      startMs: 5241589,
      endMs: 5281560,
      text: "And in fact, our friends at Stanford wonderfully brought this particular scenario to life whereby even though this example is a bit contrived just to fit it all on the screen at once, it is going to be the case that bad things happen if we don't check for these values and actually assign valid values in the form of, as we'll see now, some claymation. So here I give you a binky. Uh, which is a bit of claymation from our friend Nick Parlante at Stanford if we could dim the lights unnecessarily dramatically. Hey Binky, wake up. It's time for pointer fun. What's that? Learn about pointers.",
    },
    {
      idx: 42,
      startMs: 5281830,
      endMs: 5317529,
      text: "Oh, goody. Well, to get started, I guess we're gonna need a couple pointers. OK, this code allocates two pointers which can point to integers. OK, well, I see the two pointers, but they don't seem to be pointing to anything. That's right. Initially, pointers don't point to anything. The things they point to are called pointees, and setting them up's a separate step. Oh, right, I knew that the pointees are separate. So how do you allocate a pointee? OK, well, this code allocates a new integer pointee, and this part sets X to point to it. Hey, that looks better. So make it do something.",
    },
    {
      idx: 43,
      startMs: 5317939,
      endMs: 5350089,
      text: "OK, I'll dereference the pointer X to store the number 42 into its pointee. For this trick, I'll need my magic wand of dereferencing. Your magic wand of dereferencing, uh, that, that's great. This is what the code looks like. I'll just set up the number and Hey, look, there it goes. So doing a D-reference on X follows the arrow to access its pointee in this case to store 42 in there. Hey, try using it to store the number 13 through the other pointer. Why?",
    },
    {
      idx: 44,
      startMs: 5350689,
      endMs: 5389459,
      text: "OK, I'll just go over here to Y and get the number 13 set up and then take the wand of dereferencing and just. Oh hey, that didn't work. Say, uh, Binky, I don't think dereferencing Y is a good idea because, uh, you know, setting up the pointee is a separate step and uh I don't think we ever did it. Hm, good point. Yeah, we, we allocated the pointer Y but we never set it to point to a pointee. Very observant. Eh, you're looking good there, Binkie. Can you fix it so that Y points to the same pointee as X? Sure, I'll use my magic wand of pointer assignment.",
    },
    {
      idx: 45,
      startMs: 5389790,
      endMs: 5423629,
      text: "Is that gonna be a problem like before? No, this doesn't touch the pointees. It just changes one pointer to point to the same thing as another. Oh, I see. Now Y points to the same place as X. So, so wait, now Y is fixed, it has a pointee. So you can try the wand of dereferencing again to send the 13 over. OK, here goes. Hey, look at that. Now dereferencing works on Y, and because the pointers are sharing that one pointee, they both see the 13. Yeah, sharing, uh, whatever. So are we gonna switch places now? Oh look, we're out of time.",
    },
    {
      idx: 46,
      startMs: 5424729,
      endMs: 5463812,
      text: "I can only imagine how long that took Nick, but the key detail was that bad things happened to Binky when we did this line of code, dereferencing an invalid pointer that had no true value assigned. It was just some garbage value. Now what's the solution? Well, as Nick proposed, just don't do that and instead at least do something sensible like assign X equal toy, not to make a copy of anything per se, but to literally point X at the same location in memory. To pointy at the same location in memory as X, then a line like this is perfectly valid. You can go to that address, which happens to be the same as the 42, and that's why in the claymation form we saw that the 42 became a 13 instead.",
    },
    {
      idx: 47,
      startMs: 5463901,
      endMs: 5499764,
      text: "So again, at the end of the day, this is only demonstrative of these basic building blocks that we now have at our disposal, but also how easy it is to do things incorrectly. So this is one of those with great. Power comes great responsibility. C is one of the languages that is incredibly high performing. It's so close to the hardware that you have so much control over the memory and operation that you can write really good, really fast code. And that's why even all these decades later, it's among the most omnipresent programming languages in the world. At the same time, you can really screw things up and so many of today's software that are hacked in some way or crashed for some reason is often.",
    },
    {
      idx: 48,
      startMs: 5499916,
      endMs: 5530680,
      text: "Humans have just missed some simple mistake like this that happens to relate to memory, so more modern languages that we'll soon see like Python and if in high school you study Java, you don't have this much control over the computer's memory. There's many more defenses put in place to protect you and me from ourselves, so to speak, but you pay the price by some of those languages tend to be uh less uh slower and less performance, yeah. My I What?",
    },
    {
      idx: 49,
      startMs: 5531950,
      endMs: 5570290,
      text: "Like like difference What is the difference here that we're now playing with memory? This will become clear this week and next, and in fact some of the examples on which will end today will motivate needing to have finer grain control over what's going on inside of the computer when you want to deal with files, for instance, you're going to need to know a little something about memory addresses and where things are when you want to build structures in memory beyond the complexity of an array. In fact, next week we're going to start building. Two dimensional structures in the computer's memory to represent the equivalent of like a family tree for instance or trees more generally that can store data in a more efficient way.",
    },
    {
      idx: 50,
      startMs: 5570459,
      endMs: 5606750,
      text: "Up until now all we have is arrays, and with arrays you can achieve something like binary search, but we're going to see there are things you can't do with arrays, especially if speed is important. I was saying like for example if you were to ask me to do this like last week. I'll be like X equals 13 or something. Correct. So last week, if you just said in X equals 13 or in Y equals 42 or whatnot, totally fine. And again this program sole purpose in life is to demonstrate how you can make mistakes in and of itself is not useful here, but it's representative of how we're gonna start using this syntax, not only in this week's problem sets but next week as well.",
    },
    {
      idx: 51,
      startMs: 5608029,
      endMs: 5645540,
      text: "All right, so with that claim made that we can do a lot of damage, let's consider how pointers and knowledge of memory addresses can actually solve some useful problems. Um, can we get one volunteer to come on up and help pour a drink? Come on up. All right, what is your name? From on over If you want to say a quick hello to the group. I'm Olivia. OK, and, and a little something about yourself. Oh, I live in Canada. OK, welcome. Well, come on over here, Olivia, and we have, um, 2 glasses, well, really 3 glasses.",
    },
    {
      idx: 52,
      startMs: 5645620,
      endMs: 5675979,
      text: "So we have these fancy ray bands that have cameras built in whereby we can sort of capture your point of view. If you're comfortable, we'll put these on. There's no lenses in them. The white light will mean we're recording, hopefully a memorable moment. This battery too is dead. All right, we don't have a backup for the backup, so we're gonna pretend that this part never happens, so. Olivia, we have 2 glasses here for you, and I'm gonna go ahead and pour some colored liquid into both. So we've got some blue liquid here into this glass. All right, so we'll fill this up here.",
    },
    {
      idx: 53,
      startMs: 5677649,
      endMs: 5717310,
      text: "And then in this one we're gonna go ahead and pour this orange liquid, and at this point in the story I'm going to exclaim, oh no, I accidentally put the wrong liquid in the wrong glass so I got this backwards. So what I'd like you to do is swap the values in these glasses so that the blue goes into that glass and the the orange goes into this glass without mixing it without mixing it. So what you're hesitating. Why? Well, it would be hard to do. Unless you can like oh it would be like hard to do um without mixing the two because like you don't have anywhere to put the other one. Of course. So in the real world this is not really solvable unless for instance we have a temporary variable if you will, like an empty glass in which to do this.",
    },
    {
      idx: 54,
      startMs: 5717339,
      endMs: 5755620,
      text: "So here is your third variable if you want to go ahead now and get the blue into that one and the orange into that one, yeah. No pressure. All right, so we're putting one value into the temporary variable, we're putting the other value into the original value. OK, and now you're probably gonna take, yep, I'm guessing the temporary value, put it into the original variable. And that that was very well done. If maybe we can give Olivia a round of applause for just that. Thank you.",
    },
    {
      idx: 55,
      startMs: 5758080,
      endMs: 5796815,
      text: "Little partying before you're here too. So. The goal here really being to create a memorable moment of like, oh remember the time Olivia tried to swap two values she needed a temporary variable is the takeaway. So why is that? Well, in code, if we wanted to do the same principle, we're going to need somewhere temporary to put one of those values before we can make this happen. The catch is though that if we don't do this intelligently, like it's just not going to work in C unless we take advantage of some of these new capabilities. So in fact, I'm going to go over to VS code here and I'm going to open up a program called. Swap.c that I wrote in advance whose purpose in life is simply to swap two variables values. So I've got standard IO.h at the top so I can use print F.",
    },
    {
      idx: 56,
      startMs: 5797085,
      endMs: 5829972,
      text: "I've got the prototype for a swap function which is might as well be Olivia in this case that's going to take two inputs A and B or two glasses and swap their values ultimately is its purpose. Inside of main though, I'm going to do this. I'm going to set two variables X and Y equal to 1 and 2 respective. I'm then just as a point of clarification going to print out the value of X is such and such, Y is such and such. Then I'm going to call the swap function, AKA Olivia to swap the values X and Y. Then I'm going to print out X is this and why is this so that hopefully I'll see that they've indeed been swapped.",
    },
    {
      idx: 57,
      startMs: 5830182,
      endMs: 5865580,
      text: "At the bottom of this file we have the actual swap function, and as you might expect, it takes two inputs A and B, both of which are integers, so I could have called them anything I want. The first thing this function does is it grabs an empty glass called temp, puts a or the blue liquid into it. Then we put into a the value of B. So we've sort of lost the value of a at this point except that we did make a copy of it into temp. And then lastly we put into B the temporary variable and at the end the temp variable is empty, although technically it still has a copy of the value, but it's no longer useful because the job is done and A has become B and B has become A.",
    },
    {
      idx: 58,
      startMs: 5865720,
      endMs: 5899390,
      text: "So I dare say this is like the literal translation of what Olivia just did and I like the logic of it. However, when I actually run this program, something goes awry. So let me go ahead and do make swap. slash swap and I'll maximize my window. I should see hopefully that X is 1, Y is 2, and then X is 2, and Y is 1. But no, like, even though I literally translated into code what Olivia did, this didn't actually seem to work. And why is that?",
    },
    {
      idx: 59,
      startMs: 5899509,
      endMs: 5930564,
      text: "Well, it turns out that this version of the program is not right, in fact, because of issues of scope, and we've talked about scope before, generally in the context of like where variable lives. We've said that a variable only exists in like the most recent curly braces that you opened up for it, and that was true. It's just sort of a colloquial way of describing what scope is, but scope comes into play here because it turns out that A and B insofar as they are the arguments or parameters for the swap function, they. Have a different scope than X and Y and that still follows the same definition.",
    },
    {
      idx: 60,
      startMs: 5930615,
      endMs: 5967279,
      text: "They're inside of different curly braces than X and Y are, so it seems that I may very well be swapping A and B, but I'm not having any impact on X and Y. So why is that? Well, in C, all this time, any time you pass in arguments to a function, you are passing in those arguments by value, so to speak. You're literally passing in copies of the variables to the function you are calling. So what does this mean? Well, more concretely, if like this is a photograph of a chunk of memory inside of the computer and we sort of zoom in as we've done before and we abstract away all of the bytes from top to bottom, what's really happening inside of the computer's memory?",
    },
    {
      idx: 61,
      startMs: 5967759,
      endMs: 6003694,
      text: "Is that we're using some of it for X and Y and some other memory for A and B, but how is that in fact happening? Well, it turns out to a question that came up before the break, memory in a computer is actually assigned in a somewhat deliberate fashion. And generally if we think of this rectangle as representing my computer's whole chunk of memory, generally what happens when you run a program with something or on a Mac or PC by double clicking. Or on a phone by single tapping, what happens is all of the zeros and ones that were compiled by the company or person who made that program are loaded into the top of the computer's memory, so to speak. This is just an artist's rendition.",
    },
    {
      idx: 62,
      startMs: 6003734,
      endMs: 6039790,
      text: "There's no notion of top or bottom per se, but it's loaded into this chunk of memory at the very edge of the computer's memory, AKA machine code. The zeros and ones that compose the actual program, that's where they go. So they're copied from the hard drive or the SS. whatever you know it as the persistent storage, and it's put there in the computer's RAM or random access memory, which is the faster memory where programs and files live while you are using them. Meanwhile, if your program or the program you're using has any global variables, global in the sense that they're defined outside of main and not inside of main or inside of other functions, they end up right below that machine code by convention just so they're accessible everywhere.",
    },
    {
      idx: 63,
      startMs: 6040205,
      endMs: 6075970,
      text: "Meanwhile, there's this big chunk of memory below that called the heap. The heap is the chunk of memory that malloc uses to allocate memory for you. So the first time you call malloc, it's going to give you probably this chunk of memory. The second time, this chunk, the 3rd time, this chunk, and this chunk, and so forth, back to back to back in memory. But malloc is going to manage all of that for you. You don't have to worry about where it's coming from, but it's coming more generally from this big heap area. But it turns out that the way computers are designed is that the heap of course sort of grows and therefore downward again even though there's no notion of up down inside of the computer but it grows in this direction.",
    },
    {
      idx: 64,
      startMs: 6076310,
      endMs: 6115640,
      text: "But it'd be nice to make use of this other area of memory and that's what's called the stack and the stack is the area of memory that's used any time you create local variables or call functions. So again, malloc uses memory from up here and functions and variables use memory down here just because the. What humans in a room decided years ago is how the computer's memory would be used. Therefore, the stack grows sort of vertically, much like stacking trays in a cafeteria or the dining hall. They go from bottom to top in this model. All right, well, let's consider for the moment just how the stack is used because we're using a main function in this program. We're using a swap function in this program, so I claim that those functions are going to use memory down here.",
    },
    {
      idx: 65,
      startMs: 6115930,
      endMs: 6150979,
      text: "Well, how are they going to use it and how is this in fact bad for our current goal? Well, when you call the main function. It uses this chunk of memory here, specifically if main has any arguments like command line arguments or if main has any local variables, they end up down here in memory. Meanwhile, when main calls swap, swap gets the next available chunk of memory above it, so to speak, in memory, and any of its arguments or local variables end up there. So when, when Swap is done executing, it's as though that memory disappears even though the zeros and ones are still there, but the computer can now reuse.",
    },
    {
      idx: 66,
      startMs: 6151060,
      endMs: 6184529,
      text: "That same chunk of memory later ergo garbage values when functions are being called going up and down conceptually, that's why you're getting remnants of previous values in the computer's memory. But let's focus on main for a moment. In main in this program, recall that I declared two variables X and Y X getting the value 1, Y getting the value 2 per these two lines of code. Then I called the swap function. So swap is going to get its own chunk of memory, more technically called a frame of memory. And inside of that frame it has two arguments A and B and a local variable called temp. So I'll draw them as such.",
    },
    {
      idx: 67,
      startMs: 6184899,
      endMs: 6224189,
      text: "When you actually call swap, passing in X and Y, X and Y are passed in by value, that is to say copy. So A becomes a copy of X and B becomes a copy of Y. So when this line of code. Or rather this prototype for swap just makes clear that it takes two arguments A and B, both of which are integers in that same order. So X. Y lines up with a B. So what happens then inside of the swap function if A is a copy of X and B is a copy of Y? Well, at the moment it's equal to 1 and 2 respectively, but consider this first line of code in temp gets A. So temp takes on the value of a.",
    },
    {
      idx: 68,
      startMs: 6224930,
      endMs: 6254000,
      text: "Next line of code A gets B. So A gets the value of B, sorry, which just happened. Meanwhile, B gets the value of temp, so B gets the value of T. Now temp still has a copy of one, so it's not quite analogous to the liquid because we're that glass is clearly now empty, but it does contain remnants of what it once did. But the key here is that A and B have successfully been swapped. If I were to print out A and B, I would see that they've been swapped.",
    },
    {
      idx: 69,
      startMs: 6254169,
      endMs: 6288884,
      text: "But what has obviously not been swapped in this story, no one has touched X or Y because when swap returns, especially if I don't even print out anything in swap, X and Y are unchanged. So A and B, the copies were swapped but not the original values, and that's the essence of the problem here with this this simple example of swapping values because I was passing by value. But as of today we now. Have a solution to this problem because previously to today if I asked you to write a function that swaps two values, you could not physically do it in code because you had no way of expressing the solution to this problem.",
    },
    {
      idx: 70,
      startMs: 6289055,
      endMs: 6323330,
      text: "But now we have the ability to pass by reference, that is use pointers and addresses more generally to tell the function how to go to an address and do something there, how to go to another address and do something there. How do I express this syntactically? It's going to look a little scary at first glance, but it's just an application of today's new building blocks. This bad version of the program. Where A and B are both integers just needs to change to be addresses of integers. So give the function a sort of treasure map that leads it to the actual X and Y by saying that A is now not going to be an in per se but the address of an N.",
    },
    {
      idx: 71,
      startMs: 6323729,
      endMs: 6362725,
      text: "B is going to be the address of an in and now to use those values you can say the following in temp gets whatever is at location A. Go to location A and put whatever's at location B. Go to location B and put in the temp value. And here is a perfect example of where this use and overuse of the star or asterisk operator is just like cognitively confusing, frankly, because we use star for multiplication, we use it for declaring a pointer, we use it for dereferencing a pointer ideally. Years ago would have come up with another symbol on the US English keyboard to represent these different ideas, but this is where we're at. We're using the star for different things in different contexts.",
    },
    {
      idx: 72,
      startMs: 6362845,
      endMs: 6400859,
      text: "So this just tells the computer that A is going to be a pointer an address of an int. This tells the computer that B is going to be the address of an int. This star, when there's no data type to the left of it means go to that address, as does every other example thereof. So what's happening this time if we actually look at the diagram again, X and Y are still 1 and 2 respectively. Swap gets called, it gets now the values of the address of X and the address of. So pictorally we might draw that as following A is pointing to X, B is pointing to 2. I mean technically it's like 0x123 and 0x12 whatever, but who cares?",
    },
    {
      idx: 73,
      startMs: 6400899,
      endMs: 6439839,
      text: "We're just going to abstract it away now with actual arrows or pointers. The beauty of this now then is if we look at the swap function, in temp gets star A. That means started A and Go there sort of shoots and ladder style familiar with the game and you find the value 1 so you put the value 1 inside of temp which is why it's there now. Meanwhile, this next line of code go to A's address, go to B's address and copy the latter to the former. So this means go to A, this means go to B, where you find the 2, so put the 2. Where A is pointing. Lastly, go to B and put temp there so that's easy. Go to B and point temp, which is why we now have the 1.",
    },
    {
      idx: 74,
      startMs: 6440060,
      endMs: 6448589,
      text: 'And the beauty of this now is that when swap is done executing, this memory, this frame sort of goes away conceptually, even though the zeros and ones are still there,',
    },
  ],
  concepts: [
    {
      key: 'strings_as_char_pointers',
      name: 'Strings as char *',
      summary:
        'A string is accessed through the address of its first character, so copying a string means allocating length-plus-one bytes for a new chunk and copying every character including the null terminator, either by loop or with strcpy.',
      keyPoints: [
        {
          id: 'k1',
          text: 'Copying a string requires allocating strlen(s) + 1 bytes, because the null terminator needs an extra byte.',
          segs: [0, 1],
        },
        {
          id: 'k2',
          text: 'A loop that copies characters must run up to and including strlen(s) so that it also copies the null character.',
          segs: [4, 5, 8],
        },
        {
          id: 'k3',
          text: 'Storing strlen in a variable n avoids recomputing the length on every iteration.',
          segs: [5, 6],
        },
        {
          id: 'k4',
          text: 'strcpy(destination, source) copies a string into memory that has already been allocated, with the destination argument first.',
          segs: [8, 9],
        },
        {
          id: 'k5',
          text: 'After the copy, t points to its own separate chunk, so capitalizing t leaves s unchanged.',
          segs: [7, 9],
        },
      ],
      segs: [0, 1, 2, 4, 5, 7, 8, 9],
      salience: 0.6,
    },
    {
      key: 'malloc_and_null',
      name: 'malloc and NULL checks',
      summary:
        'malloc, declared in stdlib.h, asks the operating system for a number of bytes and returns the address of the first byte, or NULL (address 0x0) on failure, so its return value should always be checked.',
      keyPoints: [
        {
          id: 'k1',
          text: 'malloc takes a number of bytes and returns the address of the first byte; sizeof(int) makes the request portable across systems.',
          segs: [0, 20, 21],
        },
        {
          id: 'k2',
          text: 'NULL is the special address 0x0 where nothing is stored, which is different from NUL, the backslash-zero string terminator.',
          segs: [10, 11],
        },
        {
          id: 'k3',
          text: 'get_string and malloc return NULL on error, so the program should check for NULL and return 1.',
          segs: [12, 13, 32],
        },
        {
          id: 'k4',
          text: "Bracket notation on malloc'd memory is syntactic sugar for pointer arithmetic, so x[1] means the same as *(x + 1).",
          segs: [30, 31],
        },
        {
          id: 'k5',
          text: "The program should check that strlen(s) > 0 before capitalizing the first character, so an empty string's terminator is never touched.",
          segs: [14, 15],
        },
      ],
      segs: [0, 1, 10, 11, 12, 13, 14, 15, 20, 21, 22, 30, 31, 32],
      salience: 0.8,
    },
    {
      key: 'memory_leaks',
      name: 'free, memory leaks and Valgrind',
      summary:
        'Memory obtained with malloc must be returned with free, or the program leaks memory; Valgrind helps find leaks and invalid reads or writes.',
      keyPoints: [
        {
          id: 'k1',
          text: "Forgetting to free malloc'd memory causes a memory leak, which can make long-running programs grow slower and slower.",
          segs: [15, 16, 17],
        },
        {
          id: 'k2',
          text: "The rule of thumb is that if you malloc'd it, you must free it; memory that CS50's get_string allocated is freed automatically.",
          segs: [18, 19],
        },
        {
          id: 'k3',
          text: 'Valgrind reports an "invalid write of size 4" when code writes past the end of allocated memory, such as an off-by-one index.',
          segs: [25, 26],
        },
        {
          id: 'k4',
          text: 'Valgrind\'s leak summary (for example, "definitely lost 12 bytes") points to the line where the leaked memory was allocated.',
          segs: [27, 28],
        },
        {
          id: 'k5',
          text: 'After the fixes, Valgrind reports that all heap blocks were freed and there are zero errors.',
          segs: [29, 33],
        },
      ],
      segs: [15, 16, 17, 18, 19, 23, 24, 25, 26, 27, 28, 29, 33, 34],
      salience: 0.75,
    },
    {
      key: 'pointers',
      name: 'Pointers and dereferencing',
      summary:
        'A pointer stores the address of a value, and dereferencing it with * goes to that address, which is only safe once the pointer has been set to point at a valid pointee.',
      keyPoints: [
        {
          id: 'k1',
          text: 'Declaring a pointer does not allocate its pointee; setting up what it points to is a separate step.',
          segs: [38, 42],
        },
        {
          id: 'k2',
          text: '*x = 42 means "go to the address in x and store 42 there."',
          segs: [39, 43],
        },
        {
          id: 'k3',
          text: 'Dereferencing an uninitialized pointer follows a garbage address, and bad things happen.',
          segs: [39, 40, 44, 46],
        },
        {
          id: 'k4',
          text: 'Uninitialized memory contains garbage values, which are leftovers from earlier use of that memory.',
          segs: [34, 36, 37],
        },
        {
          id: 'k5',
          text: 'Pointer assignment (y = x) makes both pointers share one pointee without copying any data.',
          segs: [44, 45, 46],
        },
      ],
      segs: [38, 39, 40, 41, 42, 43, 44, 45, 46, 34, 35, 36, 37, 47, 48],
      salience: 0.8,
    },
    {
      key: 'pass_by_reference',
      name: 'Passing by value vs. by reference (swap)',
      summary:
        'Because C passes arguments by value, a naive swap only exchanges copies of the variables, whereas passing their addresses lets the function swap the original variables.',
      keyPoints: [
        {
          id: 'k1',
          text: 'Swapping two values requires a temporary variable to hold one of them.',
          segs: [53, 54, 55, 57],
        },
        {
          id: 'k2',
          text: 'C passes arguments by value, so a and b inside swap are copies of x and y, and swapping them leaves x and y unchanged.',
          segs: [58, 59, 60, 67, 68, 69],
        },
        {
          id: 'k3',
          text: 'Passing by reference means declaring swap(int *a, int *b) and calling it with the addresses of x and y.',
          segs: [70, 72],
        },
        {
          id: 'k4',
          text: 'Inside the fixed swap, the lines int tmp = *a; *a = *b; *b = tmp; change the original variables through their addresses.',
          segs: [71, 73],
        },
        {
          id: 'k5',
          text: 'The * symbol is overloaded in C: it means multiplication, declaring a pointer, or dereferencing, depending on context.',
          segs: [71, 72],
        },
      ],
      segs: [53, 54, 55, 56, 57, 58, 59, 60, 67, 68, 69, 70, 71, 72, 73],
      salience: 0.75,
    },
    {
      key: 'stack_and_heap',
      name: 'Stack and heap',
      summary:
        "A program's memory is laid out as machine code, then globals, then a heap that malloc uses and that grows downward, and a stack of function frames that grows upward.",
      keyPoints: [
        {
          id: 'k1',
          text: 'Machine code is loaded at the top of memory, with global variables just below it.',
          segs: [61, 62],
        },
        {
          id: 'k2',
          text: 'The heap is the region malloc allocates from, and it grows downward.',
          segs: [63],
        },
        {
          id: 'k3',
          text: 'The stack holds local variables and function calls, and it grows upward like stacked cafeteria trays.',
          segs: [64],
        },
        {
          id: 'k4',
          text: 'Each function call gets its own frame, which is conceptually freed when the function returns, leaving garbage values behind.',
          segs: [65, 66, 74],
        },
      ],
      segs: [61, 62, 63, 64, 65, 66, 74],
      salience: 0.6,
    },
  ],
}
