import type { ItemFx } from './types'

/**
 * Verified practice bank for Lecture 5: Data Structures (F7.3).
 * GENERATED by scripts/seed-library.ts (Opus 5.5 extraction/drafting, GPT-6.1 Sol blind
 * verification). Do not edit by hand: change the script and re-run it.
 */
export const lecture5Items: ItemFx[] = [
  {
    concept: 'arrays',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [2, 3],
    publicPayload: {
      stem: 'A sorted array of integers supports binary search in O(log n) time. Which property of arrays makes this possible?',
      options: [
        {
          id: 'a',
          text: 'Each element stores a pointer to the element in the middle of the array.',
        },
        {
          id: 'b',
          text: 'The elements are stored back to back in memory, so simple arithmetic on the length finds the middle.',
        },
        {
          id: 'c',
          text: 'Arrays automatically grow when new elements are added, so they always stay sorted.',
        },
        {
          id: 'd',
          text: 'Arrays use less memory than linked lists, so the computer can scan them faster.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        'Because array elements are contiguous, you can take the length, divide by 2 and jump directly to the middle, then repeat on the middle of the middle. This direct jumping is what gives binary search its logarithmic running time.',
    },
    distractorMeta: {
      a: {
        misconception: 'Thinks arrays keep extra pointers to find the middle.',
        whyWrong:
          'Arrays store no pointers. The middle is computed by arithmetic because the storage is contiguous.',
      },
      c: {
        misconception: 'Believes arrays resize themselves and stay sorted automatically.',
        whyWrong:
          'Arrays have a fixed size chosen in advance, and growing one requires a manual reallocation. Sortedness is a precondition you must ensure yourself.',
      },
      d: {
        misconception: 'Confuses memory footprint with the ability to jump to the middle.',
        whyWrong:
          "Using less memory does not let you skip elements. The logarithmic time comes from computing the middle's location directly.",
      },
    },
    rubric: null,
    hints: [
      'Think about how the computer can get from the start of the array straight to the middle element.',
      'What does storing values back to back in memory let you do with an index?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'arrays',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [3, 4, 12],
    publicPayload: {
      stem: 'A program has an array holding 3 million integers, and the array is completely full. The program now needs to add one more integer, and the bytes right after the array in memory are already in use. What must happen?',
      options: [
        {
          id: 'a',
          text: 'The new integer can be stored anywhere in memory, and the array links to it with a pointer.',
        },
        {
          id: 'b',
          text: 'Nothing extra is needed, because arrays expand in place automatically.',
        },
        {
          id: 'c',
          text: 'The program must delete the oldest value to make room for the new one.',
        },
        {
          id: 'd',
          text: 'New, larger memory must be allocated, and all 3 million old values must be copied into it, which is slow.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        'Arrays must be contiguous. If no room exists after the array, you have to allocate a bigger chunk elsewhere with malloc or realloc and copy every old value over. For millions of values, this copying wastes a lot of time.',
    },
    distractorMeta: {
      a: {
        misconception: 'Mixes up arrays with linked lists.',
        whyWrong:
          'Arrays have no pointers between elements, and all of their elements must be contiguous.',
      },
      b: {
        misconception: 'Assumes arrays grow automatically.',
        whyWrong:
          "An array's size is decided in advance. Growing it requires an explicit reallocation.",
      },
      c: {
        misconception: 'Thinks overwriting old data is the standard fix.',
        whyWrong:
          'Discarding data is not resizing. The correct approach is to reallocate and copy the values.',
      },
    },
    rubric: null,
    hints: [
      'Remember the key requirement about where array elements live in memory.',
      'If the space right after the array is taken, where could a bigger contiguous block come from, and what must move into it?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'arrays',
    kind: 'spot_flaw',
    variant: 1,
    segs: [3, 4],
    publicPayload: {
      sentences: [
        'Arrays store their values back to back in memory, which is why we can compute the middle and run binary search in O(log n).',
        'The downside is that you have to decide how big the array is before you use it.',
        'If you guess too small, realloc fixes it instantly, because it just extends the array without touching the existing values.',
        'So arrays give fast search, but they are rigid about size.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'Claims that resizing an array with realloc is instant and never copies the existing values.',
      correction:
        'Growing an array usually means allocating a new, larger block and copying all the old values into it, whether you write a for loop or realloc does it for you. This takes time proportional to the number of values, which is slow for large arrays.',
      explanation:
        'Arrays must be contiguous. If there is no free room after the array, realloc has to move the data to a new location by copying every value. For something like 3 million values, that is a lot of wasted time.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the cost',
          description: 'States that resizing requires copying the old values into new memory.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Explains why',
          description:
            'Connects the copying to contiguity, or notes that it is slow for large arrays.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check each claim about what happens when an array runs out of room.',
      'Does realloc always have free space right after the array to grow into?',
    ],
    leakKeywords: ['copy', 'copying', 'instantly', 'realloc'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'arrays',
    kind: 'spot_flaw',
    variant: 2,
    segs: [3, 4, 12],
    publicPayload: {
      sentences: [
        "Because an array's elements are contiguous, you can use the length to jump straight to the middle element.",
        'That makes binary search on a sorted array run in O(log n) time.',
        "However, if an array fills up and there's no free space right after it, you must allocate a bigger chunk elsewhere and copy all the old values over.",
        "For a few values that's fine, but for millions of values the copying wastes a lot of time.",
      ],
    },
    answerKey: {
      hasFlaw: false,
      flawSentenceIdx: null,
      flawSummary: null,
      correction: null,
      explanation:
        'Every sentence is accurate. Contiguity enables computing the middle and binary search in O(log n). Growing a full array requires reallocating and copying everything, which is costly for large data sets.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Recognizes correctness',
          description: 'Correctly judges that no sentence contains an error.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Justifies',
          description:
            'Briefly explains why the claims about binary search and resizing cost hold.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check the claims about search speed and resizing separately.',
      'Compare each claim to what contiguous storage implies.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'correct',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'arrays',
    kind: 'transfer',
    variant: 1,
    segs: [3, 4, 12],
    publicPayload: {
      prompt:
        'A weather station logs one temperature reading per minute. The program starts with an array that has room for 1,000 readings. Whenever the array is full, it allocates a new array exactly one slot larger and moves the data over. After running for a year (about 500,000 readings), the program has become very slow at adding readings. Explain why, and say what property of arrays causes the problem.',
    },
    answerKey: {
      modelSolution:
        'Arrays must store their elements contiguously, so an array cannot simply be extended when the memory after it is in use. Each time this array fills up, the program allocates a new block and copies every existing reading into it. Because it grows by only one slot at a time, every new reading after the first 1,000 triggers another full copy. With hundreds of thousands of readings, each insertion copies hundreds of thousands of values, which wastes a huge amount of time. The root cause is the combination of a size fixed in advance and contiguous storage.',
      explanation:
        'This applies the array resizing cost: a fixed size plus contiguity means that growing the array requires reallocating and copying all the old values, which is slow for large data sets.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'r1',
          label: 'Contiguity',
          description:
            'Identifies that arrays must be contiguous and have a size fixed in advance.',
          max: 2,
        },
        {
          id: 'r2',
          label: 'Copying cost',
          description: 'Explains that each resize copies all existing values to new memory.',
          max: 2,
        },
        {
          id: 'r3',
          label: 'Scale',
          description:
            'Connects the slowdown to the large number of values and the frequent resizes.',
          max: 2,
        },
      ],
    },
    hints: [
      'Think about what has to happen to the old readings each time the array grows.',
      'How often does this program resize, and how many values move each time?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        'Arrays require contiguous memory and have a fixed allocated capacity. Growing this array by just one slot means that every reading after the first 1,000 triggers allocation and copying of all existing readings. An addition with n readings already stored therefore takes O(n) time, and the repeated copying accumulates to O(N²) work over N readings. As the collection grows, each new addition copies more data.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'linked_lists',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [5, 6, 7],
    publicPayload: {
      stem: "You have a sorted singly linked list of n values, with only a pointer to the first node. Why can't you get O(log n) binary search on it?",
      options: [
        {
          id: 'a',
          text: 'To find the middle, you must start at the beginning and follow pointers node by node, which takes O(n) steps.',
        },
        {
          id: 'b',
          text: 'Binary search requires the data to be unsorted, and linked lists are always sorted.',
        },
        {
          id: 'c',
          text: 'Linked list nodes cannot store integers, only pointers.',
        },
        {
          id: 'd',
          text: 'Binary search works on a linked list, but only after converting it to a doubly linked list.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'a',
      explanation:
        'The nodes are scattered in memory and connected only by pointers. There is no arithmetic that jumps to the middle. You must traverse from the start to learn the length, then traverse again to reach the halfway point, and repeat this for each half. Just finding the middle already costs O(n).',
    },
    distractorMeta: {
      b: {
        misconception: "Reverses binary search's sortedness precondition.",
        whyWrong:
          'Binary search requires sorted data. The problem is reaching the middle, not the ordering.',
      },
      c: {
        misconception: 'Misremembers what a node contains.',
        whyWrong: 'Each node holds a value, such as an int, plus a pointer to the next node.',
      },
      d: {
        misconception: 'Believes doubly linked lists restore fast search.',
        whyWrong:
          'Adding backward pointers simplifies some code but does not change the speed. You still cannot jump to the middle.',
      },
    },
    rubric: null,
    hints: [
      'Consider how you would actually reach the middle node if all you have is a pointer to the start.',
      'Is there any way to compute where the middle node is in memory, the way you can with an array?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'a',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'linked_lists',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [8],
    publicPayload: {
      stem: 'A programmer switches a singly linked list to a doubly linked list, where each node has pointers to both the next and the previous node. What is the main effect?',
      options: [
        {
          id: 'a',
          text: 'Searching becomes O(log n) because you can move in both directions.',
        },
        {
          id: 'b',
          text: 'The list no longer needs to allocate a node for each value.',
        },
        {
          id: 'c',
          text: 'Some insert and delete code becomes simpler to write, but the running times stay the same.',
        },
        {
          id: 'd',
          text: 'The list now stores its nodes contiguously, like an array.',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        'With pointers going both ways, you no longer need to look ahead to find what to free or where to insert, so the code is easier to write. However, searching, inserting and deleting are still O(n), so the speed does not fundamentally change.',
    },
    distractorMeta: {
      a: {
        misconception: 'Thinks bidirectional traversal enables binary search.',
        whyWrong:
          'You still cannot jump to the middle without walking node by node, so search remains O(n).',
      },
      b: {
        misconception: 'Confuses adding pointers with changing the allocation strategy.',
        whyWrong: 'Every value still gets its own node. Each node just carries one more pointer.',
      },
      d: {
        misconception: 'Believes extra pointers force contiguous layout.',
        whyWrong:
          'The nodes can still be anywhere in memory. Pointers connect them, not adjacency.',
      },
    },
    rubric: null,
    hints: [
      'Separate two questions: is the code easier to write, and is it faster in big-O terms?',
      'Does moving backward help you reach the middle of the list any faster?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'linked_lists',
    kind: 'spot_flaw',
    variant: 1,
    segs: [0, 8],
    publicPayload: {
      sentences: [
        'A linked list allocates a new node for each value and connects the nodes with pointers.',
        'This lets the list grow and shrink without copying existing values to a new location.',
        'Making it a doubly linked list, with pointers in both directions, lets you search a sorted list in O(log n).',
        'Without that, searching, inserting and deleting in a singly linked list are all O(n).',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary: 'Claims that doubly linked lists enable logarithmic search.',
      correction:
        "A doubly linked list makes some code simpler, because you don't have to look ahead to insert or free nodes. It doesn't change the speed: search is still O(n), because you still have to walk node by node to reach the middle.",
      explanation:
        "Backward pointers don't let you jump to the middle of the list. Binary search stays unavailable, and the running times are unchanged.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Corrects the speed claim',
          description: 'States that search remains O(n) in a doubly linked list.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'States the real benefit',
          description:
            'Notes that the benefit is simpler code, or explains that finding the middle still requires traversal.',
          max: 2,
        },
      ],
    },
    hints: [
      'Look closely at what extra pointers can and cannot change.',
      'Does moving backward let you reach the middle node without walking through the list?',
    ],
    leakKeywords: ['doubly', 'O(log n)', 'both directions'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'linked_lists',
    kind: 'spot_flaw',
    variant: 2,
    segs: [1, 4, 5],
    publicPayload: {
      sentences: [
        'Arrays force us to pick a size in advance, which is why linked lists are appealing.',
        'With a linked list, we allocate one node at a time as each new value arrives.',
        'Because each node must be placed right after the previous node in memory, a linked list cannot make use of fragmented memory.',
        'The price we pay is that searching, inserting and deleting are all O(n).',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        "Claims that linked list nodes must be contiguous and so can't use fragmented memory.",
      correction:
        'Linked list nodes can live anywhere in memory, because pointers connect them. That is exactly why linked lists can make efficient use of fragmented memory, such as a few bytes here and a few bytes there.',
      explanation:
        'Contiguity is a requirement of arrays, not linked lists. Pointers let nodes stay wherever they were allocated, so a list can use scattered free chunks of memory.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Rejects contiguity',
          description: 'States that nodes need not be adjacent in memory.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Explains the role of pointers',
          description:
            'Explains that pointers link the nodes, which allows the list to use fragmented memory.',
          max: 2,
        },
      ],
    },
    hints: [
      'Which data structure actually requires its elements to be back to back?',
      'What connects one node to the next?',
    ],
    leakKeywords: ['contiguous', 'right after', 'fragmented'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'linked_lists',
    kind: 'transfer',
    variant: 1,
    segs: [0, 4, 5, 6, 7, 9],
    publicPayload: {
      prompt:
        "A music app keeps a user's songs sorted by title and has to look songs up by title often. A developer proposes storing the songs in a sorted singly linked list instead of a sorted array, so that adding songs never requires copying the whole collection. Explain what the app gains and what it loses in terms of running time.",
    },
    answerKey: {
      modelSolution:
        'Gain: each new song gets its own node, linked in by updating pointers. The collection can grow or shrink without reallocating or copying existing songs, and it can use fragmented memory. Loss: looking up a title becomes O(n). Even though the list is sorted, binary search no longer works, because finding the middle requires walking from the first node. A sorted array allows O(log n) binary search, but the linked list makes search, insertion and deletion all O(n).',
      explanation:
        'This tests the core linked list trade-off: dynamic growth without copying, in exchange for losing binary search and having O(n) operations.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'r1',
          label: 'Dynamism gained',
          description:
            'Notes that nodes are allocated per value and linked by pointers, so no copying is needed.',
          max: 2,
        },
        {
          id: 'r2',
          label: 'Search cost',
          description:
            'States that search becomes O(n), compared with O(log n) for a sorted array.',
          max: 2,
        },
        {
          id: 'r3',
          label: 'Reason',
          description:
            'Explains that binary search is lost because reaching the middle requires traversing from the start.',
          max: 2,
        },
      ],
    },
    hints: [
      'Compare how each structure handles adding an element and how each finds an element.',
      'Even though the list is sorted, can you jump to its middle?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        'The linked list gains dynamic growth: adding a node does not require relocating and copying the existing collection. However, inserting in sorted order still takes O(n) time to find the insertion position. The app loses efficient binary search: title lookup is O(n) in the linked list rather than O(log n) in a sorted array, because reaching a middle element requires traversing links.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'binary_search_trees',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [30, 31, 32, 33, 34],
    publicPayload: {
      stem: 'A binary search tree is built naively, with no rebalancing, by inserting 1, then 2, 3, 4, 5 and 6 in that order. What does the resulting structure look like, and what is the running time of searching it?',
      options: [
        {
          id: 'a',
          text: 'A balanced tree with 1 at the root, so search is O(log n)',
        },
        {
          id: 'b',
          text: 'A balanced tree with 3 or 4 at the root, because insertion always puts the middle value at the top, so search is O(log n)',
        },
        {
          id: 'c',
          text: 'A long chain where each node has only a right child, effectively a linked list, so search is O(n)',
        },
        {
          id: 'd',
          text: 'An invalid binary search tree, because each node must have both a left and a right child',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        'Each new value is larger than every value already in the tree, so it always goes to the right of the last node. The tree becomes long and stringy. It still satisfies the BST property, but it is really a linked list in one dimension, so search degrades to O(n) unless the tree is rebalanced.',
    },
    distractorMeta: {
      a: {
        misconception: 'Any BST automatically has logarithmic height.',
        whyWrong: 'O(log n) requires a balanced tree. With sorted input the height becomes n.',
      },
      b: {
        misconception: 'Naive insertion reorganizes the tree to keep the middle value at the root.',
        whyWrong:
          'Only rebalancing algorithms pivot nodes around. Naive insertion just attaches each new node where it falls.',
      },
      d: {
        misconception: 'A BST requires every node to have two children.',
        whyWrong:
          'Nodes may have zero, one or two children. The stringy tree does not violate the BST definition.',
      },
    },
    rubric: null,
    hints: [
      'Think about where each new value must go relative to the values already in the tree.',
      'Every new value is bigger than everything inserted before it. Which side does it always end up on?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'binary_search_trees',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [24, 25, 26, 28, 29],
    publicPayload: {
      stem: 'In a recursive C function bool search(node *tree, int number) on a binary search tree, what should happen when tree is not NULL and number < tree->number?',
      options: [
        {
          id: 'a',
          text: 'Return search(tree->left, number)',
        },
        {
          id: 'b',
          text: 'Return search(tree->right, number)',
        },
        {
          id: 'c',
          text: 'Return false, because the number is smaller than the current node',
        },
        {
          id: 'd',
          text: 'Search both tree->left and tree->right, and return true if either finds it',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'a',
      explanation:
        'By the BST property, smaller values live in the left subtree. The function can therefore cut off the right subtree and recursively search tree->left for the same number. The other cases are: a NULL tree returns false, a larger number searches right, and an equal number returns true.',
    },
    distractorMeta: {
      b: {
        misconception: 'Confusing which side of the tree holds smaller values.',
        whyWrong: 'Each node is less than its right child, so smaller values are on the left.',
      },
      c: {
        misconception: 'A mismatch at the current node means the value is absent.',
        whyWrong:
          'The value may still be in the left subtree. The function returns false only when it reaches a NULL tree.',
      },
      d: {
        misconception: 'BST search must explore every branch.',
        whyWrong:
          'Searching both subtrees throws away the halving advantage that makes BST search O(log n).',
      },
    },
    rubric: null,
    hints: [
      'Remember how a node compares to its left child and to its right child.',
      'Which subtree can be safely snipped off when the target is smaller than the current node?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'a',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'binary_search_trees',
    kind: 'spot_flaw',
    variant: 1,
    segs: [14, 17, 18, 19, 31, 32, 33, 34],
    publicPayload: {
      sentences: [
        'A binary search tree node stores a number plus a left pointer and a right pointer.',
        'Every node is greater than its left child and less than its right child, and this property holds recursively for every subtree.',
        'Because the tree grows just by updating pointers, inserting values in any order automatically keeps it balanced, with height about log2 n.',
        'When searching, comparing the target with a node lets us ignore an entire subtree, much like tearing a phone book in half.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'Naive insertion does not keep the tree balanced. Inserting values in sorted order produces a long chain, effectively a linked list, with O(n) height.',
      correction:
        'Insertion order matters. Sorted input makes a naive BST devolve into a linked list with O(n) operations. A logarithmic height is maintained only if the tree is rebalanced on insertion or deletion.',
      explanation:
        'Updating pointers avoids copying data, but it does nothing to ensure balance. If values arrive as 1, 2, 3, 4…, each one becomes the right child of the previous node. The tree turns into a stringy linked list, and search degrades to O(n). Rebalancing techniques can pivot nodes to restore logarithmic height.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flaw',
          description: 'Points out that insertion order can unbalance a naive BST.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct consequence and fix',
          description:
            'States that a degenerate tree gives O(n) operations, and that rebalancing keeps the height logarithmic.',
          max: 2,
        },
      ],
    },
    hints: [
      'Is there an input order that would make the tree look very different from a nicely balanced picture?',
      'Imagine inserting 1, 2, 3, 4, 5, 6 one after another.',
    ],
    leakKeywords: ['sorted order', 'linked list', 'rebalance', 'devolve', 'stringy'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'binary_search_trees',
    kind: 'spot_flaw',
    variant: 2,
    segs: [20, 21, 22, 23, 25, 26, 28],
    publicPayload: {
      sentences: [
        'Compared with an array of ints, a binary search tree uses roughly three times as much memory, since each node holds an int and two pointers.',
        'In exchange, inserting a new value only requires updating pointers, rather than copying the whole data set to a new location.',
        "A recursive search returns false when handed a NULL tree, searches the left subtree when the target is smaller than the node's number, and searches the right subtree when it is larger.",
        "If none of those cases applies, the target must equal the node's number, so the function returns true.",
      ],
    },
    answerKey: {
      hasFlaw: false,
      flawSentenceIdx: null,
      flawSummary: null,
      correction: null,
      explanation:
        'Every sentence is correct. Each node stores one piece of data and two pointers, which is about three times the space of a bare int. In return, the tree grows dynamically through pointer updates instead of reallocation and copying. The recursive search has exactly four cases: NULL returns false, smaller goes left, larger goes right, and otherwise the value was found, so it returns true.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Recognizes correctness',
          description: 'Concludes that the explanation has no flaw.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Justification',
          description: 'Briefly confirms the memory trade-off and the four search cases.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check each claim against what a BST node contains and how recursive search proceeds.',
      'Count the possible cases in recursive search, and make sure each one is handled correctly.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'correct',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'binary_search_trees',
    kind: 'transfer',
    variant: 1,
    segs: [15, 16, 17, 18, 19, 31, 32, 33, 34],
    publicPayload: {
      prompt:
        "A student inserts the values 50, 30, 70, 20, 40, 60, 80 into an initially empty binary search tree, without any rebalancing. A second student inserts the same seven values in the order 20, 30, 40, 50, 60, 70, 80. Describe the shape of each resulting tree, and give the worst-case number of comparisons needed to search for 80 in each. What would you recommend so that the second student's tree performs like the first?",
    },
    answerKey: {
      modelSolution:
        'First tree: 50 is the root, with 30 and 70 as its children, and 20, 40, 60 and 80 as leaves. It is a balanced tree of height about log2 7, so finding 80 takes 3 comparisons (50, 70, 80). Second tree: each value is larger than the previous ones, so every node is the right child of the one before. The tree is a chain, effectively a linked list, and finding 80 takes 7 comparisons, which is O(n). The fix is a self-balancing approach that rebalances on insertion, for example pivoting so that a middle value becomes the root. This keeps the height logarithmic and search at O(log n).',
      explanation:
        "This applies the BST property and shows that insertion order determines the tree's height. A balanced tree gives O(log n) search, while sorted insertion gives O(n) search.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Tree shapes',
          description: 'Correctly describes the balanced tree and the right-leaning chain.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Comparison counts',
          description:
            'Gives about 3 comparisons for the first tree and 7 for the second, linking them to O(log n) and O(n).',
          max: 2,
        },
        {
          id: 'c3',
          label: 'Remedy',
          description:
            'Recommends rebalancing on insertion, for example pivoting nodes, to maintain logarithmic height.',
          max: 2,
        },
      ],
    },
    hints: [
      'Place each value by comparing it with the root, then go left or right.',
      'In the second order, every new value is bigger than all the values already in the tree.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        'The first tree is balanced: root 50; children 30 and 70; 30 has children 20 and 40, and 70 has children 60 and 80. Searching for 80 visits 50, 70, and 80: 3 node comparisons. The second tree is a right-only chain, 20 → 30 → 40 → 50 → 60 → 70 → 80, requiring 7 node comparisons. Use a self-balancing BST that rebalances after updates to maintain logarithmic height.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'hash_functions',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [43, 44, 45],
    publicPayload: {
      stem: 'A hash function is defined as: unsigned int hash(const string name) { return toupper(name[0]) - \'A\'; }. What does hash("luigi") return?',
      options: [
        {
          id: 'a',
          text: '12',
        },
        {
          id: 'b',
          text: "76, the ASCII value of 'L'",
        },
        {
          id: 'c',
          text: "43, because lowercase 'l' minus 'A' is computed directly",
        },
        {
          id: 'd',
          text: '11',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        "toupper converts 'l' to 'L', which is ASCII 76. Subtracting 'A' (65) gives 11. L is the 12th letter, but buckets are counted from 0, so its index is 11.",
    },
    distractorMeta: {
      a: {
        misconception: "Mixing up Luigi's bucket with Mario's, or counting letters from 1.",
        whyWrong:
          'L is the 12th letter, so with 0-based buckets its index is 11. Mario, starting with M, maps to 12.',
      },
      b: {
        misconception: "Forgetting to subtract 'A'.",
        whyWrong:
          'The function subtracts 65 from the ASCII value, which shifts letters into the range 0 to 25.',
      },
      c: {
        misconception: 'Ignoring the effect of toupper.',
        whyWrong:
          'toupper converts the lowercase letter to uppercase before the subtraction, so the result stays in the range 0 to 25.',
      },
    },
    rubric: null,
    hints: [
      'Trace what toupper does to the first character before the subtraction happens.',
      "Work out 'L' minus 'A' in ASCII, keeping in mind that buckets start at 0.",
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'hash_functions',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [58, 59, 60, 61],
    publicPayload: {
      stem: 'A hash table hashes names by their first letter into 26 buckets. A programmer changes it to hash on the first three letters, using one bucket for every combination from AAA to ZZZ. What is the main effect of this change?',
      options: [
        {
          id: 'a',
          text: 'It eliminates collisions for every possible set of names, at no extra cost',
        },
        {
          id: 'b',
          text: 'It reduces the likelihood of collisions, but it needs vastly more buckets, many of which, like AAA, will sit unused',
        },
        {
          id: 'c',
          text: 'It increases collisions, because three letters are more likely to match than one',
        },
        {
          id: 'd',
          text: "It shrinks the memory needed, because each bucket's linked list becomes shorter",
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        'Using more letters spreads names across many more buckets, so collisions become less probable. This is the trade-off: it takes 26 × 26 × 26 buckets, and many combinations never correspond to a real name. A great deal of memory is wasted.',
    },
    distractorMeta: {
      a: {
        misconception: 'A finer hash function guarantees no collisions and has no downside.',
        whyWrong:
          'The range is still finite, so collisions remain possible. The memory cost is also huge.',
      },
      c: {
        misconception: 'Matching on more characters makes collisions more likely.',
        whyWrong:
          'Two names must now share all three leading letters to collide, which is less likely than sharing one.',
      },
      d: {
        misconception: 'Shorter chains mean less total memory.',
        whyWrong:
          'The array of buckets grows enormously. The node count stays the same, so total memory goes up.',
      },
    },
    rubric: null,
    hints: [
      'Think about both sides of the trade-off: collisions and space.',
      'How many buckets does a three-letter scheme require, and will they all be used?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'hash_functions',
    kind: 'spot_flaw',
    variant: 1,
    segs: [37, 50, 53, 55, 57, 61, 62],
    publicPayload: {
      sentences: [
        'Hashing maps an infinite domain of inputs, such as all possible names, to a finite range of outputs, such as 26 bucket indices.',
        "A hash table built this way is an array of linked lists: each name is hashed to a bucket and then added to that bucket's chain.",
        'Because many names must share only 26 outputs, collisions are inevitable, so several names can end up in the same chain.',
        'If names are spread evenly across the 26 buckets, each chain holds about n/26 names, so search becomes asymptotically faster than O(n).',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        'O(n/k) with a constant k such as 26 is still O(n). Search is faster in practice, but it is not asymptotically better.',
      correction:
        'Each chain holds about n/26 names, so search is roughly 26 times faster in practice. Since 26 is a constant, however, O(n/26) is still O(n) asymptotically.',
      explanation:
        'Big-O notation drops constant factors. Dividing the work among k buckets speeds up real-world search by a factor of k, but the time still grows linearly with n. That makes it O(n), not something asymptotically faster.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flaw',
          description: 'Recognizes that O(n/26) is not asymptotically better than O(n).',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Explains why',
          description:
            'Notes that big O ignores constant factors, while acknowledging the practical speedup.',
          max: 2,
        },
      ],
    },
    hints: [
      'Think about how big-O notation treats constant factors.',
      'Is dividing n by a fixed number like 26 enough to change the growth rate?',
    ],
    leakKeywords: ['constant factor', 'still O(n)', 'asymptotically', '26 times faster'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'hash_functions',
    kind: 'spot_flaw',
    variant: 2,
    segs: [44, 45, 46, 47],
    publicPayload: {
      sentences: [
        "A simple hash function returns toupper(name[0]) - 'A', which gives a value from 0 to 25 for an English name.",
        'Calling toupper first keeps the subtraction correct even if the name starts with a lowercase letter.',
        "Marking the parameter const means the function receives its own private copy of the name, so the caller's string is protected.",
        'Returning an unsigned int documents that a bucket index should never be negative.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'const does not make a copy. The name is still passed by reference, and const only prevents the function from changing it.',
      correction:
        "Marking the parameter const means the function still receives a reference to the caller's string, not a copy, but it is not allowed to modify that string.",
      explanation:
        "A string in C is passed as an address, so the function could reach into the caller's memory and alter the name. Adding const keeps that reference-passing behavior and simply forbids changing the value. It is a defensive refinement, just like returning an unsigned int.",
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies the flaw',
          description: 'Recognizes that const does not create a copy of the argument.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct meaning of const',
          description:
            'Explains that the name is still passed by reference, and that const prevents the function from modifying it.',
          max: 2,
        },
      ],
    },
    hints: [
      'Think about how a string is actually passed to a function in C.',
      'Does const change how the argument is passed, or only what the function is allowed to do with it?',
    ],
    leakKeywords: ['copy', 'by reference', 'by value', 'modify'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'hash_tables',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [57, 58, 61, 62],
    publicPayload: {
      stem: 'A contacts app stores n names in a hash table with 26 buckets, one per first letter, and handles collisions by chaining. Assuming names are spread evenly across the letters, what is the asymptotic running time of searching for a name?',
      options: [
        {
          id: 'a',
          text: 'O(1), because the hash function jumps straight to the right bucket',
        },
        {
          id: 'b',
          text: 'O(log n), because the buckets are in alphabetical order',
        },
        {
          id: 'c',
          text: 'O(n), because each chain holds about n/26 names and constant factors drop out',
        },
        {
          id: 'd',
          text: 'O(26n), because there are 26 buckets that might each need to be searched',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'c',
      explanation:
        "Hashing finds the right bucket in one step, but you then have to walk that bucket's linked list. With k buckets and evenly spread names, each chain holds about n/k names. That is faster in practice, roughly 26 times faster than a single linked list. Asymptotically, though, O(n/k) is still O(n).",
    },
    distractorMeta: {
      a: {
        misconception: 'Hash table lookup is always O(1)',
        whyWrong:
          'Jumping to the bucket takes constant time, but collisions create chains that must be searched linearly. The chain length grows with n.',
      },
      b: {
        misconception: 'Alphabetically ordered buckets allow binary search.',
        whyWrong:
          'Each bucket is a linked list, and linked lists do not support binary search. Nothing about the structure halves the problem.',
      },
      d: {
        misconception: 'Every bucket must be scanned on each lookup.',
        whyWrong:
          'The hash function picks exactly one bucket, so only one chain of about n/26 names is searched. In any case, O(26n) is not the standard simplified form.',
      },
    },
    rubric: null,
    hints: [
      'Think about what happens after the hash function picks a bucket.',
      'How long is each chain relative to n, and what does big O do with a constant divisor?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'c',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'hash_tables',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [50, 52, 53, 54, 55],
    publicPayload: {
      stem: 'A hash table maps names to 26 buckets by first letter. Mario is already stored at index 12, and a new contact, Morton, also hashes to index 12. In the design described for this hash table, what happens?',
      options: [
        {
          id: 'a',
          text: 'Morton replaces Mario at index 12',
        },
        {
          id: 'b',
          text: 'Morton is added to the linked list at index 12, chained together with Mario',
        },
        {
          id: 'c',
          text: 'Morton is placed in the next empty bucket, such as index 13',
        },
        {
          id: 'd',
          text: 'The array is reallocated with more buckets so Morton gets his own slot',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'b',
      explanation:
        'Each bucket is a pointer to the head of a linked list. When two keys collide, the new node is simply stitched into the chain at the hashed location. Nothing is deleted, and the structure stays organized by bucket.',
    },
    distractorMeta: {
      a: {
        misconception: 'A collision overwrites the existing entry.',
        whyWrong: 'Clobbering the existing value loses data. Chaining keeps both names.',
      },
      c: {
        misconception: 'Colliding entries should spill into neighboring buckets.',
        whyWrong:
          'In this design, spilling into other buckets removes any rhyme or reason about who is where. Searches would devolve into linear scans across buckets. Chaining avoids that.',
      },
      d: {
        misconception: 'Collisions require growing the array.',
        whyWrong:
          'The array stays at 26 pointers. Collisions are absorbed by the linked lists, not by resizing.',
      },
    },
    rubric: null,
    hints: [
      'Recall what each array element in this hash table actually points to.',
      'The data structure combines an array with another structure you already know.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'b',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'hash_tables',
    kind: 'spot_flaw',
    variant: 1,
    segs: [55, 57, 58, 61, 62],
    publicPayload: {
      sentences: [
        'A hash table is an array of buckets, where each bucket points to the head of a linked list.',
        'The hash function turns a key, such as a name, into an index, for example by taking its first letter so that names map to 0 through 25.',
        'When two names hash to the same index, the new node is simply chained onto the linked list in that bucket.',
        'Because the hash function jumps straight to the right bucket, a hash table lookup always takes O(1) time no matter how many names are stored.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 3,
      flawSummary:
        'The scenario claims a hash table lookup always takes O(1) time, ignoring that collisions create chains that must be searched linearly.',
      correction:
        'Jumping to the bucket is constant time, but collisions make chains. With k buckets the chains hold about n/k entries, which is still O(n) asymptotically, and the worst case is O(n).',
      explanation:
        'Hashing finds the bucket in one step, but the linked list in that bucket must then be searched. With collisions, chains grow with n. Even with an even spread, O(n/k) simplifies to O(n), so constant time is not guaranteed.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Identifies collisions',
          description:
            'Explains that collisions produce chains in a bucket that must be traversed.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Correct complexity',
          description: 'States that the lookup is O(n/k), which is O(n), rather than always O(1).',
          max: 2,
        },
      ],
    },
    hints: [
      'Is finding the bucket the whole cost of a lookup?',
      'Consider what is inside a bucket once several names collide.',
    ],
    leakKeywords: ['collision', 'chain', 'O(n)', 'n/k', 'worst case'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'hash_tables',
    kind: 'spot_flaw',
    variant: 2,
    segs: [50, 51, 52, 55, 57, 61, 62],
    publicPayload: {
      sentences: [
        'A hash table can be built as an array of buckets, such as 26 pointers to nodes, one for each letter of the alphabet, with each pointer heading a linked list.',
        'When two names hash to the same bucket, such as Mario and another name starting with M, the new name is chained onto the linked list at that location instead of overwriting the existing entry.',
        'If the names are spread uniformly across k buckets, each chain holds roughly n/k names.',
        'That makes searching about k times faster than one long linked list in practice, but O(n/k) is still O(n) asymptotically because k is a constant.',
        'So a hash table that hashes on the first letter does not guarantee constant-time lookup.',
      ],
    },
    answerKey: {
      hasFlaw: false,
      flawSentenceIdx: null,
      flawSummary: null,
      correction: null,
      explanation:
        'Every sentence is correct. A hash table is an array of linked lists, and collisions are handled by chaining at the hashed index. With k buckets and a uniform distribution, chains have about n/k entries. That is faster in practice, but dropping the constant factor still leaves O(n). So lookup is not guaranteed to be O(1).',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'verdict',
          label: 'Correct verdict',
          description: 'States that the explanation contains no conceptual error.',
          max: 2,
        },
        {
          id: 'justification',
          label: 'Justifies the complexity claim',
          description:
            'Explains why O(n/k) simplifies to O(n), noting that k is a constant, and that chaining is how collisions are handled.',
          max: 2,
        },
      ],
    },
    hints: [
      'Check each claim against how collisions are resolved and how big-O treats constant factors.',
      'Ask whether dividing n by a fixed number like 26 changes the asymptotic class.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'correct',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'hash_tables',
    kind: 'transfer',
    variant: 1,
    segs: [59, 60, 61, 62],
    publicPayload: {
      prompt:
        'A library stores 10,000 book titles in a hash table with 26 buckets, hashing on the first letter of each title and chaining collisions in linked lists. (1) Assuming titles are evenly spread across the letters, about how many titles must be checked in the worst case to find a title? What is the big-O running time? (2) A colleague suggests hashing on the first two letters instead, giving 676 buckets. What does this gain, and what does it cost?',
    },
    answerKey: {
      modelSolution:
        '(1) Each chain holds about 10,000 / 26, or roughly 385 titles, so a search may check about 385 titles. That is about 26 times faster than a single linked list, but O(n/k) is still O(n) asymptotically. (2) With 676 buckets, chains average about 15 titles, so collisions become rarer and searches get faster in practice. The cost is much more memory for the array, and many buckets, such as those for QX or ZZ, will sit empty and wasted. With chaining, the asymptotic bound is still O(n).',
      explanation:
        'This applies the n/k analysis of chained hash tables. It also applies the tension between reducing collisions with a finer hash function and wasting memory on rarely used buckets.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'r1',
          label: 'Chain length',
          description: 'Computes about n/26, or roughly 385, entries per chain.',
          max: 2,
        },
        {
          id: 'r2',
          label: 'Asymptotic class',
          description: 'States that O(n/k) is still O(n), not O(1).',
          max: 2,
        },
        {
          id: 'r3',
          label: 'Trade-off',
          description:
            'Explains that more buckets mean fewer collisions but more memory, with many empty buckets.',
          max: 2,
        },
      ],
    },
    hints: [
      'Divide the data among the buckets.',
      'Think about which two-letter combinations real titles would rarely start with.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        '(1) About 10,000/26 ≈ 385 titles in the worst case: search may inspect the entire target bucket’s linked list. With a fixed 26 buckets, the running time is O(n). (2) Using 676 buckets reduces collisions and, if titles remain evenly distributed, reduces the worst-case chain length to about 10,000/676 ≈ 15 titles. It costs more memory for bucket pointers—26 times as many—and potentially wastes space on empty buckets. With a fixed 676 buckets, search is still O(n) asymptotically.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'tries',
    kind: 'diagnostic_mcq',
    variant: 1,
    segs: [68, 69, 70],
    publicPayload: {
      stem: 'A trie stores the names of characters, and you look up "toad". The trie currently holds 3 names. Later it holds 3 million names. How does the number of pointer steps for looking up "toad" change?',
      options: [
        {
          id: 'a',
          text: 'It grows linearly, because there are more names to compare against',
        },
        {
          id: 'b',
          text: 'It grows logarithmically, like in a balanced binary search tree',
        },
        {
          id: 'c',
          text: 'It grows a little, because more names share the T node',
        },
        {
          id: 'd',
          text: 'It stays at 4 steps, one per letter, regardless of how many names are stored',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'd',
      explanation:
        'A trie lookup follows one pointer per letter of the key. For "toad" that is T, O, A, D, and then a check of the end-of-name marker. The number of other names stored is irrelevant. Names have a reasonable maximum length, so lookup is effectively O(1).',
    },
    distractorMeta: {
      a: {
        misconception: 'Lookup compares the key against stored names.',
        whyWrong:
          'A trie never compares against other names. It indexes directly into an array by letter.',
      },
      b: {
        misconception:
          "Every tree lookup takes time proportional to the tree's height in terms of n.",
        whyWrong:
          "A trie's depth depends on the length of the key, not on the number of keys stored.",
      },
      c: {
        misconception: 'Shared prefix nodes become slower to traverse as they fill up.',
        whyWrong:
          'Each node is a fixed array of 26 pointers. Indexing into it is constant time no matter how many children are non-null.',
      },
    },
    rubric: null,
    hints: [
      'What determines how many nodes you visit during a trie lookup?',
      'Count the letters in the key.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'd',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'tries',
    kind: 'diagnostic_mcq',
    variant: 2,
    segs: [73, 74, 75],
    publicPayload: {
      stem: 'Tries achieve effectively constant-time lookup, yet hash tables are used far more often in practice. What is the main trade-off of a trie?',
      options: [
        {
          id: 'a',
          text: 'Each node holds 26 pointers, most of which are null, so tries use a huge amount of memory',
        },
        {
          id: 'b',
          text: 'Tries cannot store names that are prefixes of other names',
        },
        {
          id: 'c',
          text: 'Trie lookups degrade to O(n) when many names share a first letter',
        },
        {
          id: 'd',
          text: 'Tries must store each full name as a string in every node along its path',
        },
      ],
    },
    answerKey: {
      correctOptionId: 'a',
      explanation:
        'Every trie node is an array of 26 child pointers plus a boolean or value. For any real set of names, most of those pointers are null and unused. The result is a great deal of wasted memory, which is the price paid for constant-time lookup.',
    },
    distractorMeta: {
      b: {
        misconception: 'Prefix names conflict in a trie.',
        whyWrong:
          'A boolean marker records where a name ends. That lets toad and toadette coexist on the same path.',
      },
      c: {
        misconception: 'Tries suffer from collisions the way hash tables do.',
        whyWrong:
          'Names that share a first letter simply share a node. Lookup still follows one pointer per letter.',
      },
      d: {
        misconception: 'Tries store keys explicitly.',
        whyWrong:
          'Names are stored implicitly as a path of non-null pointers. There is no char array holding the name.',
      },
    },
    rubric: null,
    hints: [
      'Think about what each node contains and how much of it is actually used.',
      'Picture a node for the second letter after T. How many of its 26 slots are really needed?',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'a',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'tries',
    kind: 'spot_flaw',
    variant: 1,
    segs: [64, 65, 66, 67],
    publicPayload: {
      sentences: [
        'A trie is a tree in which each node is an array of 26 pointers, one for each letter from A to Z.',
        'To insert toad, you follow or create the pointer for T at the root, then the pointer for O, then A, then D.',
        'At the final node, the full string "toad" is copied into a char array so that lookups can confirm the match.',
        'Toadette can then reuse the same T, O, A and D path before adding nodes for its remaining letters.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'The scenario claims the name is stored explicitly as a string. In a trie, names are stored implicitly by the path of non-null pointers plus a boolean or value marking where a name ends.',
      correction:
        'At the end of the path, a boolean is set to true, or a value such as a phone number is stored, to mark that a name ends there. The word itself is never stored as a string.',
      explanation:
        'In a trie, the key is represented by the sequence of non-null pointers from the root. An end marker, either a boolean or a value, says that a name ends at that node. No char array holding "toad" exists in the structure.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Implicit storage',
          description:
            'Explains that names are represented by the path of pointers, not stored as strings.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'End marker',
          description: 'Mentions the boolean or value that marks the end of a name.',
          max: 2,
        },
      ],
    },
    hints: [
      'Ask yourself whether a trie ever needs the whole word written anywhere.',
      'How does a trie know that a name ends at a particular node?',
    ],
    leakKeywords: ['implicit', 'boolean', 'path', 'no string stored'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'tries',
    kind: 'spot_flaw',
    variant: 2,
    segs: [65, 66, 67, 71],
    publicPayload: {
      sentences: [
        'Each trie node contains an array of 26 child pointers plus a boolean marking whether a name ends at that node.',
        'Names that share a prefix, like toad and tom, share the nodes for their common letters.',
        'Because toad is a prefix of toadette, the trie can tell that toad is stored simply because the pointers for T, O, A and D are all non-null, without needing any end marker.',
        'Lookup follows one pointer per letter, so its cost does not depend on how many names are stored.',
      ],
    },
    answerKey: {
      hasFlaw: true,
      flawSentenceIdx: 2,
      flawSummary:
        'The scenario claims that a non-null path alone proves a name is stored. When one name is a prefix of another, the path exists for both, so a boolean end marker is required.',
      correction:
        'The path for T, O, A, D exists whenever toadette is stored, even if toad is not. A boolean, or a value, at the D node must be set to true to indicate that toad itself ends there.',
      explanation:
        'Storing toadette creates non-null pointers for T, O, A and D, so the existence of that path cannot distinguish whether toad is also stored. The boolean flag at the node is what marks that a name ends there. This is why tries can hold names that are prefixes of other names.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'c1',
          label: 'Path is insufficient',
          description:
            'Notes that a longer name creates the same path, so the path alone is ambiguous.',
          max: 2,
        },
        {
          id: 'c2',
          label: 'Boolean marker',
          description: 'States that a boolean or value must mark the end of toad.',
          max: 2,
        },
      ],
    },
    hints: [
      'Imagine the trie holds toadette but not toad.',
      'What extra field does each node have besides its 26 pointers?',
    ],
    leakKeywords: ['boolean', 'end marker', 'prefix', 'flag'],
    verification: {
      verdict: 'pass',
      solvedAnswer: 'flawed',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
  {
    concept: 'tries',
    kind: 'transfer',
    variant: 1,
    segs: [65, 66, 67, 69, 70],
    publicPayload: {
      prompt:
        'You insert the words "cat", "car" and "cart" into a trie whose nodes each have 26 child pointers and a boolean. (1) Which letters\' nodes are shared among these words? (2) Where are the booleans set to true? (3) Does a lookup of "ca" report the word as present? (4) How many pointer steps does it take to look up "cart", and would this change if the trie held a million other words?',
    },
    answerKey: {
      modelSolution:
        '(1) All three words share the path C then A. "car" and "cart" also share R. (2) The booleans are true at the end of "cat" (the T node), at the end of "car" (the R node) and at the end of "cart" (the T node below R). (3) No. The path C, A exists, but no boolean marks a word ending there, so "ca" is not found. (4) Looking up "cart" takes 4 steps, one per letter. This would not change with a million other words, because lookup depends only on the length of the key, which makes it effectively O(1).',
      explanation:
        'This tests prefix sharing, the role of end-of-word booleans in distinguishing a stored word from a mere path, and the fact that lookup cost depends on key length, not on the number of keys.',
    },
    distractorMeta: null,
    rubric: {
      criteria: [
        {
          id: 'r1',
          label: 'Sharing and markers',
          description:
            'Correctly identifies the shared prefix nodes and where the booleans are true.',
          max: 2,
        },
        {
          id: 'r2',
          label: 'Prefix lookup',
          description: 'Explains that "ca" is not found because no end marker is set there.',
          max: 2,
        },
        {
          id: 'r3',
          label: 'Constant time',
          description: 'States 4 steps, independent of the number of stored words.',
          max: 2,
        },
      ],
    },
    hints: [
      'Trace each word letter by letter from the root.',
      'Ask yourself whether an existing path is enough to say a word is stored.',
    ],
    leakKeywords: [],
    verification: {
      verdict: 'pass',
      solvedAnswer:
        '(1) All three words share the c → a prefix path; car and cart also share the r node. (2) Set terminal booleans to true at the t ending cat, the r ending car, and the t ending cart. (3) No: the ca path exists, but its terminal boolean is false. (4) Looking up cart takes four pointer steps, one per letter. Adding a million other words does not change that count.',
      reasons: [],
      model: 'openai/gpt-6.1-sol',
    },
    model: 'anthropic/claude-opus-5.5',
    promptVersion: 'draft-items@0.1+seed.1',
  },
]
